BYZ_REGIONS_AFRICA = {
	"mk_reg_al-mahdiya",
	"mk_reg_misrata",
	"mk_reg_qusantina",
	"mk_reg_tripoli_libya",
	"mk_reg_tunis",
};

BYZ_REGIONS_ANATOLIA = {
	"mk_reg_ancyra",
	"mk_reg_attaleia",
	"mk_reg_cyzicus",
	"mk_reg_dorylaion",
	"mk_reg_iconion",
	"mk_reg_kayseri",
	"mk_reg_malatya",
	"mk_reg_nicaea",
	"mk_reg_sinope",
	"mk_reg_sis",
	"mk_reg_smyrna",
	"mk_reg_trebizond",
};

BYZ_REGIONS_CYRENAICA = {
	"mk_reg_barca",
	"mk_reg_mersa_matruh",
};

BYZ_REGIONS_DALMATIA = {
	"mk_reg_ras",
	"mk_reg_split",
	"mk_reg_visoko",
	"mk_reg_zagreb",
};

BYZ_REGIONS_EGYPT = {
	"mk_reg_alexandria",
	"mk_reg_aydhab",
	"mk_reg_cairo",
	"mk_reg_damietta",
	"mk_reg_minya",
	"mk_reg_qus",
};

BYZ_REGIONS_ITALY = {
	"mk_reg_ancona",
	"mk_reg_bologna",
	"mk_reg_genoa",
	"mk_reg_milan",
	"mk_reg_naples",
	"mk_reg_palermo",
	"mk_reg_pisa",
	"mk_reg_reggio",
	"mk_reg_rome",
	"mk_reg_syracuse",
	"mk_reg_taranto",
	"mk_reg_turin",
	"mk_reg_venice",
	"mk_reg_verona",
};

BYZ_REGIONS_GREECE = {
	"mk_reg_athens",
	"mk_reg_arta",
	"mk_reg_dyrrhachium",
	"mk_reg_mystras",
	"mk_reg_philippopolis",
	"mk_reg_thessalonica",
};

BYZ_REGIONS_ORIENS = {
	"mk_reg_acre",
	"mk_reg_antioch",
	"mk_reg_aqaba",
	"mk_reg_damascus",
	"mk_reg_homs",
	"mk_reg_kerak",
	"mk_reg_jerusalem",
	"mk_reg_tripoli_levant",
};

BYZ_REGIONS_PENTARCHY = {
	"mk_reg_alexandria",
	"mk_reg_rome",
	"mk_reg_jerusalem",
	"mk_reg_antioch",
	"mk_reg_constantinopolis",
};

REGIONS_ROME = {
	"mk_reg_acre",
	"mk_reg_al-mahdiya",
	"mk_reg_alexandria",
	"mk_reg_ancyra",
	"mk_reg_antioch",
	"mk_reg_aqaba",
	"mk_reg_attaleia",
	"mk_reg_aydhab",
	"mk_reg_bologna",
	"mk_reg_cairo",
	"mk_reg_constantinopolis",
	"mk_reg_cyzicus",
	"mk_reg_damascus",
	"mk_reg_dorylaion",
	"mk_reg_dyrrhachium",
	"mk_reg_genoa",
	"mk_reg_homs",
	"mk_reg_iconion",
	"mk_reg_jerusalem",
	"mk_reg_kayseri",
	"mk_reg_malatya",
	"mk_reg_milan",
	"mk_reg_misrata",
	"mk_reg_mystras",
	"mk_reg_naples",
	"mk_reg_nicaea",
	"mk_reg_philippopolis",
	"mk_reg_pisa",
	"mk_reg_qusantina",
	"mk_reg_ras",
	"mk_reg_reggio",
	"mk_reg_rome",
	"mk_reg_sinope",
	"mk_reg_sis",
	"mk_reg_smyrna",
	"mk_reg_split",
	"mk_reg_syracuse",
	"mk_reg_taranto",
	"mk_reg_thessalonica",
	"mk_reg_trebizond",
	"mk_reg_tripoli_libya",
	"mk_reg_tunis",
	"mk_reg_turin",
	"mk_reg_venice",
	"mk_reg_verona",
	"mk_reg_zagreb"
};

REGIONS_ROME_FACTION_PIPS_LOCATIONS = {
	["mk_reg_acre"] = {998, 509},
	["mk_reg_al-mahdiya"] = {222, 528},
	["mk_reg_alexandria"] = {790, 658},
	["mk_reg_ancyra"] = {921, 281},
	["mk_reg_antioch"] = {1023, 436},
	["mk_reg_aqaba"] = {974, 638},
	["mk_reg_attaleia"] = {825, 403},
	["mk_reg_aydhab"] = {965, 798},
	["mk_reg_bologna"] = {268, 80},
	["mk_reg_cairo"] = {815, 729},
	["mk_reg_constantinopolis"] = {782, 230},
	["mk_reg_cyzicus"] = {753, 286},
	["mk_reg_damascus"] = {1041, 583},
	["mk_reg_dorylaion"] = {840, 312},
	["mk_reg_dyrrhachium"] = {507, 241},
	["mk_reg_genoa"] = {162, 104},
	["mk_reg_homs"] = {1058, 478},
	["mk_reg_iconion"] = {900, 344},
	["mk_reg_jerusalem"] = {980, 586},
	["mk_reg_kayseri"] = {981, 323},
	["mk_reg_malatya"] = {1066, 325},
	["mk_reg_milan"] = {198, 60},
	["mk_reg_misrata"] = {251, 604},
	["mk_reg_mystras"] = {587, 373},
	["mk_reg_naples"] = {317, 245},
	["mk_reg_nicaea"] = {836, 256},
	["mk_reg_philippopolis"] = {664, 200},
	["mk_reg_pisa"] = {238, 163},
	["mk_reg_qusantina"] = {76, 492},
	["mk_reg_ras"] = {488, 133},
	["mk_reg_reggio"] = {366, 350},
	["mk_reg_rome"] = {285, 219},
	["mk_reg_sinope"] = {987, 238},
	["mk_reg_sis"] = {972, 382},
	["mk_reg_smyrna"] = {764, 359},
	["mk_reg_split"] = {434, 133},
	["mk_reg_syracuse"]  = {329, 429},
	["mk_reg_taranto"] = {393, 281},
	["mk_reg_thessalonica"] = {584, 244},
	["mk_reg_trebizond"] = {1112, 258},
	["mk_reg_tripoli_libya"] = {355, 627},
	["mk_reg_tunis"] = {191, 470},
	["mk_reg_turin"] = {120, 91},
	["mk_reg_venice"] = {321, 49},
	["mk_reg_verona"] = {291, 143},
	["mk_reg_zagreb"] = {437, 64}
};
