BYZ_REGIONS_AFRICA = {
	"att_reg_africa_carthago",
	"att_reg_africa_constantina",
	"att_reg_africa_hadrumentum",
	"att_reg_tripolitana_leptis_magna",
	"att_reg_tripolitana_macomades",
	"att_reg_tripolitana_sabrata",
};

BYZ_REGIONS_ANATOLIA = {
	"att_reg_asia_cyzicus",
	"att_reg_asia_ephesus",
	"att_reg_asia_synnada",
	"att_reg_bithynia_amasea",
	"att_reg_bithynia_ancyra",
	"att_reg_bithynia_nicomedia",
	"att_reg_cappadocia_caesarea_eusebia",
	"att_reg_cappadocia_melitene",
	"att_reg_cappadocia_trapezus",
	"att_reg_cilicia_iconium",
	"att_reg_cilicia_myra",
	"att_reg_cilicia_tarsus",
};

BYZ_REGIONS_CYRENAICA = {
	"att_reg_libya_augila",
	"att_reg_libya_paraetonium",
	"att_reg_libya_ptolemais",
};

BYZ_REGIONS_DALMATIA = {
	"att_reg_dalmatia_domavia",
	"att_reg_dalmatia_salona",
	"att_reg_dalmatia_siscia",
};

BYZ_REGIONS_EGYPT = {
	"att_reg_aegyptus_alexandria",
	"att_reg_aegyptus_berenice",
	"att_reg_aegyptus_oxyrhynchus",
};

BYZ_REGIONS_ITALY = {
	"att_reg_liguria_mediolanum",
	"att_reg_liguria_segusio",
	"att_reg_liguria_genua",
	"att_reg_venetia_verona",
	"att_reg_venetia_aquileia",
	"att_reg_venetia_ravenna",
	"att_reg_italia_fiorentia",
	"att_reg_italia_roma",
	"att_reg_italia_neapolis",
	"att_reg_magna_graecia_tarentum",
	"att_reg_magna_graecia_rhegium",
	"att_reg_magna_graecia_syracusae"
};

BYZ_REGIONS_GREECE = {
	"att_reg_macedonia_corinthus",
	"att_reg_macedonia_dyrrhachium",
	"att_reg_macedonia_thessalonica",
	"att_reg_thracia_trimontium",
};

BYZ_REGIONS_ORIENS = {
	"att_reg_palaestinea_aila",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_palaestinea_nova_trajana_bostra",
	"att_reg_syria_antiochia",
	"att_reg_syria_emesa",
	"att_reg_syria_tyrus",
};

BYZ_REGIONS_PENTARCHY = {
	"att_reg_aegyptus_alexandria",
	"att_reg_italia_roma",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_syria_antiochia",
	"att_reg_thracia_constantinopolis",
};

REGIONS_ROME = {
	"att_reg_aegyptus_alexandria",
	"att_reg_aegyptus_berenice",
	"att_reg_aegyptus_oxyrhynchus",
	"att_reg_africa_carthago",
	"att_reg_africa_constantina",
	"att_reg_africa_hadrumentum",
	"att_reg_asia_cyzicus",
	"att_reg_asia_ephesus",
	"att_reg_asia_synnada",
	"att_reg_bithynia_amasea",
	"att_reg_bithynia_ancyra",
	"att_reg_bithynia_nicomedia",
	"att_reg_cappadocia_caesarea_eusebia",
	"att_reg_cappadocia_melitene",
	"att_reg_cappadocia_trapezus",
	"att_reg_cilicia_iconium",
	"att_reg_cilicia_myra",
	"att_reg_cilicia_tarsus",
	"att_reg_dalmatia_domavia",
	"att_reg_dalmatia_salona",
	"att_reg_dalmatia_siscia",
	"att_reg_liguria_mediolanum",
	"att_reg_liguria_segusio",
	"att_reg_liguria_genua",
	"att_reg_italia_fiorentia",
	"att_reg_italia_roma",
	"att_reg_italia_neapolis",
	"att_reg_macedonia_corinthus",
	"att_reg_macedonia_dyrrhachium",
	"att_reg_macedonia_thessalonica",
	"att_reg_magna_graecia_tarentum",
	"att_reg_magna_graecia_rhegium",
	"att_reg_magna_graecia_syracusae",
	"att_reg_palaestinea_aila",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_palaestinea_nova_trajana_bostra",
	"att_reg_syria_antiochia",
	"att_reg_syria_emesa",
	"att_reg_syria_tyrus",
	"att_reg_thracia_trimontium",
	"att_reg_thracia_constantinopolis",
	"att_reg_tripolitana_leptis_magna",
	"att_reg_tripolitana_macomades",
	"att_reg_tripolitana_sabrata",
	"att_reg_venetia_verona",
	"att_reg_venetia_aquileia",
	"att_reg_venetia_ravenna"
};

REGIONS_ROME_FACTION_PIPS_LOCATIONS = {
	["att_reg_aegyptus_alexandria"] = {790, 658},
	["att_reg_aegyptus_berenice"] = {965, 798},
	["att_reg_aegyptus_oxyrhynchus"] = {815, 729},
	["att_reg_africa_carthago"] = {191, 470},
	["att_reg_africa_constantina"] = {76, 492},
	["att_reg_africa_hadrumentum"] = {222, 528},
	["att_reg_tripolitana_leptis_magna"] = {355, 627},
	["att_reg_tripolitana_macomades"] = {440, 652},
	["att_reg_tripolitana_sabrata"] = {251, 604},
	["att_reg_asia_cyzicus"] = {753, 286},
	["att_reg_asia_ephesus"] = {764, 359},
	["att_reg_asia_synnada"] = {840, 312},
	["att_reg_bithynia_amasea"] = {987, 238},
	["att_reg_bithynia_ancyra"] = {921, 281},
	["att_reg_bithynia_nicomedia"] = {836, 256},
	["att_reg_cappadocia_caesarea_eusebia"] = {981, 323},
	["att_reg_cappadocia_melitene"] = {1066, 325},
	["att_reg_cappadocia_trapezus"] = {1112, 258},
	["att_reg_cilicia_iconium"] = {900, 344},
	["att_reg_cilicia_myra"] = {825, 403},
	["att_reg_cilicia_tarsus"] = {972, 382},
	["att_reg_dalmatia_domavia"] = {488, 133},
	["att_reg_dalmatia_salona"] = {434, 133},
	["att_reg_dalmatia_siscia"] = {437, 64},
	["att_reg_macedonia_corinthus"] = {587, 373},
	["att_reg_macedonia_dyrrhachium"] = {507, 241},
	["att_reg_macedonia_thessalonica"] = {584, 244},
	["att_reg_thracia_trimontium"] = {664, 200},
	["att_reg_thracia_constantinopolis"] = {782, 230},
	["att_reg_palaestinea_aila"] = {974, 638},
	["att_reg_palaestinea_aelia_capitolina"] = {980, 586},
	["att_reg_palaestinea_nova_trajana_bostra"] = {1041, 583},
	["att_reg_syria_antiochia"] = {1023, 436},
	["att_reg_syria_emesa"] = {1058, 478},
	["att_reg_syria_tyrus"] = {998, 509},
	["att_reg_liguria_mediolanum"] = {198, 60},
	["att_reg_liguria_segusio"] = {120, 91},
	["att_reg_liguria_genua"] = {162, 104},
	["att_reg_venetia_verona"] = {268, 80},
	["att_reg_venetia_aquileia"] = {321, 49},
	["att_reg_venetia_ravenna"] = {291, 143},
	["att_reg_italia_fiorentia"] = {238, 163},
	["att_reg_italia_roma"] = {285, 219},
	["att_reg_italia_neapolis"] = {317, 245},
	["att_reg_magna_graecia_tarentum"] = {393, 281},
	["att_reg_magna_graecia_rhegium"] = {366, 350},
	["att_reg_magna_graecia_syracusae"]  = {329, 429}
};
