BYZ_REGIONS_AFRICA = {
	"att_reg_africa_carthago",
	"att_reg_africa_constantina",
	"att_reg_africa_hadrumentum",
	"att_reg_tripolitana_leptis_magna",
	"att_reg_tripolitana_macomades",
	"att_reg_tripolitana_sabrata",
};

BYZ_REGIONS_ANATOLIA = {
	"att_reg_asia_cyzicus",
	"att_reg_asia_ephesus",
	"att_reg_asia_synnada",
	"att_reg_bithynia_amasea",
	"att_reg_bithynia_ancyra",
	"att_reg_bithynia_nicomedia",
	"att_reg_cappadocia_caesarea_eusebia",
	"att_reg_cappadocia_melitene",
	"att_reg_cappadocia_trapezus",
	"att_reg_cilicia_iconium",
	"att_reg_cilicia_myra",
	"att_reg_cilicia_tarsus",
};

BYZ_REGIONS_CYRENAICA = {
	"att_reg_libya_augila",
	"att_reg_libya_paraetonium",
	"att_reg_libya_ptolemais",
};

BYZ_REGIONS_DALMATIA = {
	"att_reg_dalmatia_domavia",
	"att_reg_dalmatia_salona",
	"att_reg_dalmatia_siscia",
};

BYZ_REGIONS_EGYPT = {
	"att_reg_aegyptus_alexandria",
	"att_reg_aegyptus_berenice",
	"att_reg_aegyptus_oxyrhynchus",
};

BYZ_REGIONS_ITALY = {
	"att_reg_liguria_mediolanum",
	"att_reg_liguria_segusio",
	"att_reg_liguria_genua",
	"att_reg_venetia_verona",
	"att_reg_venetia_aquileia",
	"att_reg_venetia_ravenna",
	"att_reg_italia_fiorentia",
	"att_reg_italia_roma",
	"att_reg_italia_neapolis",
	"att_reg_magna_graecia_tarentum",
	"att_reg_magna_graecia_rhegium",
	"att_reg_magna_graecia_syracusae"
};

BYZ_REGIONS_GREECE = {
	"att_reg_macedonia_corinthus",
	"att_reg_macedonia_dyrrhachium",
	"att_reg_macedonia_thessalonica",
	"att_reg_thracia_trimontium",
};

BYZ_REGIONS_ORIENS = {
	"att_reg_palaestinea_aila",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_palaestinea_nova_trajana_bostra",
	"att_reg_syria_antiochia",
	"att_reg_syria_emesa",
	"att_reg_syria_tyrus",
};

BYZ_REGIONS_PENTARCHY = {
	"att_reg_aegyptus_alexandria",
	"att_reg_italia_roma",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_syria_antiochia",
	"att_reg_thracia_constantinopolis",
};

REGIONS_ROME = {
	"att_reg_africa_carthago",
	"att_reg_africa_constantina",
	"att_reg_africa_hadrumentum",
	"att_reg_tripolitana_leptis_magna",
	"att_reg_tripolitana_macomades",
	"att_reg_tripolitana_sabrata",
	"att_reg_asia_cyzicus",
	"att_reg_asia_ephesus",
	"att_reg_asia_synnada",
	"att_reg_bithynia_amasea",
	"att_reg_bithynia_ancyra",
	"att_reg_bithynia_nicomedia",
	"att_reg_cappadocia_caesarea_eusebia",
	"att_reg_cappadocia_melitene",
	"att_reg_cappadocia_trapezus",
	"att_reg_cilicia_iconium",
	"att_reg_cilicia_myra",
	"att_reg_cilicia_tarsus",
	"att_reg_dalmatia_domavia",
	"att_reg_dalmatia_salona",
	"att_reg_dalmatia_siscia",
	"att_reg_aegyptus_alexandria",
	"att_reg_aegyptus_berenice",
	"att_reg_aegyptus_oxyrhynchus",
	"att_reg_liguria_mediolanum",
	"att_reg_liguria_segusio",
	"att_reg_liguria_genua",
	"att_reg_venetia_verona",
	"att_reg_venetia_aquileia",
	"att_reg_venetia_ravenna",
	"att_reg_italia_fiorentia",
	"att_reg_italia_roma",
	"att_reg_italia_neapolis",
	"att_reg_magna_graecia_tarentum",
	"att_reg_magna_graecia_rhegium",
	"att_reg_magna_graecia_syracusae",
	"att_reg_macedonia_corinthus",
	"att_reg_macedonia_dyrrhachium",
	"att_reg_macedonia_thessalonica",
	"att_reg_thracia_trimontium",
	"att_reg_thracia_constantinopolis",
	"att_reg_palaestinea_aila",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_palaestinea_nova_trajana_bostra",
	"att_reg_syria_antiochia",
	"att_reg_syria_emesa",
	"att_reg_syria_tyrus"
};

REGIONS_ROME_FACTION_PIPS_LOCATIONS = {
	["att_reg_aegyptus_alexandria"] = {762, 658},
	["att_reg_aegyptus_berenice"] = {937, 798},
	["att_reg_aegyptus_oxyrhynchus"] = {787, 729},
	["att_reg_africa_carthago"] = {163, 470},
	["att_reg_africa_constantina"] = {48, 492},
	["att_reg_africa_hadrumentum"] = {194, 528},
	["att_reg_tripolitana_leptis_magna"] = {327, 627},
	["att_reg_tripolitana_macomades"] = {412, 652},
	["att_reg_tripolitana_sabrata"] = {223, 604},
	["att_reg_asia_cyzicus"] = {725, 286},
	["att_reg_asia_ephesus"] = {736, 359},
	["att_reg_asia_synnada"] = {812, 312},
	["att_reg_bithynia_amasea"] = {959, 238},
	["att_reg_bithynia_ancyra"] = {893, 281},
	["att_reg_bithynia_nicomedia"] = {808, 256},
	["att_reg_cappadocia_caesarea_eusebia"] = {953, 323},
	["att_reg_cappadocia_melitene"] = {1038, 325},
	["att_reg_cappadocia_trapezus"] = {1084, 258},
	["att_reg_cilicia_iconium"] = {872, 344},
	["att_reg_cilicia_myra"] = {797, 403},
	["att_reg_cilicia_tarsus"] = {944, 382},
	["att_reg_dalmatia_domavia"] = {460, 133},
	["att_reg_dalmatia_salona"] = {406, 133},
	["att_reg_dalmatia_siscia"] = {409, 64},
	["att_reg_macedonia_corinthus"] = {559, 373},
	["att_reg_macedonia_dyrrhachium"] = {479, 241},
	["att_reg_macedonia_thessalonica"] = {556, 244},
	["att_reg_thracia_trimontium"] = {636, 200},
	["att_reg_thracia_constantinopolis"] = {728, 222},
	["att_reg_palaestinea_aila"] = {946, 638},
	["att_reg_palaestinea_aelia_capitolina"] = {952, 586},
	["att_reg_palaestinea_nova_trajana_bostra"] = {1013, 583},
	["att_reg_syria_antiochia"] = {995, 436},
	["att_reg_syria_emesa"] = {1030, 478},
	["att_reg_syria_tyrus"] = {970, 509},
	["att_reg_liguria_mediolanum"] = {170, 60},
	["att_reg_liguria_segusio"] = {92, 91},
	["att_reg_liguria_genua"] = {134, 104},
	["att_reg_venetia_verona"] = {240, 80},
	["att_reg_venetia_aquileia"] = {293, 49},
	["att_reg_venetia_ravenna"] = {263, 143},
	["att_reg_italia_fiorentia"] = {210, 163},
	["att_reg_italia_roma"] = {257, 219},
	["att_reg_italia_neapolis"] = {289, 245},
	["att_reg_magna_graecia_tarentum"] = {365, 281},
	["att_reg_magna_graecia_rhegium"] = {338, 350},
	["att_reg_magna_graecia_syracusae"]  = {301, 429}
};