----------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------
--
-- 	MEDIEVAL KINGDOMS 1212 - COMMON UI: UNIT INFORMATION LISTS
-- 	By: DETrooper
--
----------------------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------------------------------------------
-- This is kind of shit since I should probably import everything related to units from DB into lua tables
-- and then go from there, calculating the unit stats that way instead of manually inputting the numbers.

unit_info = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {["num_men"] = 160, ["upkeep"] = 174, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_spear_land", ["tier"] = 1},
	["mk_mio_t1_templar_sergeant_spearmen"] = {["num_men"] = 160, ["upkeep"] = 174, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_spear_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {["num_men"] = 160, ["upkeep"] = 307, ["unit_weight"] = "heavy", ["unit_type"] = "att_inf_sword_land", ["tier"] = 1},
	["mk_mio_t1_templar_knights_dismounted"] = {["num_men"] = 160, ["upkeep"] = 307, ["unit_weight"] = "heavy", ["unit_type"] = "att_inf_sword_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {["num_men"] = 130, ["upkeep"] = 222, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_crossbow_land", ["tier"] = 1},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {["num_men"] = 130, ["upkeep"] = 222, ["unit_weight"] = "medium", ["unit_type"] = "att_inf_crossbow_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {["num_men"] = 80, ["upkeep"] = 274, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_hospitaller_knights"] = {["num_men"] = 80, ["upkeep"] = 463, ["unit_weight"] = "heavy", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_templar_mounted_sergeants"] = {["num_men"] = 80, ["upkeep"] = 274, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_templar_knights"] = {["num_men"] = 80, ["upkeep"] = 463, ["unit_weight"] = "heavy", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_teu_mounted_sergeants"] = {["num_men"] = 80, ["upkeep"] = 274, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_teu_sariantbruder"] = {["num_men"] = 80, ["upkeep"] = 319, ["unit_weight"] = "medium", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
	["mk_mio_t1_teu_ritterbruder"] = {["num_men"] = 80, ["upkeep"] = 463, ["unit_weight"] = "heavy", ["unit_type"] = "att_cav_shock_land", ["tier"] = 1},
};

unit_stats = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {["melee_attack"] = 34, ["weapon_damage"] = 29, ["charge_bonus"] = 15, ["melee_defence"] = 33, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_block_chance"] = 25, ["bonus_vs_cavalry"] = 12},
	["mk_mio_t1_templar_sergeant_spearmen"] = {["melee_attack"] = 34, ["weapon_damage"] = 29, ["charge_bonus"] = 15, ["melee_defence"] = 33, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_block_chance"] = 25, ["bonus_vs_cavalry"] = 12},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {["melee_attack"] = 38, ["weapon_damage"] = 26, ["charge_bonus"] = 30, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 100, ["morale"] = 50, ["speed"] = 30, ["missile_block_chance"] = 40},
	["mk_mio_t1_templar_knights_dismounted"] = {["melee_attack"] = 38, ["weapon_damage"] = 26, ["charge_bonus"] = 30, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 100, ["morale"] = 50, ["speed"] = 30, ["missile_block_chance"] = 40},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 26, ["melee_defence"] = 15, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_damage"] = 48, ["ammo"] = 30, ["reloading"] = 23, ["weapon_range"] = 145, ["accuracy"] = 15},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 26, ["melee_defence"] = 15, ["armour"] = 25, ["health"] = 100, ["morale"] = 35, ["speed"] = 30, ["missile_damage"] = 48, ["ammo"] = 30, ["reloading"] = 23, ["weapon_range"] = 145, ["accuracy"] = 15},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 30, ["armour"] = 25, ["health"] = 150, ["morale"] = 35, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_hospitaller_knights"] = {["melee_attack"] = 38, ["weapon_damage"] = 27, ["charge_bonus"] = 155, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 150, ["morale"] = 50, ["speed"] = 75, ["missile_block_chance"] = 40},
	["mk_mio_t1_templar_mounted_sergeants"] =  {["melee_attack"] = 30, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 30, ["armour"] = 25, ["health"] = 150, ["morale"] = 35, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_templar_knights"] = {["melee_attack"] = 38, ["weapon_damage"] = 27, ["charge_bonus"] = 155, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 150, ["morale"] = 50, ["speed"] = 75, ["missile_block_chance"] = 40},
	["mk_mio_t1_teu_mounted_sergeants"] = {["melee_attack"] = 30, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 30, ["armour"] = 25, ["health"] = 150, ["morale"] = 35, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_teu_sariantbruder"] = {["melee_attack"] = 35, ["weapon_damage"] = 29, ["charge_bonus"] = 95, ["melee_defence"] = 35, ["armour"] = 25, ["health"] = 150, ["morale"] = 50, ["speed"] = 90, ["missile_block_chance"] = 25},
	["mk_mio_t1_teu_ritterbruder"] = {["melee_attack"] = 38, ["weapon_damage"] = 27, ["charge_bonus"] = 155, ["melee_defence"] = 37, ["armour"] = 55, ["health"] = 150, ["morale"] = 50, ["speed"] = 75, ["missile_block_chance"] = 40},
};

unit_bullet_points = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {"positive|Good Armour-piercing Damage|", "negative|Poor Armour|", "negative|Poor Missile Block Chance|"},
	["mk_mio_t1_templar_sergeant_spearmen"] = {"positive|Good Armour-piercing Damage|", "negative|Poor Armour|", "negative|Poor Missile Block Chance|"},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {"very_positive|Excellent Morale|", "very_negative|Very Poor Armour-piercing Damage|", "positive|Good Armour|"},
	["mk_mio_t1_templar_knights_dismounted"] = {"very_positive|Excellent Morale|", "very_negative|Very Poor Armour-piercing Damage|", "positive|Good Armour|"},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {"very_negative|Very Poor Missile Block Chance|", "positive|High Ammunition|", "negative|Poor Armour-Piercing Damage|"},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {"very_negative|Very Poor Missile Block Chance|", "positive|High Ammunition|", "negative|Poor Armour-Piercing Damage|"},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {"positive|High Health|", "positive|Good Charge Bonus|", "negative|Poor Armour|"},
	["mk_mio_t1_hospitaller_knights"] = {"very_positive|Excellent Charge Bonus|", "very_positive|Excellent Morale|", "positive|High Health|"},
	["mk_mio_t1_templar_mounted_sergeants"] = {"positive|High Health|", "positive|Good Charge Bonus|", "negative|Poor Armour|"},
	["mk_mio_t1_templar_knights"] = {"very_positive|Excellent Charge Bonus|", "very_positive|Excellent Morale|", "positive|High Health|"},
	["mk_mio_t1_teu_mounted_sergeants"] = {"positive|High Health|", "positive|Good Charge Bonus|", "negative|Poor Armour|"},
	["mk_mio_t1_teu_sariantbruder"] = {"very_positive|Excellent Morale|", "positive|High Health|", "positive|Good Charge Bonus|"},
	["mk_mio_t1_teu_ritterbruder"] = {"very_positive|Excellent Charge Bonus|", "very_positive|Excellent Morale|", "positive|High Health|"}
};

unit_abilities = {
	["mk_mio_t1_hospitaller_sergeant_spearmen"] = {"form_hoplite_phalanx", "a_mp_test_7", "hide_forest"},
	["mk_mio_t1_templar_sergeant_spearmen"] = {"form_hoplite_phalanx", "a_mp_test_7", "hide_forest"},
	["mk_mio_t1_hospitaller_knights_dismounted"] = {"form_shield_wall", "a_mp_test_6", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_templar_knights_dismounted"] = {"form_shield_wall", "a_mp_test_6", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_hospitaller_crossbowmen_sergeants"] = {"a_mp_test_7", "mk_crossbow_early", "mk_crossbow_extended", "hide_forest"},
	["mk_mio_t1_templar_crossbowmen_sergeants"] = {"a_mp_test_7", "mk_crossbow_early", "mk_crossbow_extended", "hide_forest"},
	["mk_mio_t1_hospitaller_mounted_sergeants"] = {"a_mp_test_7", "hide_forest"},
	["mk_mio_t1_hospitaller_knights"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_templar_mounted_sergeants"] = {"a_mp_test_7", "hide_forest"},
	["mk_mio_t1_templar_knights"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest", "scare_immune"},
	["mk_mio_t1_teu_mounted_sergeants"] = {"form_wedge", "a_mp_test_7", "hide_forest"},
	["mk_mio_t1_teu_sariantbruder"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest"},
	["mk_mio_t1_teu_ritterbruder"] = {"form_wedge", "a_mp_test_7", "disciplined", "hide_forest", "scare_immune"}
};

unit_stats_ordered = {"melee_attack", "weapon_damage", "charge_bonus", "melee_defence", "armour", "health", "morale", "speed", "missile_block_chance", "missile_damage", "ammo", "reloading", "weapon_range", "accuracy", "bonus_vs_cavalry"};

ui_unit_groupings = {
	["art_fix"] = {"Fixed Artillery", "Fixed position artillery units that pack quite a punch, they are nevertheless very weak if engaged in melee."},
	["art_fld"] = {"Field Artillery", "With a long range and able to cause great damage, field artillery units can be moved slowly around the battlefield, but are very weak if engaged in melee."},
	["art_siege"] = {"Siege Artillery", "Huge siege engines perfect for knocking down walls and gatehouses."},
	["att_art_field_land"] = {"Artillery", "With a long range and able to cause great damage, field artillery units can be moved slowly around the battlefield, but are very weak if engaged in melee."},
	["att_art_field_naval"] = {"Artillery", "With a long range and able to cause great damage, field artillery units can be moved slowly around the battlefield, but are very weak if engaged in melee."},
	["att_art_scorpio"] = {"Scorpio", "With a long range and able to cause great damage, field artillery units can be moved slowly around the battlefield, but are very weak if engaged in melee."},
	["att_cav_bow_land"] = {"Bow Cavalry", "Fast moving and long range, missile cavalry are great at harassing their enemies, but weak if pinned down in melee."},
	["att_cav_crossbow_land"] = {"Crossbow Cavalry", "Fast moving and mid-range, missile cavalry are great at harassing their enemies, but weak if pinned down in melee."},
	["att_cav_elephant_land"] = {"Elephant", "There's nothing quite like elephants to make a hole in an enemy line. Flaming projectiles and javelins are the best way to counter them."},
	["att_cav_javelin_land"] = {"Skirmisher Cavalry", "Fast moving and short-range, missile cavalry are great at harassing their enemies, but weak if pinned down in melee."},
	["att_cav_melee_land"] = {"Melee Cavalry", "Although versatile units protected by shields, melee cavalry are weak against more specialised units."},
	["att_cav_shock_land"] = {"Shock Cavalry", "The hammer to the infantry of any army, they are devastating when charged into the flank or rear of enemies."},
	["att_inf_axe_land"] = {"Axe Infantry", "Frontline soldiers trained for hand-to-hand combat."},
	["att_inf_axe_marine"] = {"Axe Infantry", "Frontline soldiers trained for hand-to-hand combat."},
	["att_inf_axe_naval"] = {"Assault Ship", "Frontline soldiers trained for hand-to-hand combat."},
	["att_inf_bow_land"] = {"Bow Infantry", "Long-range units who provide support for melee units, but are themselves very weak in close combat."},
	["att_inf_bow_marine"] = {"Bow Infantry", "Long-range units who provide support for melee units, but are themselves very weak in close combat."},
	["att_inf_bow_naval"] = {"Bow Ship", "Long-range units who provide support for melee units, but are themselves very weak in close combat."},
	["att_inf_crossbow_land"] = {"Crossbow Infantry", "Mid-range units with exceptional armour-piercing ability, but slow reload speed."},
	["att_inf_crossbow_marine"] = {"Crossbow Infantry", "Mid-range units with exceptional armour-piercing ability, but slow reload speed."},
	["att_inf_crossbow_naval"] = {"Crossbow Ship", "Mid-range units with exceptional armour-piercing ability, but slow reload speed."},
	["att_inf_gun_land"] = {"Handgunner Infantry", "Gunpowder-based Mid-range units with exceptional armour-piercing ability, but slow reload speed."},
	["att_inf_javelin_land"] = {"Skirmisher", "Short-range units that can take exceptionally high damage."},
	["att_inf_javelin_marine"] = {"Skirmisher", "Short-range units that can take exceptionally high damage."},
	["att_inf_javelin_naval"] = {"Skirmisher", "Short-range units that can take exceptionally high damage."},
	["att_inf_pike_land"] = {"Pike Infantry", "Long pikes make these troops deadly from the front but vulnerable if flanked. They are highly effective against cavalry."},
	["att_inf_polearm_land"] = {"Polearm Infantry", "Polearms make these troops deadly from the front but vulnerable if flanked. They are highly effective against cavalry."},
	["att_inf_polearm_shock_land"] = {"Shock Infantry", "Hard-hitting Frontline soldiers with Great Weapons for armoured combat"},
	["att_inf_sling_land"] = {"Slinger", "Mid-range units with exceptional high rate of fire."},
	["att_inf_sling_marine"] = {"Slinger", "Mid-range units with exceptional high rate of fire."},
	["att_inf_sling_naval"] = {"Slinger", "Mid-range units with exceptional high rate of fire."},
	["att_inf_spear_bow_land"] = {"Spear-Bow Infantry", "Dual Purpose Soldiers capable of both forming the battleline and peppering the enemy from afar"},
	["att_inf_spear_land"] = {"Spear Infantry", "Solid defensive infantry protected by shields, they are very good when ranged against cavalry."},
	["att_inf_sword_bow_land"] = {"Ranged Melee Infantry", "Dual Purpose Soldiers capable of both forming the battleline and peppering the enemy from afar"},
	["att_inf_sword_land"] = {"Melee Infantry", "Frontline soldiers trained for hand-to-hand combat with their enemies."},
	["att_inf_sword_marine"] = {"Melee Infantry", "Frontline soldiers trained for hand-to-hand combat with their enemies."},
	["att_inf_sword_naval"] = {"Melee Ship", "Frontline soldiers trained for hand-to-hand combat with their enemies."},
	["att_special_fireship_naval"] = {"Fireship", "Capable of settling other ships alight."},
	["att_special_greek_fire_land"] = {"Greek Fire Thrower", "Spewing unquenchable flames, these units can burn any enemy to agonizing deaths. However, they're few in numbers and cannot bring much fuel"},
	["att_special_grenade_land"] = {"Naft Thrower", "These units can throw powerful grenades to cause great damage to the enemy, but are weak if engaged in melee due to their low numbers."},
	["att_special_grenade_marine"] = {"Naft Thrower", "These units can throw powerful grenades to cause great damage to the enemy, but are weak if engaged in melee due to their low numbers."},
	["att_special_grenade_naval"] = {"Naft Thrower", "These units can throw powerfull grenades to cause great damage to the enemy, but are weak if engaged in combat due to their low numbers."},
	["att_special_ram_naval"] = {"Ramming Ship", "Full speed ahead!"},
	["att_special_transportship_naval"] = {"Transport Ship", "Slow but with plenty of space, they do their job well. Just remember that they aren't warships."},
	["att_special_wardog_land"] = {"Warhounds", "War dogs are great to attack lightly armoured units."},
	["carroccio"] = {"Carroccio", "."},
	["cav_mel"] = {"Melee Cavalry", "Although they are versatile units protected by shields, melee cavalry are weak against more specialised units."},
	["cav_mis"] = {"Missile Cavalry", "Fast moving and with a long range, missile cavalry are great at harassing their enemies, but weak if pinned down in melee."},
	["cav_shk"] = {"Shock Cavalry", "The hammer to the infantry of any army, they are devastating when charged into the flank or rear of enemies."},
	["chariot"] = {"Chariot", "Fast moving units with a wide turning circle, they can punch through weak enemy units. They are vulnerable if pinned down in combat."},
	["com"] = {"Command", "These are small units that protect the general whilst he gets on with his job."},
	["elph"] = {"Elephant", "There's nothing quite like elephants to make a hole in an enemy line. Flaming projectiles and javelins are the best way to counter them."},
	["inf_mel"] = {"Melee Infantry", "Frontline soldiers trained for hand-to-hand combat with their enemies."},
	["inf_mis"] = {"Missile Infantry", "Long range units who provide support for melee units, but are themselves very weak in close combat."},
	["inf_pik"] = {"Pike Infantry", "Long pikes make these troops deadly from the front but vulnerable if flanked. They are highly effective against cavalry."},
	["inf_sling"] = {"Slinger", "placeholder"},
	["inf_spr"] = {"Spear Infantry", "Solid defensive infantry protected by shields, they are very good when ranged against cavalry."},
	["ltd_hussite_warwagon"] = {"War Wagon", "."},
	["ltd_medieval_tent"] = {"Tent", "."},
	["shp_art"] = {"Artillery Ship", "These ships can do a lot of damage from long range, but can be neutralised by boarding and ramming."},
	["shp_mel"] = {"Melee Ship", "Perfect for taking out enemy ships, but have to close quickly and board to be successful."},
	["shp_mis"] = {"Missile Ship", "Enemy ships can be showered with their projectiles, but they must steer clear of enemy melee ships."},
	["shp_trn"] = {"Transport Ship", "Slow but with plenty of space, they do their job well. Just remember that they aren't warships."},
	["spcl"] = {"Special", "Nothing says 'surprise!' like unleashing animals on the battlefield."},
};

ui_unit_stats = {
	["scalar_bracing"] = {"Entity Mass", "Mass of each entity in the unit.", 1000},
	["scalar_entity_acceleration_modifier"] = {"Acceleration", "The rate at which the unit accelerates.", 100},
	["scalar_entity_charge_speed_modifier"] = {"Charge Speed", "The additional speed used for charging the final distance to the target.", 100},
	["scalar_entity_deceleration_modifier"] = {"Deceleration", "The rate that the unit slows to a stop.", 100},
	["scalar_spotting_range"] = {"Spotting Range", "A way to change the default range at which a unit can spot others hiding.", 100},
	["stat_accuracy"] = {"Accuracy", "The likelihood of hitting the enemy when firing.", 75},
	["stat_ammo"] = {"Ammunition", "The amount of ammunition this unit can carry into battle.||Once this has been exhausted the unit will be forced to switch to melee to continue fighting.||After the battle, ammunition is fully replenished.", 50},
	["stat_armour"] = {"Armour", "How resistant a unit is to missile fire and melee attacks.", 120},
	["stat_attack"] = {"Attack", "Unit's attack potential", 100},
	["stat_bonus_vs_cavalry"] = {"Attack Against Cavalry", "The melee bonus this unit receives when fighting against cavalry and elephants.", 60},
	["stat_bonus_vs_elephants"] = {"Attack Against Elephants", "The melee bonus this unit receives when fighting against elephants.", 60},
	["stat_bonus_vs_infantry"] = {"Attack Against Infantry", "The melee bonus this unit receives when fighting against infantry.", 60},
	["stat_capture_power"] = {"Capture Power", "How fast a unit can capture different locations in settlement battles.", 25},
	["stat_charge_bonus"] = {"Charge Bonus", "This increases a unit's melee attack and damage when charging. This does not represent the physical impact of the charge.", 300},
	["stat_defence"] = {"Defence", "Unit's defence potential", 100},
	["stat_first_strike"] = {"First Strike", "Determines who strikes first at the beginning of combat.", 100},
	["stat_health"] = {"Health", "This determines how many hits a unit can withstand alongside armour and melee defence.", 350},
	["stat_hiding"] = {"Hiding", "How well this unit can hide.", 100},
	["stat_melee_attack"] = {"Melee Attack", "This determines the chance of a successful hit on the enemy when the unit is engaged in melee.||Battle-hardened troops will gain experience through melee, improving this skill.", 75},
	["stat_melee_damage_ap"] = {"Armour-piercing Damage", "Melee Damage Ap", 25},
	["stat_melee_damage_base"] = {"Melee Base Damage", "Melee Damage Base", 75},
	["stat_melee_defence"] = {"Melee Defence", "This determines the chance of a unit being hit whilst in melee.||This only works in melee and provides no protection from missiles!", 75},
	["stat_men_count"] = {"Men Count", "Default number of men a unit has.", 120},
	["stat_missile_block_chance"] = {"Missile Block Chance", "The percentage chance that the shield will block (non-artillery) missiles. (%)", 100},
	["stat_missile_damage"] = {"Missile Damage", "The damage caused by a missile attack, split between base, armour piercing and explosive.||Armour-piercing damage is always applied, base and explosive damage can be blocked by armour.||Explosive damage has an area of effect.", 100},
	["stat_missile_damage_ap"] = {"Armour-Piercing Damage", "Ranged AP Damage", 50},
	["stat_missile_damage_base"] = {"Missile Base Damage", "Ranged Base Damage", 100},
	["stat_morale"] = {"Morale", "A unit with high morale is less likely to rout in the face of danger. Morale is improved by experience in battle.", 75},
	["stat_reloading"] = {"Rate of Fire", "The rate at which this unit can fire.||This is improved with experience.", 100},
	["stat_remaining_ammo"] = {"Added Ammunition", "Adding ammunition to naval units.", 20},
	["stat_shield_armour"] = {"Shield Armour", "Reduced damage due to shield.", 75},
	["stat_shield_defence"] = {"Shield Defence", "Defence or evasion bonus attained from the shield.", 45},
	["stat_ship_douse_fire"] = {"Douse Fire", "Douse Fire", 10},
	["stat_ship_health"] = {"Hull Strength", "Ship Health", 2500},
	["stat_ship_health_fire"] = {"Fire Resistance", "How much fire damage the ship can sustain before catching fire.", 2000},
	["stat_ship_move_speed"] = {"Speed", "How quickly the ship is able to move.", 100},
	["stat_speed"] = {"Speed", "The speed at which the unit moves around the battlefield.", 120},
	["stat_spotting"] = {"Spotting", "From how far a unit can spot enemies.", 1000},
	["stat_weapon_damage"] = {"Melee Damage", "The damage caused by a unit's weapon, split between base and armour piercing.||Armour-piercing damage is always applied; base damage can be blocked by armour.", 75},
	["stat_weapon_range"] = {"Range", "A long range enables you to hit enemies from a distance, but weapons are still more accurate at shorter ranges.", 500}
}

unit_weights_texts = {
	["very_light"] = "Very Light",
	["light"] = "Light",
	["medium"] = "Medium",
	["heavy"] = "Heavy",
	["very_heavy"] = "Very Heavy",
	["super_heavy"] = "Super Heavy"
};
