-- Faction group strengths/weaknessess should correspond to the first faction in the faction group.

FACTION_STRENGTHS = {
	att_fact_group_iberiamoors  = "Faction Strength: PLACEHOLDER", -- mk_fact_hafsids
	att_fact_group_france = "Faction Strength: PLACEHOLDER", -- mk_fact_flanders
	att_fact_group_northsea = "Faction Strength: PLACEHOLDER", -- mk_fact_norway
	att_fact_group_italia = "Faction Strength: PLACEHOLDER", -- mk_fact_sicily
	att_fact_group_germania = "Faction Strength: PLACEHOLDER", -- mk_fact_schwyz
	att_fact_group_barbarian = "Faction Strength: PLACEHOLDER", -- mk_fact_croatia
	att_fact_group_roman = "Faction Strength: PLACEHOLDER", -- mk_fact_teutonicorder
	att_fact_group_barbarian_m = "Faction Strength: PLACEHOLDER", -- mk_fact_armenia
	att_fact_group_arabia = "Faction Strength: PLACEHOLDER", -- mk_fact_ayyubids
	att_fact_group_nomadic = "Faction Strength: PLACEHOLDER",-- mk_fact_goldenhorde
	att_fact_group_eastern = "Faction Strength: PLACEHOLDER", -- mk_fact_georgia
	mk_fact_abbasids = "Faction Strength: Diverse Roster",
	mk_fact_almohads = "Faction Strength: Large Territory",
	mk_fact_antioch = "Faction Strength: Unique Holy Order Units",
	mk_fact_aragon = "Faction Strength: Good Heavy Infantry",
	mk_fact_armenia = "Faction Strength: Diverse Roster",
	mk_fact_austria = "Faction Strength: Good Infantry & Cavalry",
	mk_fact_ayyubids = "Faction Strength: Good Economy",
	mk_fact_bohemia = "Faction Strength: Diverse Roster",
	mk_fact_bologna = "Faction Strength: PLACEHOLDER",
	mk_fact_bulgaria = "Faction Strength: Diverse Roster",
	mk_fact_burgundy = "Faction Strength: Exceptional Cavalry",
	mk_fact_castile = "Faction Strength: Strong Infantry & Cavalry",
	mk_fact_croatia = "Faction Strength: Stable Realm",
	mk_fact_cumans = "Faction Strength: Good Horse Archers",
	mk_fact_denmark = "Faction Strength: Strong Infantry",
	mk_fact_earldoms = "Faction Strength: PLACEHOLDER",
	mk_fact_england = "Faction Strength: Exceptional Archers",
	mk_fact_epirus = "Faction Strength: Strong Infantry & Cavalry",
	mk_fact_flanders = "Faction Strength: Diverse Roster",
	mk_fact_france = "Faction Strength: Exceptional Cavalry",
	mk_fact_genoa = "Faction Strength: Strong Economy",
	mk_fact_georgia = "Faction Strength: Very Strong Roster",
	mk_fact_ghurids = "Faction Strength: Exceptional Cavalry & Elephants",
	mk_fact_goldenhorde = "Faction Strength: Good Horse Archers",
	mk_fact_hafsids = "Faction Strength: Strong Economy",
	mk_fact_hre = "Faction Strength: Many Client States",
	mk_fact_hungary = "Faction Strength: Good Cavalry & Ranged",
	mk_fact_ildegizids = "Faction Strength: Rapid Expander",
	mk_fact_ilkhanate = "Faction Strength: Good Horse Archers",
	mk_fact_ireland = "Faction Strength: PLACEHOLDER",
	mk_fact_jerusalem = "Faction Strength: Unique Holy Order Units",
	mk_fact_khwarazm = "Faction Strength: Good Mercenaries",
	mk_fact_kiev = "Faction Strength: Religious Stability",
	mk_fact_latinempire = "Faction Strength: High Loyalty",
	mk_fact_lesserpoland = "Faction Strength: Good Infantry & Cavalry",
	mk_fact_lithuania = "Faction Strength: Good Cavalry & Ranged",
	mk_fact_lorraine = "Faction Strength: Good Infantry & Cavalry",
	mk_fact_makuria = "Faction Strength: Exceptional Archers",
	mk_fact_marinids = "Faction Strength: Diverse Roster",
	mk_fact_milan = "Faction Strength: Exceptional Crossbowmen",
	mk_fact_navarre = "Faction Strength: PLACEHOLDER",
	mk_fact_nicaea = "Faction Strength: Strong Professional Units",
	mk_fact_norway = "Faction Strength: Strong Navy",
	mk_fact_papacy = "Faction Strength: PLACEHOLDER",
	mk_fact_pisa = "Faction Strength: Strong Economy",
	mk_fact_portugal = "Faction Strength: Good Cavalry & Shock Infantry",
	mk_fact_schwyz = "Faction Strength: Exceptional Heavy Infantry",
	mk_fact_scotland = "Faction Strength: Strong Spear Infantry",
	mk_fact_seljuks = "Faction Strength: Exceptional Cavalry",
	mk_fact_serbia = "Faction Strength: Exceptional Cavalry",
	mk_fact_sicily = "Faction Strength: Strong Infantry",
	mk_fact_sweden = "Faction Strength: Secure Home",
	mk_fact_teutonicorder = "Faction Strength: Exceptional Cavalry",
	mk_fact_toulouse = "Faction Strength: Religious Tolerance",
	mk_fact_trebizond = "Faction Strength: Good Archers & Cavalry",
	mk_fact_trier = "Faction Strength: Good Infantry & Cavalry",
	mk_fact_venice = "Faction Strength: Strong Economy",
	mk_fact_volga = "Faction Strength: Strong Trade",
	mk_fact_wallachia = "Faction Strength: Expert Ambushers",
	mk_fact_zagwe = "Faction Strength: Secure Home",
	mk_fact_zengids = "Faction Strength: Religious Stability",
	att_fact_visigothi = "Faction Strength: PLACEHOLDER",
	att_fact_ostrogothi = "Faction Strength: PLACEHOLDER"
};

FACTION_WEAKNESSES = {
	att_fact_group_iberiamoors = "Faction Weakness: PLACEHOLDER", -- mk_fact_hafsids
	att_fact_group_france = "Faction Weakness: PLACEHOLDER", -- mk_fact_flanders
	att_fact_group_northsea = "Faction Weakness: PLACEHOLDER", -- mk_fact_norway
	att_fact_group_italia = "Faction Weakness: PLACEHOLDER", -- mk_fact_sicily
	att_fact_group_germania = "Faction Weakness: PLACEHOLDER", -- mk_fact_schwyz
	att_fact_group_barbarian = "Faction Weakness: PLACEHOLDER", -- mk_fact_croatia
	att_fact_group_roman = "Faction Weakness: PLACEHOLDER", -- mk_fact_teutonicorder
	att_fact_group_barbarian_m = "Faction Weakness: PLACEHOLDER", -- mk_fact_armenia
	att_fact_group_arabia = "Faction Weakness: PLACEHOLDER", -- mk_fact_ayyubids
	att_fact_group_nomadic = "Faction Weakness: PLACEHOLDER", -- mk_fact_goldenhorde
	att_fact_group_eastern = "Faction Weakness: PLACEHOLDER", -- mk_fact_georgia
	mk_fact_abbasids = "Faction Weakness: Few Avenues of Expansion",
	mk_fact_almohads = "Faction Weakness: Religious Turmoil",
	mk_fact_antioch = "Faction Weakness: Religious Turmoil",
	mk_fact_aragon = "Faction Weakness: No Archer Units",
	mk_fact_armenia = "Faction Weakness: Small Garrisons",
	mk_fact_austria = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_ayyubids = "Faction Weakness: Crusade Target",
	mk_fact_bohemia = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_bologna = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_bulgaria = "Faction Weakness: Religious Enemies",
	mk_fact_burgundy = "Faction Weakness: Vassal of France",
	mk_fact_castile = "Faction Weakness: Few Anti-Cavalry Units",
	mk_fact_croatia = "Faction Weakness: Vassal of Hungary",
	mk_fact_cumans = "Faction Weakness: Powerful Enemies",
	mk_fact_denmark = "Faction Weakness: Disloyal Nobles",
	mk_fact_earldoms = "Faction Weakness: PLACEHOLDER",
	mk_fact_england = "Faction Weakness: Disloyal Nobles",
	mk_fact_epirus = "Faction Weakness: Disloyal Nobles",
	mk_fact_flanders = "Faction Weakness: Few Early Heavy Units",
	mk_fact_france = "Faction Weakness: Many Enemies",
	mk_fact_genoa = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_georgia = "Faction Weakness: Religious Enemies",
	mk_fact_ghurids = "Faction Weakness: Powerful Enemies",
	mk_fact_goldenhorde = "Faction Weakness: Weak Infantry",
	mk_fact_hafsids = "Faction Weakness: Reliance on Commerce",
	mk_fact_hre = "Faction Weakness: Autonomous Tributaries",
	mk_fact_hungary = "Faction Weakness: Lack of Heavy Infantry",
	mk_fact_ildegizids = "Faction Weakness: Weak Diplomacy",
	mk_fact_ilkhanate = "Faction Weakness: Low Fertility",
	mk_fact_ireland = "Faction Weakness: PLACEHOLDER",
	mk_fact_jerusalem = "Faction Weakness: Powerful Enemies",
	mk_fact_khwarazm = "Faction Weakness: Powerful Enemies",
	mk_fact_kiev = "Faction Weakness: Many Enemies",
	mk_fact_latinempire = "Faction Weakness: Many Enemies",
	mk_fact_lesserpoland = "Faction Weakness: Lack of Heavy Infantry",
	mk_fact_lithuania = "Faction Weakness: Lack of Heavy Infantry",
	mk_fact_lorraine = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_makuria = "Faction Weakness: Religious Difficulties",
	mk_fact_marinids = "Faction Weakness: Lack of Heavy Units",
	mk_fact_milan = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_navarre = "Faction Weakness: PLACEHOLDER",
	mk_fact_nicaea = "Faction Weakness: Disloyal Nobles",
	mk_fact_norway = "Faction Weakness: Weak Early Cavalry",
	mk_fact_papacy = "Faction Weakness: PLACEHOLDER",
	mk_fact_pisa = "Faction Weakness: Religious Enemies",
	mk_fact_portugal = "Faction Weakness: Lack of Heavy Infantry",
	mk_fact_schwyz = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_scotland = "Faction Weakness: Few Avenues of Expansion",
	mk_fact_seljuks = "Faction Weakness: Many Enemies",
	mk_fact_serbia = "Faction Weakness: Lack of Heavy Infantry",
	mk_fact_sicily = "Faction Weakness: Weak Diplomacy",
	mk_fact_sweden = "Faction Weakness: Weak Spearmen",
	mk_fact_teutonicorder = "Faction Weakness: Low Public Order",
	mk_fact_toulouse = "Faction Weakness: Powerful Enemies",
	mk_fact_trebizond = "Faction Weakness: Disloyal Nobles",
	mk_fact_trier = "Faction Weakness: Holy Roman Empire Tributary",
	mk_fact_venice = "Faction Weakness: Stretched Thin",
	mk_fact_volga = "Faction Weakness: Lack of Heavy Infantry",
	mk_fact_wallachia = "Faction Weakness: Vassal of Bulgaria",
	mk_fact_zagwe = "Faction Weakness: Few Avenues of Expansion",
	mk_fact_zengids = "Faction Weakness: Surrounded by Great Powers",
	att_fact_visigothi = "Faction Weakness: PLACEHOLDER",
	att_fact_ostrogothi = "Faction Weakness: PLACEHOLDER"
};

FACTION_POPULATIONS = {
	mk_fact_abbasids = "396,000",
	mk_fact_almohads = "1,128,500",
	mk_fact_antioch = "60,900",
	mk_fact_aragon = "71,250",
	mk_fact_armenia = "10,500",
	mk_fact_austria = "25,500",
	mk_fact_ayyubids = "614,500",
	mk_fact_bohemia = "15,000",
	mk_fact_bologna = "52,500",
	mk_fact_bulgaria = "109,500",
	mk_fact_burgundy = "22,500",
	mk_fact_castile = "123,000",
	mk_fact_croatia = "21,000",
	mk_fact_cumans = "103,500",
	mk_fact_denmark = "42,000",
	mk_fact_england = "92,250",
	mk_fact_epirus = "37,500",
	mk_fact_flanders = "30,000",
	mk_fact_france = "261,000",
	mk_fact_genoa = "55,500",
	mk_fact_georgia = "51,250",
	mk_fact_ghurids = "21,000",
	mk_fact_goldenhorde = "N/A (Horde)",
	mk_fact_hafsids = "101,000",
	mk_fact_hre = "41,000",
	mk_fact_hungary = "45,000",
	mk_fact_ildegizids = "21,000",
	mk_fact_ilkhanate = "N/A (Horde)",
	mk_fact_ireland = "13,500",
	mk_fact_jerusalem = "21,000",
	mk_fact_khwarazm = "459,000",
	mk_fact_kiev = "60,000",
	mk_fact_latinempire = "415,500",
	mk_fact_lesserpoland = "15,000",
	mk_fact_lithuania = "30,000",
	mk_fact_lorraine = "1,500",
	mk_fact_makuria = "21,000",
	mk_fact_marinids = "N/A (Horde)",
	mk_fact_milan = "150,000",
	mk_fact_navarre = "12,000",
	mk_fact_nicaea = "80,500",
	mk_fact_norway = "N/A (Horde)",
	mk_fact_papacy = "52,500",
	mk_fact_pisa = "41,000",
	mk_fact_portugal = "51,000",
	mk_fact_schwyz = "4,500",
	mk_fact_scotland = "4,500",
	mk_fact_seljuks = "136,500",
	mk_fact_serbia = "18,000",
	mk_fact_sicily = "72,000",
	mk_fact_sweden = "10,500",
	mk_fact_teutonicorder = "3,000",
	mk_fact_toulouse = "49,500",
	mk_fact_trebizond = "81,000",
	mk_fact_trier = "40,500",
	mk_fact_venice = "125,250",
	mk_fact_volga = "66,750",
	mk_fact_wallachia = "15,000",
	mk_fact_zagwe = "10,500",
	mk_fact_zengids = "21,000",
};

FACTIONS_CAMPAIGN_1 = {
	"mk_fact_abbasids",
	"mk_fact_almohads",
	"mk_fact_antioch",
	"mk_fact_aragon",
	"mk_fact_armenia",
	"mk_fact_austria",
	"mk_fact_ayyubids",
	"mk_fact_bohemia",
	"mk_fact_bulgaria",
	"mk_fact_burgundy",
	"mk_fact_castile",
	"mk_fact_croatia",
	"mk_fact_cumans",
	"mk_fact_denmark",
	"mk_fact_england",
	"mk_fact_epirus",
	"mk_fact_flanders",
	"mk_fact_france",
	"mk_fact_genoa",
	"mk_fact_georgia",
	"mk_fact_ghurids",
	"mk_fact_goldenhorde",
	"mk_fact_hafsids",
	"mk_fact_hre",
	"mk_fact_hungary",
	"mk_fact_ildegizids",
	"mk_fact_ilkhanate",
	"mk_fact_jerusalem",
	"mk_fact_khwarazm",
	"mk_fact_kiev",
	"mk_fact_latinempire",
	"mk_fact_lesserpoland",
	"mk_fact_lithuania",
	"mk_fact_lorraine",
	"mk_fact_makuria",
	"mk_fact_marinids",
	"mk_fact_milan",
	"mk_fact_nicaea",
	"mk_fact_norway",
	"mk_fact_pisa",
	"mk_fact_portugal",
	"mk_fact_schwyz",
	"mk_fact_scotland",
	"mk_fact_seljuks",
	"mk_fact_serbia",
	"mk_fact_sicily",
	"mk_fact_sweden",
	"mk_fact_teutonicorder",
	"mk_fact_toulouse",
	"mk_fact_trebizond",
	"mk_fact_trier",
	"mk_fact_venice",
	"mk_fact_volga",
	"mk_fact_wallachia",
	"mk_fact_zagwe",
	"mk_fact_zengids"
};

FACTIONS_CAMPAIGN_2 = {
	"att_fact_visigothi",
	"att_fact_ostrogothi"
};