----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--
-- 	MEDIEVAL KINGDOMS 1212 - COMMON LISTS
-- 	By: DETrooper
--
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------

REGIONS_TO_PROVINCES_LIST = {
	["att_reg_aegyptus_alexandria"] = "mk_prov_alexandria",
	["att_reg_aegyptus_berenice"] = "mk_prov_berenice",
	["att_reg_aegyptus_oxyrhynchus"] = "mk_prov_oxyrhynchus",
	["att_reg_aethiopia_adulis"] = "mk_prov_adulis",
	["att_reg_aethiopia_aksum"] = "mk_prov_aksum",
	["att_reg_aethiopia_pachoras"] = "mk_prov_pachoras",
	["att_reg_africa_carthago"] = "mk_prov_carthago",
	["att_reg_africa_constantina"] = "mk_prov_constantina",
	["att_reg_africa_hadrumentum"] = "mk_prov_hadrumentum",
	["att_reg_aquitania_avaricum"] = "mk_prov_avaricum",
	["att_reg_aquitania_burdigala"] = "mk_prov_burdigala",
	["att_reg_aquitania_elusa"] = "mk_prov_elusa",
	["att_reg_arabia_felix_eudaemon"] = "mk_prov_eudaemon",
	["att_reg_arabia_felix_omana"] = "mk_prov_omana",
	["att_reg_arabia_felix_zafar"] = "mk_prov_zafar",
	["att_reg_arabia_magna_dumatha"] = "mk_prov_dumatha",
	["att_reg_arabia_magna_hira"] = "mk_prov_hira",
	["att_reg_arabia_magna_yathrib"] = "mk_prov_yathrib",
	["att_reg_armenia_duin"] = "mk_prov_duin",
	["att_reg_armenia_payttakaran"] = "mk_prov_payttakaran",
	["att_reg_armenia_tosp"] = "mk_prov_tosp",
	["att_reg_asia_cyzicus"] = "mk_prov_cyzicus",
	["att_reg_asia_ephesus"] = "mk_prov_ephesus",
	["att_reg_asia_synnada"] = "mk_prov_synnada",
	["att_reg_asorstan_arbela"] = "mk_prov_arbela",
	["att_reg_asorstan_ctesiphon"] = "mk_prov_ctesiphon",
	["att_reg_asorstan_meshan"] = "mk_prov_meshan",
	["att_reg_baetica_corduba"] = "mk_prov_corduba",
	["att_reg_baetica_hispalis"] = "mk_prov_hispalis",
	["att_reg_baetica_malaca"] = "mk_prov_malaca",
	["att_reg_belgica_augusta_treverorum"] = "mk_prov_augusta_treverorum",
	["att_reg_belgica_colonia_agrippina"] = "mk_prov_colonia_agrippina",
	["att_reg_belgica_durocorterum"] = "mk_prov_durocorterum",
	["att_reg_bithynia_amasea"] = "mk_prov_amasea",
	["att_reg_bithynia_ancyra"] = "mk_prov_ancyra",
	["att_reg_bithynia_nicomedia"] = "mk_prov_nicomedia",
	["att_reg_britannia_inferior_eboracum"] = "mk_prov_eboracum",
	["att_reg_britannia_inferior_lindum"] = "mk_prov_lindum",
	["att_reg_britannia_inferior_segontium"] = "mk_prov_segontium",
	["att_reg_britannia_superior_camulodunon"] = "mk_prov_camulodunon",
	["att_reg_britannia_superior_corinium"] = "mk_prov_corinium",
	["att_reg_britannia_superior_londinium"] = "mk_prov_londinium",
	["att_reg_caledonia_et_hibernia_eblana"] = "mk_prov_eblana",
	["att_reg_caledonia_et_hibernia_eildon"] = "mk_prov_eildon",
	["att_reg_caledonia_et_hibernia_tuesis"] = "mk_prov_tuesis",
	["att_reg_cappadocia_caesarea_eusebia"] = "mk_prov_caesarea_eusebia",
	["att_reg_cappadocia_melitene"] = "mk_prov_melitene",
	["att_reg_cappadocia_trapezus"] = "mk_prov_trapezus",
	["att_reg_carthaginensis_carthago_nova"] = "mk_prov_carthago_nova",
	["att_reg_carthaginensis_segobriga"] = "mk_prov_segobriga",
	["att_reg_carthaginensis_toletum"] = "mk_prov_toletum",
	["att_reg_caucasia_gabala"] = "mk_prov_gabala",
	["att_reg_caucasia_kotais"] = "mk_prov_kotais",
	["att_reg_caucasia_mtskheta"] = "mk_prov_mtskheta",
	["att_reg_cilicia_iconium"] = "mk_prov_iconium",
	["att_reg_cilicia_myra"] = "mk_prov_myra",
	["att_reg_cilicia_tarsus"] = "mk_prov_tarsus",
	["att_reg_dacia_apulum"] = "mk_prov_apulum",
	["att_reg_dacia_petrodava"] = "mk_prov_petrodava",
	["att_reg_dacia_romula"] = "mk_prov_romula",
	["att_reg_dalmatia_domavia"] = "mk_prov_domavia",
	["att_reg_dalmatia_salona"] = "mk_prov_salona",
	["att_reg_dalmatia_siscia"] = "mk_prov_siscia",
	["att_reg_dardania_scupi"] = "mk_prov_scupi",
	["att_reg_dardania_serdica"] = "mk_prov_serdica",
	["att_reg_dardania_viminacium"] = "mk_prov_viminacium",
	["att_reg_frisia_angulus"] = "mk_prov_angulus",
	["att_reg_frisia_flevum"] = "mk_prov_flevum",
	["att_reg_frisia_tulifurdum"] = "mk_prov_tulifurdum",
	["att_reg_gallaecia_asturica"] = "mk_prov_asturica",
	["att_reg_gallaecia_bracara"] = "mk_prov_bracara",
	["att_reg_gallaecia_brigantium"] = "mk_prov_brigantium",
	["att_reg_germania_aregelia"] = "mk_prov_aregelia",
	["att_reg_germania_lupfurdum"] = "mk_prov_lupfurdum",
	["att_reg_germania_uburzis"] = "mk_prov_uburzis",
	["att_reg_germano_sarmatia_duna"] = "mk_prov_duna",
	["att_reg_germano_sarmatia_oium"] = "mk_prov_oium",
	["att_reg_germano_sarmatia_palteskja"] = "mk_prov_palteskja",
	["att_reg_gothiscandza_ascaucalis"] = "mk_prov_ascaucalis",
	["att_reg_gothiscandza_gothiscandza"] = "mk_prov_gothiscandza",
	["att_reg_gothiscandza_rugion"] = "mk_prov_rugion",
	["att_reg_hercynia_budorgis"] = "mk_prov_budorgis",
	["att_reg_hercynia_casurgis"] = "mk_prov_casurgis",
	["att_reg_hercynia_nitrahwa"] = "mk_prov_nitrahwa",
	["att_reg_hyperborea_kariskos"] = "mk_prov_kariskos",
	["att_reg_hyperborea_moramar"] = "mk_prov_moramar",
	["att_reg_hyperborea_sylis"] = "mk_prov_sylis",
	["att_reg_italia_fiorentia"] = "mk_prov_fiorentia",
	["att_reg_italia_neapolis"] = "mk_prov_neapolis",
	["att_reg_italia_roma"] = "mk_prov_roma",
	["att_reg_khwarasan_abarshahr"] = "mk_prov_abarshahr",
	["att_reg_khwarasan_harey"] = "mk_prov_harey",
	["att_reg_khwarasan_merv"] = "mk_prov_merv",
	["att_reg_libya_augila"] = "mk_prov_augila",
	["att_reg_libya_paraetonium"] = "mk_prov_paraetonium",
	["att_reg_libya_ptolemais"] = "mk_prov_ptolemais",
	["att_reg_liguria_genua"] = "mk_prov_genua",
	["att_reg_liguria_mediolanum"] = "mk_prov_mediolanum",
	["att_reg_liguria_segusio"] = "mk_prov_segusio",
	["att_reg_lugdunensis_lugdunum"] = "mk_prov_lugdunum",
	["att_reg_lugdunensis_rotomagus"] = "mk_prov_rotomagus",
	["att_reg_lugdunensis_turonum"] = "mk_prov_turonum",
	["att_reg_lusitania_emerita_augusta"] = "mk_prov_emerita_augusta",
	["att_reg_lusitania_olisipo"] = "mk_prov_olisipo",
	["att_reg_lusitania_pax_augusta"] = "mk_prov_pax_augusta",
	["att_reg_macedonia_corinthus"] = "mk_prov_corinthus",
	["att_reg_macedonia_dyrrhachium"] = "mk_prov_dyrrhachium",
	["att_reg_macedonia_thessalonica"] = "mk_prov_thessalonica",
	["att_reg_magna_graecia_rhegium"] = "mk_prov_rhegium",
	["att_reg_magna_graecia_syracusae"] = "mk_prov_syracusae",
	["att_reg_magna_graecia_tarentum"] = "mk_prov_tarentum",
	["att_reg_makran_harmosia"] = "mk_prov_harmosia",
	["att_reg_makran_phra"] = "mk_prov_phra",
	["att_reg_makran_pura"] = "mk_prov_pura",
	["att_reg_mauretania_caesarea"] = "mk_prov_caesarea",
	["att_reg_mauretania_tamousiga"] = "mk_prov_tamousiga",
	["att_reg_mauretania_tingis"] = "mk_prov_tingis",
	["att_reg_maxima_sequanorum_argentoratum"] = "mk_prov_argentoratum",
	["att_reg_maxima_sequanorum_octodurus"] = "mk_prov_octodurus",
	["att_reg_maxima_sequanorum_vesontio"] = "mk_prov_vesontio",
	["att_reg_media_atropatene_ecbatana"] = "mk_prov_ecbatana",
	["att_reg_media_atropatene_ganzaga"] = "mk_prov_ganzaga",
	["att_reg_media_atropatene_rhaga"] = "mk_prov_rhaga",
	["att_reg_mediterraneus_occidentalis_ajax"] = "mk_prov_ajax",
	["att_reg_mediterraneus_occidentalis_caralis"] = "mk_prov_caralis",
	["att_reg_mediterraneus_occidentalis_palma"] = "mk_prov_palma",
	["att_reg_mediterraneus_orientalis_constantia"] = "mk_prov_constantia",
	["att_reg_mediterraneus_orientalis_gortyna"] = "mk_prov_gortyna",
	["att_reg_mediterraneus_orientalis_rhodes"] = "mk_prov_rhodes",
	["att_reg_narbonensis_aquae_sextiae"] = "mk_prov_aquae_sextiae",
	["att_reg_narbonensis_narbo"] = "mk_prov_narbo",
	["att_reg_narbonensis_vienna"] = "mk_prov_vienna",
	["att_reg_osroene_amida"] = "mk_prov_amida",
	["att_reg_osroene_edessa"] = "mk_prov_edessa",
	["att_reg_osroene_nisibis"] = "mk_prov_nisibis",
	["att_reg_palaestinea_aelia_capitolina"] = "mk_prov_aelia_capitolina",
	["att_reg_palaestinea_aila"] = "mk_prov_aila",
	["att_reg_palaestinea_nova_trajana_bostra"] = "mk_prov_nova_trajana_bostra",
	["att_reg_pannonia_savaria"] = "mk_prov_savaria",
	["att_reg_pannonia_sirmium"] = "mk_prov_sirmium",
	["att_reg_pannonia_sopianae"] = "mk_prov_sopianae",
	["att_reg_persis_behdeshir"] = "mk_prov_behdeshir",
	["att_reg_persis_siraf"] = "mk_prov_siraf",
	["att_reg_persis_stakhr"] = "mk_prov_stakhr",
	["att_reg_phazania_cydamus"] = "mk_prov_cydamus",
	["att_reg_phazania_dimmidi"] = "mk_prov_dimmidi",
	["att_reg_phazania_garama"] = "mk_prov_garama",
	["att_reg_raetia_et_noricum_augusta_vindelicorum"] = "mk_prov_augusta_vindelicorum",
	["att_reg_raetia_et_noricum_iuvavum"] = "mk_prov_iuvavum",
	["att_reg_raetia_et_noricum_virunum"] = "mk_prov_virunum",
	["att_reg_sarmatia_asiatica_anacopia"] = "mk_prov_anacopia",
	["att_reg_sarmatia_asiatica_samandar"] = "mk_prov_samandar",
	["att_reg_sarmatia_asiatica_tanais"] = "mk_prov_tanais",
	["att_reg_sarmatia_europaea_chersonessus"] = "mk_prov_chersonessus",
	["att_reg_sarmatia_europaea_gelonus"] = "mk_prov_gelonus",
	["att_reg_sarmatia_europaea_olbia"] = "mk_prov_olbia",
	["att_reg_scandza_alabu"] = "mk_prov_alabu",
	["att_reg_scandza_hafn"] = "mk_prov_hafn",
	["att_reg_scandza_hrefnesholt"] = "mk_prov_hrefnesholt",
	["att_reg_scythia_bolghar"] = "mk_prov_bolghar",
	["att_reg_scythia_ra"] = "mk_prov_ra",
	["att_reg_scythia_sarai"] = "mk_prov_sarai",
	["att_reg_spahan_issatis"] = "mk_prov_issatis",
	["att_reg_spahan_spahan"] = "mk_prov_spahan",
	["att_reg_spahan_susa"] = "mk_prov_susa",
	["att_reg_syria_antiochia"] = "mk_prov_antiochia",
	["att_reg_syria_emesa"] = "mk_prov_emesa",
	["att_reg_syria_tyrus"] = "mk_prov_tyrus",
	["att_reg_tarraconensis_caesaraugusta"] = "mk_prov_caesaraugusta",
	["att_reg_tarraconensis_pompaelo"] = "mk_prov_pompaelo",
	["att_reg_tarraconensis_tarraco"] = "mk_prov_tarraco",
	["att_reg_thracia_constantinopolis"] = "mk_prov_constantinopolis",
	["att_reg_thracia_marcianopolis"] = "mk_prov_marcianopolis",
	["att_reg_thracia_trimontium"] = "mk_prov_trimontium",
	["att_reg_transcarpathia_arheimar"] = "mk_prov_arheimar",
	["att_reg_transcarpathia_belz"] = "mk_prov_belz",
	["att_reg_transcarpathia_leopolis"] = "mk_prov_leopolis",
	["att_reg_transcaspia_dahistan"] = "mk_prov_dahistan",
	["att_reg_transcaspia_kath"] = "mk_prov_kath",
	["att_reg_transcaspia_siahkuh"] = "mk_prov_siahkuh",
	["att_reg_tripolitana_leptis_magna"] = "mk_prov_leptis_magna",
	["att_reg_tripolitana_macomades"] = "mk_prov_macomades",
	["att_reg_tripolitana_sabrata"] = "mk_prov_sabrata",
	["att_reg_venetia_aquileia"] = "mk_prov_aquileia",
	["att_reg_venetia_ravenna"] = "mk_prov_ravenna",
	["att_reg_venetia_verona"] = "mk_prov_verona",
};

SEPARATIST_FACTION_REBELLION_UNITS = {
	["mk_fact_separatists_abbasid"] = {
		"mk_abb_t1_awam_rumat",
		"mk_abb_t1_ayyar",
		"mk_abb_t1_bedouin_lancers",
		"mk_abb_t1_dariyyah_ghulam_horse_archers",
		"mk_abb_t1_dismounted_ghulam",
		"mk_abb_t1_fursan_akrad",
		"mk_abb_t1_fursan_iqtaiyyah",
		"mk_abb_t1_futuwwa",
		"mk_abb_t1_futuwwa_jund",
		"mk_abb_t1_jund_crossbowmen",
		"mk_abb_t1_jund_rajilah",
		"mk_abb_t1_jund_rumat",
		"mk_abb_t1_mounted_crossbowmen",
		"mk_abb_t1_naffatun",
		"mk_abb_t1_turcoman_jarida",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_alania"] = {
		"mk_cuman_t1_heavy_HA",
		"mk_cuman_t1_heavy_lancers",
		"mk_cuman_t1_infantry",
		"mk_cuman_t1_light_HA",
		"mk_cuman_t1_light_archers",
		"mk_cuman_t1_light_lancers",
		"mk_cuman_t1_macemen",
		"mk_cuman_t1_medium_archers",
		"mk_cuman_t1_nogers",
		"mk_cuman_t1_skirmisher_cavalry",
		"mk_cuman_t1_skirmishers",
		"mk_cuman_t1_spearmen",
		"mk_cuman_t1_subject_cavalry",
		"mk_cuman_t1_tribal_HA",
		"mk_cuman_t1_uzdens",
		"mk_mon_t1_catapult",
	},
	["mk_fact_separatists_almohads"] = {
		"mk_alm_t1_abid_al_makhzan",
		"mk_alm_t1_abid_infantry",
		"mk_alm_t1_abid_skirmishers",
		"mk_alm_t1_arab_cavalry",
		"mk_alm_t1_berber_horsemen",
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_huffaz",
		"mk_alm_t1_hushud",
		"mk_alm_t1_hushud_rumat",
		"mk_alm_t1_jund_swordsmen",
		"mk_alm_t1_maghrebi_rumat",
		"mk_alm_t1_maghrebi_tribesmen",
		"mk_alm_t1_mounted_abid_al_makhzan",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_nobat_al_djandariya",
		"mk_alm_t1_slinger",
		"mk_mar_t1_humah_watanihi",
		"mk_mar_t1_zenata_skirmish_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_andalusian"] = {
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_ghuzz_horse_archers",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_slinger",
		"mk_gran_t1_andalusian_crossbowmen",
		"mk_gran_t1_andalusian_jund",
		"mk_gran_t1_andalusian_mounted_crossbowmen",
		"mk_gran_t1_asnaf_al_berber",
		"mk_gran_t1_granadine_knights",
		"mk_gran_t1_granadine_rais",
		"mk_gran_t1_granadine_spear_cavalry",
		"mk_gran_t1_heavy_andalusian_crossbowmen",
		"mk_gran_t1_hushud_rumat",
		"mk_gran_t1_jund_al_nasara",
		"mk_gran_t1_jundi_mutadawwan",
		"mk_gran_t1_maghrebi_tribesmen",
		"mk_gran_t1_mozarab_jund",
		"mk_gran_t1_muwalladun_cavalry",
		"mk_gran_t1_muwalladun_jund",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_antioch"] = {
		"mk_ant_t1_crossbowmen",
		"mk_ant_t1_knights",
		"mk_ant_t1_sergeants_mounted",
		"mk_ant_t1_spearmen",
		"mk_ant_t1_syriac_archers",
		"mk_eur_t1_catapult",
		"mk_mio_t1_hospitaller_knights",
		"mk_mio_t1_hospitaller_mounted_sergeants",
		"mk_mio_t1_hospitaller_sergeant_spearmen",
		"mk_mio_t1_templar_knights",
		"mk_mio_t1_templar_mounted_sergeants",
		"mk_mio_t1_templar_sergeant_spearmen",
	},
	["mk_fact_separatists_aragon"] = {
		"mk_ara_t1_almogavars",
		"mk_ara_t1_caballeros",
		"mk_ara_t1_caballeros_villanos",
		"mk_ara_t1_fidalgos",
		"mk_ara_t1_jinetes",
		"mk_ara_t1_militia_crossbowmen",
		"mk_ara_t1_militia_spearmen",
		"mk_ara_t1_mounted_crossbowmen",
		"mk_ara_t1_peones",
		"mk_ara_t1_peones_crossbowmen",
		"mk_ara_t1_peones_spearmen",
		"mk_ara_t1_pikemen",
		"mk_ara_t1_sergeant_crossbowmen",
		"mk_ara_t1_slingers",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_armenia"] = {
		"mk_arm_t1_archer_dziaworner",
		"mk_arm_t1_archer_serzhantner",
		"mk_arm_t1_aspatakner",
		"mk_arm_t1_aspetner",
		"mk_arm_t1_bardzraharker",
		"mk_arm_t1_bardzravandak_skirmishers",
		"mk_arm_t1_bourdjes_archers",
		"mk_arm_t1_bourdjes_militia",
		"mk_arm_t1_cilician_levies",
		"mk_arm_t1_dziaworner",
		"mk_arm_t1_foot_serzhantner",
		"mk_arm_t1_serzhantner",
		"mk_arm_t1_spear_serzhantner",
		"mk_arm_t1_turcopoles",
		"mk_byz_t1_catapult",
	},
	["mk_fact_separatists_austria"] = {
		"mk_aus_t1_armbrustschutzen_crossbow",
		"mk_aus_t1_bogner_archer",
		"mk_aus_t1_burgerwehr_spearmen",
		"mk_aus_t1_fussknecht_spearmen",
		"mk_aus_t1_fussknechte_halberdiers",
		"mk_aus_t1_konstafler",
		"mk_aus_t1_landsturm_crossbowmen",
		"mk_aus_t1_landsturm_spearmen",
		"mk_aus_t1_mounted_crossbowmen",
		"mk_aus_t1_mounted_sarianten",
		"mk_aus_t1_ritter",
		"mk_aus_t1_schutzen_crossbowmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_ayyubids"] = {
		"mk_ayy_t1_ahdath",
		"mk_ayy_t1_ahdath_archers",
		"mk_ayy_t1_ajnad_cavalry",
		"mk_ayy_t1_askari_cavalry",
		"mk_ayy_t1_askari_nobles",
		"mk_ayy_t1_beduin_camel_riders",
		"mk_ayy_t1_crossbowmen",
		"mk_ayy_t1_harafisha_infantry",
		"mk_ayy_t1_jaridah_cav",
		"mk_ayy_t1_jund_spearmen",
		"mk_ayy_t1_jund_swordsmen",
		"mk_ayy_t1_naffatun",
		"mk_ayy_t1_nubian_spearmen",
		"mk_ayy_t1_shujan",
		"mk_ayy_t1_sudanese_archers",
		"mk_ayy_t1_tawashi",
		"mk_ayy_t1_thaqlah_axemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_bohemia"] = {
		"mk_boh_t1_chod_frontiersmen",
		"mk_boh_t1_crossbowmen",
		"mk_boh_t1_king_bodyguard",
		"mk_boh_t1_knights",
		"mk_boh_t1_militia_archers",
		"mk_boh_t1_mounted_raiders",
		"mk_boh_t1_mounted_sergeants",
		"mk_boh_t1_pacholek_spearmen",
		"mk_boh_t1_peasant_archers",
		"mk_boh_t1_sergeant_spearmen",
		"mk_boh_t1_sergeants",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_bologna"] = {
		"mk_eur_t1_catapult",
		"mk_mil_t1_archer_militia",
		"mk_mil_t1_archers",
		"mk_mil_t1_berrovieri",
		"mk_mil_t1_crossbowmen",
		"mk_mil_t1_foot_berrovieri",
		"mk_mil_t1_knights",
		"mk_mil_t1_light_cav",
		"mk_mil_t1_militia_crossbowmen",
		"mk_mil_t1_militia_spearmen",
		"mk_mil_t1_militia_swordsmen",
		"mk_mil_t1_mounted_crossbowmen",
		"mk_mil_t1_mounted_serjeants",
		"mk_mil_t1_spearmen",
		"mk_mil_t1_swordsmen",
	},
	["mk_fact_separatists_brabant"] = {
		"mk_brab_t1_crossbowmen",
		"mk_brab_t1_dismounted_knights",
		"mk_brab_t1_goedendag_militia",
		"mk_brab_t1_guisarmiers",
		"mk_brab_t1_knights",
		"mk_brab_t1_levy_archer",
		"mk_brab_t1_militia_spearmen",
		"mk_brab_t1_militia_swordsmen",
		"mk_brab_t1_mounted_crossbowmen",
		"mk_brab_t1_mounted_sergeants",
		"mk_brab_t1_pikemen",
		"mk_brab_t1_sergeants",
		"mk_brab_t1_spearmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_britons"] = {
		"mk_wel_t1_dismounted_uchelwyr",
		"mk_wel_t1_hobilar",
		"mk_wel_t1_rhyfelwyr",
		"mk_wel_t1_saethwyr",
		"mk_wel_t1_schiltron_spearmen",
		"mk_wel_t1_spear_band",
		"mk_wel_t1_spearmen",
		"mk_wel_t1_teulu_saethwyr",
		"mk_wel_t1_uchelwyr",
		"mk_wel_t1_ysbeilwyr",
	},
	["mk_fact_separatists_bulgaria"] = {
		"mk_bulg_t1_archers",
		"mk_bulg_t1_axemen_dogs",
		"mk_bulg_t1_bolyars",
		"mk_bulg_t1_cavalry",
		"mk_bulg_t1_heavy_cavalry",
		"mk_bulg_t1_heavy_spearmen",
		"mk_bulg_t1_hooked_pikemen",
		"mk_bulg_t1_levy_spearmen",
		"mk_bulg_t1_militia_archers",
		"mk_bulg_t1_militia_spearmen",
		"mk_bulg_t1_slav_aux_javelinmen",
		"mk_bulg_t1_voivods",
		"mk_byz_t1_catapult",
	},
	["mk_fact_separatists_burgundy"] = {
		"mk_bur_t1_axe_sergeants",
		"mk_bur_t1_chevaliers",
		"mk_bur_t1_crossbowmen",
		"mk_bur_t1_dismounted_chevaliers",
		"mk_bur_t1_guisarmiers",
		"mk_bur_t1_levy_archers",
		"mk_bur_t1_levy_crossbowmen",
		"mk_bur_t1_levy_guisarmiers",
		"mk_bur_t1_mounted_crossbowmen",
		"mk_bur_t1_mounted_serjeants",
		"mk_bur_t1_scouts",
		"mk_bur_t1_sergeants",
		"mk_bur_t1_spear_militia",
		"mk_bur_t1_spearmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_castile"] = {
		"mk_cas_t1_almogavar_scouts",
		"mk_cas_t1_almogavars",
		"mk_cas_t1_caballeros",
		"mk_cas_t1_crossbow_militia",
		"mk_cas_t1_crossbowmen",
		"mk_cas_t1_hidalgos",
		"mk_cas_t1_jinetes",
		"mk_cas_t1_mounted_crossbowmen",
		"mk_cas_t1_peones",
		"mk_cas_t1_peones_crossbowmen",
		"mk_cas_t1_peones_spearmen",
		"mk_cas_t1_slingers",
		"mk_cas_t1_spear_militia",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_croatia"] = {
		"mk_croat_T1_archers",
		"mk_croat_T1_cavalry",
		"mk_croat_T1_communal_militia",
		"mk_croat_T1_communal_noble_infantry",
		"mk_croat_T1_crossbowmen",
		"mk_croat_T1_javelin_sailors",
		"mk_croat_T1_knight",
		"mk_croat_T1_militia_crossbowmen",
		"mk_croat_T1_spearmen",
		"mk_croat_T1_swordsmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_cumans"] = {
		"mk_cuman_t1_heavy_HA",
		"mk_cuman_t1_heavy_lancers",
		"mk_cuman_t1_infantry",
		"mk_cuman_t1_light_HA",
		"mk_cuman_t1_light_archers",
		"mk_cuman_t1_light_lancers",
		"mk_cuman_t1_macemen",
		"mk_cuman_t1_medium_archers",
		"mk_cuman_t1_nogers",
		"mk_cuman_t1_skirmisher_cavalry",
		"mk_cuman_t1_skirmishers",
		"mk_cuman_t1_spearmen",
		"mk_cuman_t1_subject_cavalry",
		"mk_cuman_t1_tribal_HA",
		"mk_cuman_t1_uzdens",
		"mk_mon_t1_catapult",
	},
	["mk_fact_separatists_denmark"] = {
		"mk_dan_t1_axe_bondir",
		"mk_dan_t1_bondir_spear",
		"mk_dan_t1_bow_bondir",
		"mk_dan_t1_crossbowmen",
		"mk_dan_t1_huskarls",
		"mk_dan_t1_huskarls_spear",
		"mk_dan_t1_knights",
		"mk_dan_t1_landevaern_infantry",
		"mk_dan_t1_landevaern_spearmen",
		"mk_dan_t1_longbowmen",
		"mk_dan_t1_scouts",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_epirus"] = {
		 "mk_byz_t1_catapult",
		 "mk_epirus_t1_epirus_epirote_guard",
		 "mk_epirus_t1_heavy_archers",
		 "mk_epirus_t1_kavallarioi",
		 "mk_epirus_t1_militia_spearmen",
		 "mk_epirus_t1_scoutatoi",
		 "mk_epirus_t1_scouts",
		 "mk_epirus_t1_skirmishers",
		 "mk_epirus_t1_swordsmen",
	},
	["mk_fact_separatists_flanders"] = {
		"mk_fla_t1_crossbowmen",
		"mk_fla_t1_falchion_swordsmen",
		"mk_fla_t1_goedendags",
		"mk_fla_t1_knights",
		"mk_fla_t1_maa",
		"mk_fla_t1_mounted_sergeants",
		"mk_fla_t1_pikemen",
		"mk_fla_t1_sergeants",
		"mk_fla_t1_spearmen",
		"mk_fla_t1_swordsmen",
	},
	["mk_fact_separatists_france"] = {
		"mk_eur_t1_catapult",
		"mk_fre_t1_arbaletriers",
		"mk_fre_t1_arbaletriers_mounted",
		"mk_fre_t1_archers",
		"mk_fre_t1_chevaliers_mounted",
		"mk_fre_t1_cliens",
		"mk_fre_t1_guisarmiers",
		"mk_fre_t1_levy_crossbowmen",
		"mk_fre_t1_levy_spearmen",
		"mk_fre_t1_mounted_sergeants",
		"mk_fre_t1_piquichins",
		"mk_fre_t1_ribauds",
		"mk_fre_t1_sergeant_axemen",
		"mk_fre_t1_sergeants",
	},
	["mk_fact_separatists_frankish"] = {
		"mk_eur_t1_catapult",
		"mk_lat_t1_bow_militia",
		"mk_lat_t1_chevaliers",
		"mk_lat_t1_crossbow_militia",
		"mk_lat_t1_crossbowmen",
		"mk_lat_t1_mounted_crossbowmen",
		"mk_lat_t1_mounted_sergeants",
		"mk_lat_t1_pikemen",
		"mk_lat_t1_sergeants",
		"mk_lat_t1_spear_militia",
	},
	["mk_fact_separatists_french"] = {
		"mk_eur_t1_catapult",
		"mk_fre_t1_arbaletriers",
		"mk_fre_t1_arbaletriers_mounted",
		"mk_fre_t1_archers",
		"mk_fre_t1_chevaliers_mounted",
		"mk_fre_t1_cliens",
		"mk_fre_t1_guisarmiers",
		"mk_fre_t1_levy_crossbowmen",
		"mk_fre_t1_levy_spearmen",
		"mk_fre_t1_mounted_sergeants",
		"mk_fre_t1_piquichins",
		"mk_fre_t1_ribauds",
		"mk_fre_t1_sergeant_axemen",
		"mk_fre_t1_sergeants",
	},
	["mk_fact_separatists_genoa"] = {
		"mk_eur_t1_catapult",
		"mk_gen_t1_archers",
		"mk_gen_t1_berrovieri",
		"mk_gen_t1_crossbowmen",
		"mk_gen_t1_foot_berrovieri",
		"mk_gen_t1_guelph_maa",
		"mk_gen_t1_guelph_mounted_maa",
		"mk_gen_t1_knights",
		"mk_gen_t1_light_cav",
		"mk_gen_t1_militia_archer",
		"mk_gen_t1_militia_crossbowmen",
		"mk_gen_t1_militia_spearmen",
		"mk_gen_t1_militia_swordmen",
		"mk_gen_t1_mounted_crossbowmen",
		"mk_gen_t1_spearmen",
		"mk_gen_t1_swordmen",
	},
	["mk_fact_separatists_georgia"] = {
		"mk_byz_t1_catapult",
		"mk_georg_t1_aznauri_lancers",
		"mk_georg_t1_aznauri_swordsmen",
		"mk_georg_t1_dismounted_monaspa_archers",
		"mk_georg_t1_kartlian_spearmen",
		"mk_georg_t1_khevsur_swordsmen",
		"mk_georg_t1_metsikhovne_archers",
		"mk_georg_t1_metsikhovne_spearmen",
		"mk_georg_t1_monaspa_lancers",
		"mk_georg_t1_msakhureuli_cavalry",
		"mk_georg_t1_shubosani_molashqre",
		"mk_georg_t1_svanian_crossbowmen",
		"mk_georg_t1_svanian_hunters",
		"mk_georg_t1_svanian_spearmen",
	},
	["mk_fact_separatists_german"] = {
		"mk_eur_t1_catapult",
		"mk_ger_t1_archers",
		"mk_ger_t1_axe_sergeants",
		"mk_ger_t1_emperor_bodyguard",
		"mk_ger_t1_knights",
		"mk_ger_t1_militia_crossbowmen",
		"mk_ger_t1_mounted_crossbowmen",
		"mk_ger_t1_mounted_sergeants",
		"mk_ger_t1_pikemen",
		"mk_ger_t1_sergeant_crossbowmen",
		"mk_ger_t1_sergeant_spearmen",
		"mk_ger_t1_sergeants",
		"mk_ger_t1_urban_militia_axe",
	},
	["mk_fact_separatists_ghurid"] = {
		"mk_ghu_t1_afghan_archers",
		"mk_ghu_t1_afghan_spearmen",
		"mk_ghu_t1_ghori_infantry",
		"mk_ghu_t1_ghori_maliks",
		"mk_ghu_t1_ghori_tribesmen",
		"mk_ghu_t1_ghulam_lancers",
		"mk_ghu_t1_ghulaman",
		"mk_ghu_t1_ghuzz_mercenaries",
		"mk_ghu_t1_indian_elephants",
		"mk_ghu_t1_khalaj_cavalry",
		"mk_ghu_t1_naphta_throwers",
		"mk_ghu_t1_nawak_infantry",
		"mk_ghu_t1_sawar-i_barahna_wa-jarida",
		"mk_ghu_t1_tajik_levy",
		"mk_ghu_t1_zupin_javelinmen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_goldenhorde"] = {
		"mk_mon_t1_catapult",
		"mk_mon_t1_fire_lance_infantry",
		"mk_mon_t1_golden_hashar_levy",
		"mk_mon_t1_golden_heavy_horse_archers",
		"mk_mon_t1_golden_heavy_lancers",
		"mk_mon_t1_golden_horse_archers",
		"mk_mon_t1_golden_kharash",
		"mk_mon_t1_golden_lancers",
		"mk_mon_t1_golden_rus_archers",
		"mk_mon_t1_golden_tserig_spearmen",
		"mk_mon_t1_golden_turk_heavy_horse_archers",
		"mk_mon_t1_ilkhan_turkic_archers",
	},
	["mk_fact_separatists_hafsids"] = {
		"mk_alm_t1_abid_al_makhzan",
		"mk_alm_t1_abid_infantry",
		"mk_alm_t1_abid_skirmishers",
		"mk_alm_t1_berber_horsemen",
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_hushud",
		"mk_alm_t1_hushud_rumat",
		"mk_alm_t1_jund_al_nasara",
		"mk_alm_t1_jund_swordsmen",
		"mk_alm_t1_maghrebi_rumat",
		"mk_alm_t1_maghrebi_tribesmen",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_slinger",
		"mk_haf_t1_ifriqyan_cavalry",
		"mk_haf_t1_irban",
		"mk_haf_t1_kabyle_tribal_horsemen",
		"mk_haf_t1_mashshain",
		"mk_mar_t1_mizwar_noble_horsemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_hre"] = {
		"mk_eur_t1_catapult",
		"mk_ger_t1_archers",
		"mk_ger_t1_axe_sergeants",
		"mk_ger_t1_emperor_bodyguard",
		"mk_ger_t1_knights",
		"mk_ger_t1_militia_crossbowmen",
		"mk_ger_t1_mounted_crossbowmen",
		"mk_ger_t1_mounted_sergeants",
		"mk_ger_t1_pikemen",
		"mk_ger_t1_sergeant_crossbowmen",
		"mk_ger_t1_sergeant_spearmen",
		"mk_ger_t1_sergeants",
		"mk_ger_t1_urban_militia_axe",
	},
	["mk_fact_separatists_hungary"] = {
		"mk_eur_t1_catapult",
		"mk_hun_t1_HA",
		"mk_hun_t1_crossbowmen",
		"mk_hun_t1_knight",
		"mk_hun_t1_light_lancer",
		"mk_hun_t1_militia_crossbowmen",
		"mk_hun_t1_militia_spear",
		"mk_hun_t1_royal_warriors",
		"mk_hun_t1_spearmen",
		"mk_hun_t1_sword",
		"mk_hun_t1_szekely_HA",
	},
	["mk_fact_separatists_iberian"] = {
		"mk_cas_t1_almogavar_scouts",
		"mk_cas_t1_almogavars",
		"mk_cas_t1_caballeros",
		"mk_cas_t1_crossbow_militia",
		"mk_cas_t1_crossbowmen",
		"mk_cas_t1_hidalgos",
		"mk_cas_t1_jinetes",
		"mk_cas_t1_mounted_crossbowmen",
		"mk_cas_t1_peones",
		"mk_cas_t1_peones_crossbowmen",
		"mk_cas_t1_peones_spearmen",
		"mk_cas_t1_slingers",
		"mk_cas_t1_spear_militia",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_ildegizids"] = {
		"mk_ata_t1_askari",
		"mk_ata_t1_ghazi_cavalry",
		"mk_ata_t1_tribesmen",
		"mk_aze_t1_azerbaijani_infantry",
		"mk_aze_t1_azerbaijani_savaran",
		"mk_aze_t1_highland_slingers",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_ilkhanate"] = {
		"mk_mon_t1_catapult",
		"mk_mon_t1_fire_lance_infantry",
		"mk_mon_t1_ilkhan_heavy_horse_archers",
		"mk_mon_t1_ilkhan_heavy_lancers",
		"mk_mon_t1_ilkhan_horse_archers",
		"mk_mon_t1_ilkhan_kharash",
		"mk_mon_t1_ilkhan_lancers",
		"mk_mon_t1_ilkhan_qaraghul",
		"mk_mon_t1_ilkhan_turkic_archers",
		"mk_mon_t1_tammas",
	},
	["mk_fact_separatists_iran"] = {
		"mk_ghu_t1_indian_elephants",
		"mk_khw_t1_askari",
		"mk_khw_t1_camel_cavalry",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_khwarazmian_cavalry",
		"mk_khw_t1_khwarazmian_lancers",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_savaran",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_ireland"] = {
		"mk_eur_t1_catapult",
		"mk_sco_t1_ettrick_archers",
		"mk_sco_t1_highlanders",
		"mk_sco_t1_hobilars",
		"mk_sco_t1_knights",
		"mk_sco_t1_longbow_militia",
		"mk_sco_t1_pikemen",
		"mk_sco_t1_sergeants",
	},
	["mk_fact_separatists_jerusalem"] = {
		"mk_eur_t1_catapult",
		"mk_jer_t1_maronite_skirmishers",
		"mk_jer_t1_maronite_spearmen",
		"mk_jer_t1_poulain_crossbowmen",
		"mk_jer_t1_poulain_knights",
		"mk_jer_t1_poulain_knights_dismounted",
		"mk_jer_t1_syriac_crossbowmen",
		"mk_jer_t1_turcopoles",
		"mk_mio_t1_hospitaller_knights",
		"mk_mio_t1_hospitaller_mounted_sergeants",
		"mk_mio_t1_hospitaller_sergeant_spearmen",
		"mk_mio_t1_templar_knights",
		"mk_mio_t1_templar_mounted_sergeants",
		"mk_mio_t1_templar_sergeant_spearmen",
	},
	["mk_fact_separatists_khwarazm"] = {
		"mk_ghu_t1_indian_elephants",
		"mk_khw_t1_askari",
		"mk_khw_t1_camel_cavalry",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_khwarazmian_cavalry",
		"mk_khw_t1_khwarazmian_lancers",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_savaran",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_kiev"] = {
		"mk_rus_t1_catapult",
		"mk_rus_t1_dismounted_druzina",
		"mk_rus_t1_druzina",
		"mk_rus_t1_guard_axemen",
		"mk_rus_t1_javelinmen",
		"mk_rus_t1_militia_archers",
		"mk_rus_t1_militia_heavy_spearmen",
		"mk_rus_t1_militia_infantry",
		"mk_rus_t1_militia_spearmen",
		"mk_rus_t1_senior_druzina",
		"mk_rus_t1_spearmen",
		"mk_rus_t1_swordsmen",
	},
	["mk_fact_separatists_latinempire"] = {
		"mk_eur_t1_catapult",
		"mk_lat_t1_bow_militia",
		"mk_lat_t1_chevaliers",
		"mk_lat_t1_crossbow_militia",
		"mk_lat_t1_crossbowmen",
		"mk_lat_t1_mounted_crossbowmen",
		"mk_lat_t1_mounted_sergeants",
		"mk_lat_t1_pikemen",
		"mk_lat_t1_sergeants",
		"mk_lat_t1_spear_militia",
	},
	["mk_fact_separatists_lesserpoland"] = {
		"mk_eur_t1_catapult",
		"mk_pol_t1_archers_lesser_poland",
		"mk_pol_t1_axemen_lesser_poland",
		"mk_pol_t1_knight_lesser_poland",
		"mk_pol_t1_militia_crossbowmen",
		"mk_pol_t1_militia_spearmen",
		"mk_pol_t1_mounted_crossbowmen",
		"mk_pol_t1_mounted_sergeants",
		"mk_pol_t1_sergeant_crossbowmen_lesser_poland",
		"mk_pol_t1_sergeant_spearmen",
		"mk_pol_t1_sergeants",
	},
	["mk_fact_separatists_lithuania"] = {
		"mk_lit_t1_axemen",
		"mk_lit_t1_boyars",
		"mk_lit_t1_ducal_axemen",
		"mk_lit_t1_ducal_spearmen",
		"mk_lit_t1_lithuanian_skirmishers",
		"mk_lit_t1_militia_crossbowmen",
		"mk_lit_t1_militia_spearmen",
		"mk_lit_t1_noble_cavalry",
		"mk_lit_t1_noble_swordsmen",
		"mk_lit_t1_ruthenian_archers",
		"mk_lit_t1_skirmisher_cavalry",
		"mk_rus_t1_catapult",
	},
	["mk_fact_separatists_lombards"] = {
		"mk_eur_t1_catapult",
		"mk_mil_t1_archer_militia",
		"mk_mil_t1_archers",
		"mk_mil_t1_berrovieri",
		"mk_mil_t1_crossbowmen",
		"mk_mil_t1_foot_berrovieri",
		"mk_mil_t1_knights",
		"mk_mil_t1_light_cav",
		"mk_mil_t1_militia_crossbowmen",
		"mk_mil_t1_militia_spearmen",
		"mk_mil_t1_militia_swordsmen",
		"mk_mil_t1_mounted_crossbowmen",
		"mk_mil_t1_mounted_serjeants",
		"mk_mil_t1_spearmen",
		"mk_mil_t1_swordsmen",
	},
	["mk_fact_separatists_lorraine"] = {
		"mk_eur_t1_catapult",
		"mk_lor_t1_axemen",
		"mk_lor_t1_chevaliers",
		"mk_lor_t1_coutiliers",
		"mk_lor_t1_crossbowmen",
		"mk_lor_t1_horsemen",
		"mk_lor_t1_jager_crossbowmen",
		"mk_lor_t1_pikes",
		"mk_lor_t1_scouts",
		"mk_lor_t1_spearmen",
		"mk_lor_t1_swordsmen",
		"mk_lor_t1_urban_militia",
	},
	["mk_fact_separatists_makuria"] = {
		"mk_mak_t1_alodian_horsemen",
		"mk_mak_t1_arab_horsemen",
		"mk_mak_t1_arab_infantry",
		"mk_mak_t1_beja_bowmen",
		"mk_mak_t1_beja_camelry",
		"mk_mak_t1_beja_tribesmen",
		"mk_mak_t1_bukna_warband",
		"mk_mak_t1_frontier_guardsmen",
		"mk_mak_t1_nubian_archers",
		"mk_mak_t1_nubian_knights",
		"mk_mak_t1_nubian_light_cavalry",
		"mk_mak_t1_nubian_quilted_infantry",
		"mk_mak_t1_nubian_slingers",
		"mk_mak_t1_nubian_spearmen",
		"mk_mak_t1_sudanese_sheikhs",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_marinids"] = {
		"mk_alm_t1_abid_infantry",
		"mk_alm_t1_abid_skirmishers",
		"mk_alm_t1_arab_cavalry",
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_ghuzz_horse_archers",
		"mk_alm_t1_hushud",
		"mk_alm_t1_hushud_rumat",
		"mk_alm_t1_jund_al_nasara",
		"mk_alm_t1_jund_swordsmen",
		"mk_alm_t1_maghrebi_rumat",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_saqaliba_jund",
		"mk_alm_t1_slinger",
		"mk_mar_t1_beni_merin_lancers",
		"mk_mar_t1_humah_watanihi",
		"mk_mar_t1_mizwar_noble_horsemen",
		"mk_mar_t1_zanata_skirmishers",
		"mk_mar_t1_zenata_skirmish_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_mecca"] = {
		"mk_ayy_t1_ahdath",
		"mk_ayy_t1_ahdath_archers",
		"mk_ayy_t1_ajnad_cavalry",
		"mk_ayy_t1_askari_cavalry",
		"mk_ayy_t1_askari_nobles",
		"mk_ayy_t1_beduin_camel_riders",
		"mk_ayy_t1_crossbowmen",
		"mk_ayy_t1_harafisha_infantry",
		"mk_ayy_t1_jaridah_cav",
		"mk_ayy_t1_jund_spearmen",
		"mk_ayy_t1_jund_swordsmen",
		"mk_ayy_t1_naffatun",
		"mk_ayy_t1_nubian_spearmen",
		"mk_ayy_t1_shujan",
		"mk_ayy_t1_sudanese_archers",
		"mk_ayy_t1_tawashi",
		"mk_ayy_t1_thaqlah_axemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_milan"] = {
		"mk_eur_t1_catapult",
		"mk_mil_t1_archer_militia",
		"mk_mil_t1_archers",
		"mk_mil_t1_berrovieri",
		"mk_mil_t1_crossbowmen",
		"mk_mil_t1_foot_berrovieri",
		"mk_mil_t1_knights",
		"mk_mil_t1_light_cav",
		"mk_mil_t1_militia_crossbowmen",
		"mk_mil_t1_militia_spearmen",
		"mk_mil_t1_militia_swordsmen",
		"mk_mil_t1_mounted_crossbowmen",
		"mk_mil_t1_mounted_serjeants",
		"mk_mil_t1_spearmen",
		"mk_mil_t1_swordsmen",
	},
	["mk_fact_separatists_navarre"] = {
		"mk_eur_t1_catapult",
		"mk_nav_t1_caballeros",
		"mk_nav_t1_caballeros_spearmen",
		"mk_nav_t1_dismounted_hidalgos",
		"mk_nav_t1_hidalgos",
		"mk_nav_t1_militia_archers",
		"mk_nav_t1_militia_crossbowmen",
		"mk_nav_t1_militia_spearmen",
		"mk_nav_t1_peones",
		"mk_nav_t1_peones_spearmen",
		"mk_nav_t1_piquieros",
		"mk_nav_t1_slingers",
		"mk_nav_t1_vasque_skirmisher_cavalry",
		"mk_nav_t1_vasque_skirmishers",
	},
	["mk_fact_separatists_nicaea"] = {
		"mk_byz_t1_cataphractoi",
		"mk_byz_t1_catapult",
		"mk_byz_t1_gasmouloi",
		"mk_byz_t1_kavallarioi",
		"mk_byz_t1_kontaratoi",
		"mk_byz_t1_latinikon",
		"mk_byz_t1_militia_spearmen",
		"mk_byz_t1_mourtatoi",
		"mk_byz_t1_peltastoi",
		"mk_byz_t1_pronoiaroi",
		"mk_byz_t1_scoutatoi",
		"mk_byz_t1_scoutatoi_swordsmen",
		"mk_byz_t1_turcoman_HA",
	},
	["mk_fact_separatists_norway"] = {
		"mk_eur_t1_catapult",
		"mk_nor_t1_atgeir_bondir",
		"mk_nor_t1_bondir",
		"mk_nor_t1_bow_bondir",
		"mk_nor_t1_candle_men",
		"mk_nor_t1_crossbow_hirdmen",
		"mk_nor_t1_guest",
		"mk_nor_t1_hirdmen",
		"mk_nor_t1_knekts",
		"mk_nor_t1_orkney",
		"mk_nor_t1_riddere",
		"mk_nor_t1_spear_bondir",
		"mk_nor_t1_tablemen",
	},
	["mk_fact_separatists_oman"] = {
		"mk_ayy_t1_ahdath",
		"mk_ayy_t1_ahdath_archers",
		"mk_ayy_t1_ajnad_cavalry",
		"mk_ayy_t1_askari_cavalry",
		"mk_ayy_t1_askari_nobles",
		"mk_ayy_t1_beduin_camel_riders",
		"mk_ayy_t1_crossbowmen",
		"mk_ayy_t1_harafisha_infantry",
		"mk_ayy_t1_jaridah_cav",
		"mk_ayy_t1_jund_spearmen",
		"mk_ayy_t1_jund_swordsmen",
		"mk_ayy_t1_naffatun",
		"mk_ayy_t1_nubian_spearmen",
		"mk_ayy_t1_shujan",
		"mk_ayy_t1_sudanese_archers",
		"mk_ayy_t1_tawashi",
		"mk_ayy_t1_thaqlah_axemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_papacy"] = {
		"mk_eur_t1_catapult",
		"mk_pap_t1_archer_militia",
		"mk_pap_t1_archers",
		"mk_pap_t1_berrovieri",
		"mk_pap_t1_crossbow_militia",
		"mk_pap_t1_crossbowmen",
		"mk_pap_t1_foot_berrovieri",
		"mk_pap_t1_foot_latin_milites",
		"mk_pap_t1_latin_milites",
		"mk_pap_t1_mounted_crossbowmen",
		"mk_pap_t1_mounted_serjeants",
		"mk_pap_t1_papal_sergeants",
		"mk_pap_t1_spear_militia",
		"mk_pap_t1_spearmen",
		"mk_pap_t1_sword_militia",
		"mk_pap_t1_swordsmen",
	},
	["mk_fact_separatists_pisa"] = {
		"mk_eur_t1_catapult",
		"mk_pis_t1_archers",
		"mk_pis_t1_berrovieri",
		"mk_pis_t1_foot_berrovieri",
		"mk_pis_t1_ghibelline_crossbowmen",
		"mk_pis_t1_ghibelline_spearmen",
		"mk_pis_t1_knights",
		"mk_pis_t1_light_cav",
		"mk_pis_t1_militia_archer",
		"mk_pis_t1_militia_crossbowmen",
		"mk_pis_t1_militia_spearmen",
		"mk_pis_t1_militia_swordsmen",
		"mk_pis_t1_mounted_crossbowmen",
		"mk_pis_t1_swordsmen",
	},
	["mk_fact_separatists_portugal"] = {
		"mk_eur_t1_catapult",
		"mk_por_t1_besteiros",
		"mk_por_t1_cavaleiros",
		"mk_por_t1_cavaleiros_apeados",
		"mk_por_t1_cavaleiros_vilaos",
		"mk_por_t1_fundeiros",
		"mk_por_t1_milicia_concelhia",
		"mk_por_t1_peoes_de_besta",
		"mk_por_t1_peoes_de_dardo",
		"mk_por_t1_peoes_de_lanca",
	},
	["mk_fact_separatists_prussian"] = {
		"mk_lit_t1_axemen",
		"mk_lit_t1_boyars",
		"mk_lit_t1_ducal_axemen",
		"mk_lit_t1_ducal_spearmen",
		"mk_lit_t1_lithuanian_skirmishers",
		"mk_lit_t1_militia_crossbowmen",
		"mk_lit_t1_militia_spearmen",
		"mk_lit_t1_noble_cavalry",
		"mk_lit_t1_noble_swordsmen",
		"mk_lit_t1_ruthenian_archers",
		"mk_lit_t1_skirmisher_cavalry",
		"mk_rus_t1_catapult",
	},
	["mk_fact_separatists_rus"] = {
		"mk_rus_t1_catapult",
		"mk_rus_t1_dismounted_druzina",
		"mk_rus_t1_druzina",
		"mk_rus_t1_guard_axemen",
		"mk_rus_t1_javelinmen",
		"mk_rus_t1_militia_archers",
		"mk_rus_t1_militia_heavy_spearmen",
		"mk_rus_t1_militia_infantry",
		"mk_rus_t1_militia_spearmen",
		"mk_rus_t1_senior_druzina",
		"mk_rus_t1_spearmen",
		"mk_rus_t1_swordsmen",
		"mk_rus_t2_boyar_sons",
	},
	["mk_fact_separatists_schwyz"] = {
		"mk_eur_t1_catapult",
		"mk_swi_t1_archer_militia",
		"mk_swi_t1_archer_sergeants",
		"mk_swi_t1_crossbow_militia",
		"mk_swi_t1_crossbowmen",
		"mk_swi_t1_kyburg_axemen",
		"mk_swi_t1_kyburg_knights_mounted",
		"mk_swi_t1_kyburg_notables_mounted",
		"mk_swi_t1_landsturm_halberdiers",
		"mk_swi_t1_mounted_crossbows",
		"mk_swi_t1_zaehringer_schiltron",
		"mk_swi_t1_zaehringer_swordsmen",
	},
	["mk_fact_separatists_scotland"] = {
		"mk_sco_t1_ettrick_archers",
		"mk_sco_t1_highlanders",
		"mk_sco_t1_hobilars",
		"mk_sco_t1_knights",
		"mk_sco_t1_longbow_militia",
		"mk_sco_t1_pikemen",
		"mk_sco_t1_sergeants",
	},
	["mk_fact_separatists_seljuks"] = {
		"mk_mus_t1_catapult",
		"mk_rum_t1_askeri_nobles",
		"mk_rum_t1_futuwwa",
		"mk_rum_t1_ghazi_horse_archers",
		"mk_rum_t1_ghazi_lancers",
		"mk_rum_t1_ghazi_warriors",
		"mk_rum_t1_ghulam_foot_guard",
		"mk_rum_t1_jira_khaars",
		"mk_rum_t1_junior_ghulams",
		"mk_rum_t1_koyluleri",
		"mk_rum_t1_muqti_cavalry",
		"mk_rum_t1_naffatun",
		"mk_rum_t1_senior_ghulams",
		"mk_rum_t1_turcoman_tribal_cavalry",
		"mk_rum_t1_uc_suvarileri",
		"mk_rum_t1_uc_turkleri",
	},
	["mk_fact_separatists_serbia"] = {
		"mk_eur_t1_catapult",
		"mk_serb_t1_archers",
		"mk_serb_t1_frontiersmen",
		"mk_serb_t1_militia_spearmen",
		"mk_serb_t1_peasant_bowmen",
		"mk_serb_t1_pronija_lancer",
		"mk_serb_t1_vlastelicici",
		"mk_serb_t1_vojnici_axemen",
		"mk_serb_t1_vojnici_spearmen",
	},
	["mk_fact_separatists_sicily"] = {
		"mk_eur_t1_catapult",
		"mk_sic_t1_crossbowmen",
		"mk_sic_t1_ghibelline_spearmen",
		"mk_sic_t1_guelph_maa",
		"mk_sic_t1_guelph_mounted_maa",
		"mk_sic_t1_italian_jav_militia",
		"mk_sic_t1_knights",
		"mk_sic_t1_maa",
		"mk_sic_t1_militia_crossbowmen",
		"mk_sic_t1_militia_spearmen",
		"mk_sic_t1_militia_swordsmen",
		"mk_sic_t1_muslim_archers",
	},
	["mk_fact_separatists_sweden"] = {
		"mk_eur_t1_catapult",
		"mk_swd_t1_atgeir_bondir",
		"mk_swd_t1_bondir",
		"mk_swd_t1_crossbowmen",
		"mk_swd_t1_haelsing_hunters",
		"mk_swd_t1_hirdmen",
		"mk_swd_t1_jarl_bodyguard",
		"mk_swd_t1_mounted_fralse",
		"mk_swd_t1_sergeants",
		"mk_swd_t1_spear_bondir",
		"mk_swd_t1_svenns",
	},
	["mk_fact_separatists_tatars"] = {
		"mk_mon_t1_catapult",
		"mk_mon_t1_fire_lance_infantry",
		"mk_mon_t1_golden_hashar_levy",
		"mk_mon_t1_golden_heavy_horse_archers",
		"mk_mon_t1_golden_heavy_lancers",
		"mk_mon_t1_golden_horse_archers",
		"mk_mon_t1_golden_kharash",
		"mk_mon_t1_golden_lancers",
		"mk_mon_t1_golden_rus_archers",
		"mk_mon_t1_golden_tserig_spearmen",
		"mk_mon_t1_golden_turk_heavy_horse_archers",
		"mk_mon_t1_ilkhan_turkic_archers",
	},
	["mk_fact_separatists_teutonic"] = {
		"mk_eur_t1_catapult",
		"mk_teu_t1_levy_crossbowmen",
		"mk_teu_t1_levy_spearmen",
		"mk_teu_t1_livonian_crossbowmen",
		"mk_teu_t1_mounted_crossbowmen",
		"mk_teu_t1_mounted_sergeants",
		"mk_teu_t1_pogesanian_raiders",
		"mk_teu_t1_prussian_archers",
		"mk_teu_t1_ritterbruder",
		"mk_teu_t1_samlander_swordsmen",
		"mk_teu_t1_sergeant_brother",
		"mk_teu_t1_sergeant_brother_axemen",
		"mk_teu_t1_sergeant_spearmen",
		"mk_teu_t1_sudovian_skirmisher_cavalry",
		"mk_teu_t1_swordbrethren",
		"mk_teu_t1_swordbrother_knight",
	},
	["mk_fact_separatists_toulouse"] = {
		"mk_eur_t1_catapult",
		"mk_tou_t1_archers",
		"mk_tou_t1_chevaliers",
		"mk_tou_t1_cliens",
		"mk_tou_t1_communal_guisarmiers",
		"mk_tou_t1_crossbowmen",
		"mk_tou_t1_dismounted_chevaliers",
		"mk_tou_t1_levy_crossbowmen",
		"mk_tou_t1_mounted_crossbowmen",
		"mk_tou_t1_mounted_sergeants",
		"mk_tou_t1_ribauds",
		"mk_tou_t1_sergeant_axemen",
		"mk_tou_t1_sergeants",
		"mk_tou_t1_spear_levy",
		"mk_tou_t1_spearmen",
		"mk_tou_t1_voulge_militia",
	},
	["mk_fact_separatists_trebizond"] = {
		"mk_byz_t1_catapult",
		"mk_trbznd_t1_guard_archers",
		"mk_trbznd_t1_kavallarioi",
		"mk_trbznd_t1_militia",
		"mk_trbznd_t1_peltastoi",
		"mk_trbznd_t1_pronoia_lancers",
		"mk_trbznd_t1_scoutatoi",
		"mk_trbznd_t1_scoutatoi_swordsmen",
		"mk_trbznd_t1_toxotai",
		"mk_trbznd_t1_trapezitae_mounted_javcav",
		"mk_trbznd_t1_trebizond_archers",
	},
	["mk_fact_separatists_trier"] = {
		"mk_eur_t1_catapult",
		"mk_tri_t1_elector_bowmen",
		"mk_tri_t1_elector_knights",
		"mk_tri_t1_elector_spearmen",
		"mk_tri_t1_elector_swordsmen",
		"mk_tri_t1_trier_city_knights",
		"mk_tri_t1_trier_crossbowmen",
		"mk_tri_t1_trier_spearmen",
		"mk_tri_t1_trier_swordsmen",
	},
	["mk_fact_separatists_turks"] = {
		"mk_mus_t1_catapult",
		"mk_rum_t1_askeri_nobles",
		"mk_rum_t1_futuwwa",
		"mk_rum_t1_ghazi_horse_archers",
		"mk_rum_t1_ghazi_lancers",
		"mk_rum_t1_ghazi_warriors",
		"mk_rum_t1_ghulam_foot_guard",
		"mk_rum_t1_jira_khaars",
		"mk_rum_t1_junior_ghulams",
		"mk_rum_t1_koyluleri",
		"mk_rum_t1_muqti_cavalry",
		"mk_rum_t1_naffatun",
		"mk_rum_t1_senior_ghulams",
		"mk_rum_t1_turcoman_tribal_cavalry",
		"mk_rum_t1_uc_suvarileri",
		"mk_rum_t1_uc_turkleri",
	},
	["mk_fact_separatists_venice"] = {
		"mk_eur_t1_catapult",
		"mk_ven_t1_archers",
		"mk_ven_t1_crossbowmen",
		"mk_ven_t1_foot_zaffones",
		"mk_ven_t1_knight",
		"mk_ven_t1_militia_archer",
		"mk_ven_t1_militia_crossbowmen",
		"mk_ven_t1_militia_spearmen",
		"mk_ven_t1_militia_swordsmen",
		"mk_ven_t1_mounted_crossbow",
		"mk_ven_t1_mounted_zaffones",
		"mk_ven_t1_pikemen",
		"mk_ven_t1_scout",
		"mk_ven_t1_spearmen",
		"mk_ven_t1_swordsmen",
	},
	["mk_fact_separatists_volga"] = {
		"mk_mon_t1_catapult",
		"mk_volga_t1_chirmesh_HA",
		"mk_volga_t1_chirmesh_archers",
		"mk_volga_t1_chirmesh_lancers",
		"mk_volga_t1_chirmesh_spearmen",
		"mk_volga_t1_elite_archers",
		"mk_volga_t1_elite_cav",
		"mk_volga_t1_knights",
		"mk_volga_t1_light_HA",
		"mk_volga_t1_skirmisher_cavalry",
		"mk_volga_t1_tribal_archers",
		"mk_volga_t1_tribal_infantry",
		"mk_volga_t1_tribal_noble_archers",
		"mk_volga_t1_tribal_skirmishers",
		"mk_volga_t1_tribal_spearmen",
	},
	["mk_fact_separatists_wallachia"] = {
		"mk_byz_t1_catapult",
		"mk_vlach_t1_boieri",
		"mk_vlach_t1_boieri_archers",
		"mk_vlach_t1_calarasi_horse_archers",
		"mk_vlach_t1_curteni_cavalry",
		"mk_vlach_t1_maciuca_macemen",
		"mk_vlach_t1_militia_archers",
		"mk_vlach_t1_militia_spearmen",
		"mk_vlach_t1_mosneni",
		"mk_vlach_t1_mosneni_archers",
		"mk_vlach_t1_peasants",
		"mk_vlach_t1_plaiesi_javelinmen",
	},
	["mk_fact_separatists_wendish"] = {
		"mk_eur_t1_catapult",
		"mk_pol_t1_archers_lesser_poland",
		"mk_pol_t1_axemen_lesser_poland",
		"mk_pol_t1_knight_lesser_poland",
		"mk_pol_t1_militia_crossbowmen",
		"mk_pol_t1_militia_spearmen",
		"mk_pol_t1_mounted_crossbowmen",
		"mk_pol_t1_mounted_sergeants",
		"mk_pol_t1_sergeant_crossbowmen_lesser_poland",
		"mk_pol_t1_sergeant_spearmen",
		"mk_pol_t1_sergeants",
	},
	["mk_fact_separatists_zagwe"] = {
		"mk_mus_t1_catapult",
		"mk_zag_t1_aqaytat",
		"mk_zag_t1_bow_sarawit",
		"mk_zag_t1_hadar_frontiersmen",
		"mk_zag_t1_heroic_horsemen",
		"mk_zag_t1_highland_angada",
		"mk_zag_t1_horse_sarawit",
		"mk_zag_t1_spear_sarawit",
	},
	["mk_fact_separatists_zengid"] = {
		"mk_ata_t1_askari",
		"mk_ata_t1_ghazi_cavalry",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
		"mk_zen_t1_arab_jarida",
		"mk_zen_t1_jazira_infantry",
		"mk_zen_t1_jazira_spearmen",
		"mk_zen_t1_tawashi_cavalry",
	},
};

DIPLOMACY_OPTIONS = {
	"trade agreement",
	"hard military access",
	"cancel hard military access",
	"military alliance",
	"regions",
	"technology",
	"state gift",
	"payments",
	"vassal",
	"peace",
	"war",
	"join war",
	"break trade",
	"break alliance",
	"hostages",
	"marriage",
	"non aggression pact",
	"soft military access",
	"cancel soft military access",
	"defensive alliance",
	"client state",
	--"form confederation",
	"break non aggression pact",
	"break soft military access",
	"break defensive alliance",
	"break vassal",
	"break client state",
	"state gift unilateral"
};

MAX_TECHS = {
	{"mk_barb_civil_imperial_autocracy", "mk_barb_military_massed_infantry_formations"},
	{"mk_east_civil_discovery_of_coffee", "mk_east_military_joint_operations"},
	{"mk_noma_civil_chingissid_legacy", "mk_noma_military_nonlinear_combat_tactics"},
	{"mk_orth_civil_imperial_restoration", "mk_orth_military_military_renaissance"},
	{"mk_west_civil_new_world_expeditions", "mk_west_military_combined_arms_tactics"}
}
