----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--
-- 	MEDIEVAL KINGDOMS 1212 - COMMON LISTS
-- 	By: DETrooper
--
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------

REGIONS_TO_PROVINCES_LIST = {
	["att_reg_aegyptus_alexandria"] = "mk_prov_alexandria",
	["att_reg_aegyptus_berenice"] = "mk_prov_berenice",
	["att_reg_aegyptus_oxyrhynchus"] = "mk_prov_oxyrhynchus",
	["att_reg_aethiopia_adulis"] = "mk_prov_adulis",
	["att_reg_aethiopia_aksum"] = "mk_prov_aksum",
	["att_reg_aethiopia_pachoras"] = "mk_prov_pachoras",
	["att_reg_africa_carthago"] = "mk_prov_carthago",
	["att_reg_africa_constantina"] = "mk_prov_constantina",
	["att_reg_africa_hadrumentum"] = "mk_prov_hadrumentum",
	["att_reg_aquitania_avaricum"] = "mk_prov_avaricum",
	["att_reg_aquitania_burdigala"] = "mk_prov_burdigala",
	["att_reg_aquitania_elusa"] = "mk_prov_elusa",
	["att_reg_arabia_felix_eudaemon"] = "mk_prov_eudaemon",
	["att_reg_arabia_felix_omana"] = "mk_prov_omana",
	["att_reg_arabia_felix_zafar"] = "mk_prov_zafar",
	["att_reg_arabia_magna_dumatha"] = "mk_prov_dumatha",
	["att_reg_arabia_magna_hira"] = "mk_prov_hira",
	["att_reg_arabia_magna_yathrib"] = "mk_prov_yathrib",
	["att_reg_armenia_duin"] = "mk_prov_duin",
	["att_reg_armenia_payttakaran"] = "mk_prov_payttakaran",
	["att_reg_armenia_tosp"] = "mk_prov_tosp",
	["att_reg_asia_cyzicus"] = "mk_prov_cyzicus",
	["att_reg_asia_ephesus"] = "mk_prov_ephesus",
	["att_reg_asia_synnada"] = "mk_prov_synnada",
	["att_reg_asorstan_arbela"] = "mk_prov_arbela",
	["att_reg_asorstan_ctesiphon"] = "mk_prov_ctesiphon",
	["att_reg_asorstan_meshan"] = "mk_prov_meshan",
	["att_reg_baetica_corduba"] = "mk_prov_corduba",
	["att_reg_baetica_hispalis"] = "mk_prov_hispalis",
	["att_reg_baetica_malaca"] = "mk_prov_malaca",
	["att_reg_belgica_augusta_treverorum"] = "mk_prov_augusta_treverorum",
	["att_reg_belgica_colonia_agrippina"] = "mk_prov_colonia_agrippina",
	["att_reg_belgica_durocorterum"] = "mk_prov_durocorterum",
	["att_reg_bithynia_amasea"] = "mk_prov_amasea",
	["att_reg_bithynia_ancyra"] = "mk_prov_ancyra",
	["att_reg_bithynia_nicomedia"] = "mk_prov_nicomedia",
	["att_reg_britannia_inferior_eboracum"] = "mk_prov_eboracum",
	["att_reg_britannia_inferior_lindum"] = "mk_prov_lindum",
	["att_reg_britannia_inferior_segontium"] = "mk_prov_segontium",
	["att_reg_britannia_superior_camulodunon"] = "mk_prov_camulodunon",
	["att_reg_britannia_superior_corinium"] = "mk_prov_corinium",
	["att_reg_britannia_superior_londinium"] = "mk_prov_londinium",
	["att_reg_caledonia_et_hibernia_eblana"] = "mk_prov_eblana",
	["att_reg_caledonia_et_hibernia_eildon"] = "mk_prov_eildon",
	["att_reg_caledonia_et_hibernia_tuesis"] = "mk_prov_tuesis",
	["att_reg_cappadocia_caesarea_eusebia"] = "mk_prov_caesarea_eusebia",
	["att_reg_cappadocia_melitene"] = "mk_prov_melitene",
	["att_reg_cappadocia_trapezus"] = "mk_prov_trapezus",
	["att_reg_carthaginensis_carthago_nova"] = "mk_prov_carthago_nova",
	["att_reg_carthaginensis_segobriga"] = "mk_prov_segobriga",
	["att_reg_carthaginensis_toletum"] = "mk_prov_toletum",
	["att_reg_caucasia_gabala"] = "mk_prov_gabala",
	["att_reg_caucasia_kotais"] = "mk_prov_kotais",
	["att_reg_caucasia_mtskheta"] = "mk_prov_mtskheta",
	["att_reg_cilicia_iconium"] = "mk_prov_iconium",
	["att_reg_cilicia_myra"] = "mk_prov_myra",
	["att_reg_cilicia_tarsus"] = "mk_prov_tarsus",
	["att_reg_dacia_apulum"] = "mk_prov_apulum",
	["att_reg_dacia_petrodava"] = "mk_prov_petrodava",
	["att_reg_dacia_romula"] = "mk_prov_romula",
	["att_reg_dalmatia_domavia"] = "mk_prov_domavia",
	["att_reg_dalmatia_salona"] = "mk_prov_salona",
	["att_reg_dalmatia_siscia"] = "mk_prov_siscia",
	["att_reg_dardania_scupi"] = "mk_prov_scupi",
	["att_reg_dardania_serdica"] = "mk_prov_serdica",
	["att_reg_dardania_viminacium"] = "mk_prov_viminacium",
	["att_reg_frisia_angulus"] = "mk_prov_angulus",
	["att_reg_frisia_flevum"] = "mk_prov_flevum",
	["att_reg_frisia_tulifurdum"] = "mk_prov_tulifurdum",
	["att_reg_gallaecia_asturica"] = "mk_prov_asturica",
	["att_reg_gallaecia_bracara"] = "mk_prov_bracara",
	["att_reg_gallaecia_brigantium"] = "mk_prov_brigantium",
	["att_reg_germania_aregelia"] = "mk_prov_aregelia",
	["att_reg_germania_lupfurdum"] = "mk_prov_lupfurdum",
	["att_reg_germania_uburzis"] = "mk_prov_uburzis",
	["att_reg_germano_sarmatia_duna"] = "mk_prov_duna",
	["att_reg_germano_sarmatia_oium"] = "mk_prov_oium",
	["att_reg_germano_sarmatia_palteskja"] = "mk_prov_palteskja",
	["att_reg_gothiscandza_ascaucalis"] = "mk_prov_ascaucalis",
	["att_reg_gothiscandza_gothiscandza"] = "mk_prov_gothiscandza",
	["att_reg_gothiscandza_rugion"] = "mk_prov_rugion",
	["att_reg_hercynia_budorgis"] = "mk_prov_budorgis",
	["att_reg_hercynia_casurgis"] = "mk_prov_casurgis",
	["att_reg_hercynia_nitrahwa"] = "mk_prov_nitrahwa",
	["att_reg_hyperborea_kariskos"] = "mk_prov_kariskos",
	["att_reg_hyperborea_moramar"] = "mk_prov_moramar",
	["att_reg_hyperborea_sylis"] = "mk_prov_sylis",
	["att_reg_italia_fiorentia"] = "mk_prov_fiorentia",
	["att_reg_italia_neapolis"] = "mk_prov_neapolis",
	["att_reg_italia_roma"] = "mk_prov_roma",
	["att_reg_khwarasan_abarshahr"] = "mk_prov_abarshahr",
	["att_reg_khwarasan_harey"] = "mk_prov_harey",
	["att_reg_khwarasan_merv"] = "mk_prov_merv",
	["att_reg_libya_augila"] = "mk_prov_augila",
	["att_reg_libya_paraetonium"] = "mk_prov_paraetonium",
	["att_reg_libya_ptolemais"] = "mk_prov_ptolemais",
	["att_reg_liguria_genua"] = "mk_prov_genua",
	["att_reg_liguria_mediolanum"] = "mk_prov_mediolanum",
	["att_reg_liguria_segusio"] = "mk_prov_segusio",
	["att_reg_lugdunensis_lugdunum"] = "mk_prov_lugdunum",
	["att_reg_lugdunensis_rotomagus"] = "mk_prov_rotomagus",
	["att_reg_lugdunensis_turonum"] = "mk_prov_turonum",
	["att_reg_lusitania_emerita_augusta"] = "mk_prov_emerita_augusta",
	["att_reg_lusitania_olisipo"] = "mk_prov_olisipo",
	["att_reg_lusitania_pax_augusta"] = "mk_prov_pax_augusta",
	["att_reg_macedonia_corinthus"] = "mk_prov_corinthus",
	["att_reg_macedonia_dyrrhachium"] = "mk_prov_dyrrhachium",
	["att_reg_macedonia_thessalonica"] = "mk_prov_thessalonica",
	["att_reg_magna_graecia_rhegium"] = "mk_prov_rhegium",
	["att_reg_magna_graecia_syracusae"] = "mk_prov_syracusae",
	["att_reg_magna_graecia_tarentum"] = "mk_prov_tarentum",
	["att_reg_makran_harmosia"] = "mk_prov_harmosia",
	["att_reg_makran_phra"] = "mk_prov_phra",
	["att_reg_makran_pura"] = "mk_prov_pura",
	["att_reg_mauretania_caesarea"] = "mk_prov_caesarea",
	["att_reg_mauretania_tamousiga"] = "mk_prov_tamousiga",
	["att_reg_mauretania_tingis"] = "mk_prov_tingis",
	["att_reg_maxima_sequanorum_argentoratum"] = "mk_prov_argentoratum",
	["att_reg_maxima_sequanorum_octodurus"] = "mk_prov_octodurus",
	["att_reg_maxima_sequanorum_vesontio"] = "mk_prov_vesontio",
	["att_reg_media_atropatene_ecbatana"] = "mk_prov_ecbatana",
	["att_reg_media_atropatene_ganzaga"] = "mk_prov_ganzaga",
	["att_reg_media_atropatene_rhaga"] = "mk_prov_rhaga",
	["att_reg_mediterraneus_occidentalis_ajax"] = "mk_prov_ajax",
	["att_reg_mediterraneus_occidentalis_caralis"] = "mk_prov_caralis",
	["att_reg_mediterraneus_occidentalis_palma"] = "mk_prov_palma",
	["att_reg_mediterraneus_orientalis_constantia"] = "mk_prov_constantia",
	["att_reg_mediterraneus_orientalis_gortyna"] = "mk_prov_gortyna",
	["att_reg_mediterraneus_orientalis_rhodes"] = "mk_prov_rhodes",
	["att_reg_narbonensis_aquae_sextiae"] = "mk_prov_aquae_sextiae",
	["att_reg_narbonensis_narbo"] = "mk_prov_narbo",
	["att_reg_narbonensis_vienna"] = "mk_prov_vienna",
	["att_reg_osroene_amida"] = "mk_prov_amida",
	["att_reg_osroene_edessa"] = "mk_prov_edessa",
	["att_reg_osroene_nisibis"] = "mk_prov_nisibis",
	["att_reg_palaestinea_aelia_capitolina"] = "mk_prov_aelia_capitolina",
	["att_reg_palaestinea_aila"] = "mk_prov_aila",
	["att_reg_palaestinea_nova_trajana_bostra"] = "mk_prov_nova_trajana_bostra",
	["att_reg_pannonia_savaria"] = "mk_prov_savaria",
	["att_reg_pannonia_sirmium"] = "mk_prov_sirmium",
	["att_reg_pannonia_sopianae"] = "mk_prov_sopianae",
	["att_reg_persis_behdeshir"] = "mk_prov_behdeshir",
	["att_reg_persis_siraf"] = "mk_prov_siraf",
	["att_reg_persis_stakhr"] = "mk_prov_stakhr",
	["att_reg_phazania_cydamus"] = "mk_prov_cydamus",
	["att_reg_phazania_dimmidi"] = "mk_prov_dimmidi",
	["att_reg_phazania_garama"] = "mk_prov_garama",
	["att_reg_raetia_et_noricum_augusta_vindelicorum"] = "mk_prov_augusta_vindelicorum",
	["att_reg_raetia_et_noricum_iuvavum"] = "mk_prov_iuvavum",
	["att_reg_raetia_et_noricum_virunum"] = "mk_prov_virunum",
	["att_reg_sarmatia_asiatica_anacopia"] = "mk_prov_anacopia",
	["att_reg_sarmatia_asiatica_samandar"] = "mk_prov_samandar",
	["att_reg_sarmatia_asiatica_tanais"] = "mk_prov_tanais",
	["att_reg_sarmatia_europaea_chersonessus"] = "mk_prov_chersonessus",
	["att_reg_sarmatia_europaea_gelonus"] = "mk_prov_gelonus",
	["att_reg_sarmatia_europaea_olbia"] = "mk_prov_olbia",
	["att_reg_scandza_alabu"] = "mk_prov_alabu",
	["att_reg_scandza_hafn"] = "mk_prov_hafn",
	["att_reg_scandza_hrefnesholt"] = "mk_prov_hrefnesholt",
	["att_reg_scythia_bolghar"] = "mk_prov_bolghar",
	["att_reg_scythia_ra"] = "mk_prov_ra",
	["att_reg_scythia_sarai"] = "mk_prov_sarai",
	["att_reg_spahan_issatis"] = "mk_prov_issatis",
	["att_reg_spahan_spahan"] = "mk_prov_spahan",
	["att_reg_spahan_susa"] = "mk_prov_susa",
	["att_reg_syria_antiochia"] = "mk_prov_antiochia",
	["att_reg_syria_emesa"] = "mk_prov_emesa",
	["att_reg_syria_tyrus"] = "mk_prov_tyrus",
	["att_reg_tarraconensis_caesaraugusta"] = "mk_prov_caesaraugusta",
	["att_reg_tarraconensis_pompaelo"] = "mk_prov_pompaelo",
	["att_reg_tarraconensis_tarraco"] = "mk_prov_tarraco",
	["att_reg_thracia_constantinopolis"] = "mk_prov_constantinopolis",
	["att_reg_thracia_marcianopolis"] = "mk_prov_marcianopolis",
	["att_reg_thracia_trimontium"] = "mk_prov_trimontium",
	["att_reg_transcarpathia_arheimar"] = "mk_prov_arheimar",
	["att_reg_transcarpathia_belz"] = "mk_prov_belz",
	["att_reg_transcarpathia_leopolis"] = "mk_prov_leopolis",
	["att_reg_transcaspia_dahistan"] = "mk_prov_dahistan",
	["att_reg_transcaspia_kath"] = "mk_prov_kath",
	["att_reg_transcaspia_siahkuh"] = "mk_prov_siahkuh",
	["att_reg_tripolitana_leptis_magna"] = "mk_prov_leptis_magna",
	["att_reg_tripolitana_macomades"] = "mk_prov_macomades",
	["att_reg_tripolitana_sabrata"] = "mk_prov_sabrata",
	["att_reg_venetia_aquileia"] = "mk_prov_aquileia",
	["att_reg_venetia_ravenna"] = "mk_prov_ravenna",
	["att_reg_venetia_verona"] = "mk_prov_verona",
};

DIPLOMACY_OPTIONS = {
	"trade agreement",
	"hard military access",
	"cancel hard military access",
	"military alliance",
	"regions",
	"technology",
	"state gift",
	"payments",
	"vassal",
	"peace",
	"war",
	"join war",
	"break trade",
	"break alliance",
	"hostages",
	"marriage",
	"non aggression pact",
	"soft military access",
	"cancel soft military access",
	"defensive alliance",
	"client state",
	--"form confederation",
	"break non aggression pact",
	"break soft military access",
	"break defensive alliance",
	"break vassal",
	"break client state",
	"state gift unilateral"
};

MAX_TECHS = {
	{"mk_barb_civil_imperial_autocracy", "mk_barb_military_massed_infantry_formations"},
	{"mk_east_civil_discovery_of_coffee", "mk_east_military_joint_operations"},
	{"mk_noma_civil_chingissid_legacy", "mk_noma_military_nonlinear_combat_tactics"},
	{"mk_orth_civil_imperial_restoration", "mk_orth_military_military_renaissance"},
	{"mk_west_civil_new_world_expeditions", "mk_west_military_combined_arms_tactics"}
}
