----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--
-- 	MEDIEVAL KINGDOMS 1212 - COMMON LISTS
-- 	By: DETrooper
--
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------

PROVINCES_LIST = {
	"_aegyptus_",
	"_aethiopia_",
	"_africa_",
	"_aquitania_",
	"_arabia_felix_",
	"_arabia_magna_",
	"_armenia_",
	"_asia_",
	"_asorstan_",
	"_baetica_",
	"_belgica_",
	"_bithynia_",
	"_britannia_inferior_",
	"_britannia_superior_",
	"_caledonia_et_hbernia_",
	"_cappadocia_",
	"_carthaginensis_",
	"_caucasia_",
	"_cilicia_",
	"_dacia_",
	"_dalmatia_",
	"_dardania_",
	"_frisia_",
	"_gallaecia_",
	"_germania_",
	"_germano-sarmatia_",
	"_gothiscandza_",
	"_hercynia_",
	"_hyperborea_",
	"_italia_",
	"_khwarasan_",
	"_libya_",
	"_liguria_",
	"_lugdunensis_",
	"_lusitania_",
	"_macedonia_",
	"_magna_graecia_",
	"_makran_",
	"_mauretania_",
	"_maxima_sequanorum_",
	"_media_atropatene_",
	"_mediterraneus_occidentalis_",
	"_mediterraneus_orientalis_",
	"_narbonensis_",
	"_osroene_",
	"_palaestinea_",
	"_pannonia_",
	"_persis_",
	"_phazania_",
	"_raetia_et_noricum_",
	"_sarmatia_asiatica_",
	"_sarmatia_europaea_",
	"_scandza_",
	"_scythia_",
	"_spahan_",
	"_syria_",
	"_tarraconensis_",
	"_thracia_",
	"_transcarpathia_",
	"_transcaspia_",
	"_tripolitana_",
	"_venetia_"
};

REGIONS_LIST = {
	"att_reg_aegyptus_alexandria",
	"att_reg_aegyptus_berenice",
	"att_reg_aegyptus_oxyrhynchus",
	"att_reg_aethiopia_adulis",
	"att_reg_aethiopia_aksum",
	"att_reg_aethiopia_pachoras",
	"att_reg_africa_carthago",
	"att_reg_africa_constantina",
	"att_reg_africa_hadrumentum",
	"att_reg_aquitania_avaricum",
	"att_reg_aquitania_burdigala",
	"att_reg_aquitania_elusa",
	"att_reg_arabia_felix_eudaemon",
	"att_reg_arabia_felix_omana",
	"att_reg_arabia_felix_zafar",
	"att_reg_arabia_magna_dumatha",
	"att_reg_arabia_magna_hira",
	"att_reg_arabia_magna_yathrib",
	"att_reg_armenia_duin",
	"att_reg_armenia_payttakaran",
	"att_reg_armenia_tosp",
	"att_reg_asia_cyzicus",
	"att_reg_asia_ephesus",
	"att_reg_asia_synnada",
	"att_reg_asorstan_arbela",
	"att_reg_asorstan_ctesiphon",
	"att_reg_asorstan_meshan",
	"att_reg_baetica_corduba",
	"att_reg_baetica_hispalis",
	"att_reg_baetica_malaca",
	"att_reg_belgica_augusta_treverorum",
	"att_reg_belgica_colonia_agrippina",
	"att_reg_belgica_durocorterum",
	"att_reg_bithynia_amasea",
	"att_reg_bithynia_ancyra",
	"att_reg_bithynia_nicomedia",
	"att_reg_britannia_inferior_eboracum",
	"att_reg_britannia_inferior_lindum",
	"att_reg_britannia_inferior_segontium",
	"att_reg_britannia_superior_camulodunon",
	"att_reg_britannia_superior_corinium",
	"att_reg_britannia_superior_londinium",
	"att_reg_caledonia_et_hibernia_eblana",
	"att_reg_caledonia_et_hibernia_eildon",
	"att_reg_caledonia_et_hibernia_tuesis",
	"att_reg_cappadocia_caesarea_eusebia",
	"att_reg_cappadocia_melitene",
	"att_reg_cappadocia_trapezus",
	"att_reg_carthaginensis_carthago_nova",
	"att_reg_carthaginensis_segobriga",
	"att_reg_carthaginensis_toletum",
	"att_reg_caucasia_gabala",
	"att_reg_caucasia_kotais",
	"att_reg_caucasia_mtskheta",
	"att_reg_cilicia_iconium",
	"att_reg_cilicia_myra",
	"att_reg_cilicia_tarsus",
	"att_reg_dacia_apulum",
	"att_reg_dacia_petrodava",
	"att_reg_dacia_romula",
	"att_reg_dalmatia_domavia",
	"att_reg_dalmatia_salona",
	"att_reg_dalmatia_siscia",
	"att_reg_dardania_scupi",
	"att_reg_dardania_serdica",
	"att_reg_dardania_viminacium",
	"att_reg_frisia_angulus",
	"att_reg_frisia_flevum",
	"att_reg_frisia_tulifurdum",
	"att_reg_gallaecia_asturica",
	"att_reg_gallaecia_bracara",
	"att_reg_gallaecia_brigantium",
	"att_reg_germania_aregelia",
	"att_reg_germania_lupfurdum",
	"att_reg_germania_uburzis",
	"att_reg_germano_sarmatia_duna",
	"att_reg_germano_sarmatia_oium",
	"att_reg_germano_sarmatia_palteskja",
	"att_reg_gothiscandza_ascaucalis",
	"att_reg_gothiscandza_gothiscandza",
	"att_reg_gothiscandza_rugion",
	"att_reg_hercynia_budorgis",
	"att_reg_hercynia_casurgis",
	"att_reg_hercynia_nitrahwa",
	"att_reg_hyperborea_kariskos",
	"att_reg_hyperborea_moramar",
	"att_reg_hyperborea_sylis",
	"att_reg_italia_fiorentia",
	"att_reg_italia_neapolis",
	"att_reg_italia_roma",
	"att_reg_khwarasan_abarshahr",
	"att_reg_khwarasan_harey",
	"att_reg_khwarasan_merv",
	"att_reg_libya_augila",
	"att_reg_libya_paraetonium",
	"att_reg_libya_ptolemais",
	"att_reg_liguria_genua",
	"att_reg_liguria_mediolanum",
	"att_reg_liguria_segusio",
	"att_reg_lugdunensis_lugdunum",
	"att_reg_lugdunensis_rotomagus",
	"att_reg_lugdunensis_turonum",
	"att_reg_lusitania_emerita_augusta",
	"att_reg_lusitania_olisipo",
	"att_reg_lusitania_pax_augusta",
	"att_reg_macedonia_corinthus",
	"att_reg_macedonia_dyrrhachium",
	"att_reg_macedonia_thessalonica",
	"att_reg_magna_graecia_rhegium",
	"att_reg_magna_graecia_syracusae",
	"att_reg_magna_graecia_tarentum",
	"att_reg_makran_harmosia",
	"att_reg_makran_phra",
	"att_reg_makran_pura",
	"att_reg_mauretania_caesarea",
	"att_reg_mauretania_tamousiga",
	"att_reg_mauretania_tingis",
	"att_reg_maxima_sequanorum_argentoratum",
	"att_reg_maxima_sequanorum_octodurus",
	"att_reg_maxima_sequanorum_vesontio",
	"att_reg_media_atropatene_ecbatana",
	"att_reg_media_atropatene_ganzaga",
	"att_reg_media_atropatene_rhaga",
	"att_reg_mediterraneus_occidentalis_ajax",
	"att_reg_mediterraneus_occidentalis_caralis",
	"att_reg_mediterraneus_occidentalis_palma",
	"att_reg_mediterraneus_orientalis_constantia",
	"att_reg_mediterraneus_orientalis_gortyna",
	"att_reg_mediterraneus_orientalis_rhodes",
	"att_reg_narbonensis_aquae_sextiae",
	"att_reg_narbonensis_narbo",
	"att_reg_narbonensis_vienna",
	"att_reg_osroene_amida",
	"att_reg_osroene_edessa",
	"att_reg_osroene_nisibis",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_palaestinea_aila",
	"att_reg_palaestinea_nova_trajana_bostra",
	"att_reg_pannonia_savaria",
	"att_reg_pannonia_sirmium",
	"att_reg_pannonia_sopianae",
	"att_reg_persis_behdeshir",
	"att_reg_persis_siraf",
	"att_reg_persis_stakhr",
	"att_reg_phazania_cydamus",
	"att_reg_phazania_dimmidi",
	"att_reg_phazania_garama",
	"att_reg_raetia_et_noricum_augusta_vindelicorum",
	"att_reg_raetia_et_noricum_iuvavum",
	"att_reg_raetia_et_noricum_virunum",
	"att_reg_sarmatia_asiatica_anacopia",
	"att_reg_sarmatia_asiatica_samandar",
	"att_reg_sarmatia_asiatica_tanais",
	"att_reg_sarmatia_europaea_chersonessus",
	"att_reg_sarmatia_europaea_gelonus",
	"att_reg_sarmatia_europaea_olbia",
	"att_reg_scandza_alabu",
	"att_reg_scandza_hafn",
	"att_reg_scandza_hrefnesholt",
	"att_reg_scythia_bolghar",
	"att_reg_scythia_ra",
	"att_reg_scythia_sarai",
	"att_reg_spahan_issatis",
	"att_reg_spahan_spahan",
	"att_reg_spahan_susa",
	"att_reg_syria_antiochia",
	"att_reg_syria_emesa",
	"att_reg_syria_tyrus",
	"att_reg_tarraconensis_caesaraugusta",
	"att_reg_tarraconensis_pompaelo",
	"att_reg_tarraconensis_tarraco",
	"att_reg_terra_incognita",
	"att_reg_thracia_constantinopolis",
	"att_reg_thracia_marcianopolis",
	"att_reg_thracia_trimontium",
	"att_reg_transcarpathia_arheimar",
	"att_reg_transcarpathia_belz",
	"att_reg_transcarpathia_leopolis",
	"att_reg_transcaspia_dahistan",
	"att_reg_transcaspia_kath",
	"att_reg_transcaspia_siahkuh",
	"att_reg_tripolitana_leptis_magna",
	"att_reg_tripolitana_macomades",
	"att_reg_tripolitana_sabrata",
	"att_reg_venetia_aquileia",
	"att_reg_venetia_ravenna",
	"att_reg_venetia_verona"
};

REGIONS_TO_PROVINCE_ORDER_LIST = {
	att_reg_aegyptus_alexandria = 1,
	att_reg_aegyptus_berenice = 2,
	att_reg_aegyptus_oxyrhynchus = 3,
	att_reg_aethiopia_adulis = 3,
	att_reg_aethiopia_aksum = 1,
	att_reg_aethiopia_pachoras = 2,
	att_reg_africa_carthago = 1,
	att_reg_africa_constantina = 2,
	att_reg_africa_hadrumentum = 3,
	att_reg_aquitania_avaricum = 2,
	att_reg_aquitania_burdigala = 1,
	att_reg_aquitania_elusa = 3,
	att_reg_arabia_felix_eudaemon = 2,
	att_reg_arabia_felix_omana = 3,
	att_reg_arabia_felix_zafar = 1,
	att_reg_arabia_magna_dumatha = 2,
	att_reg_arabia_magna_hira = 1,
	att_reg_arabia_magna_yathrib = 3,
	att_reg_armenia_duin = 1,
	att_reg_armenia_payttakaran = 2,
	att_reg_armenia_tosp = 3,
	att_reg_asia_cyzicus = 3,
	att_reg_asia_ephesus = 1,
	att_reg_asia_synnada = 2,
	att_reg_asorstan_arbela = 3,
	att_reg_asorstan_ctesiphon = 1,
	att_reg_asorstan_meshan = 2,
	att_reg_baetica_corduba = 1,
	att_reg_baetica_hispalis = 3,
	att_reg_baetica_malaca = 2,
	att_reg_belgica_augusta_treverorum = 1,
	att_reg_belgica_colonia_agrippina = 2,
	att_reg_belgica_durocorterum = 3,
	att_reg_bithynia_amasea = 2,
	att_reg_bithynia_ancyra = 1,
	att_reg_bithynia_nicomedia = 3,
	att_reg_britannia_inferior_eboracum = 1,
	att_reg_britannia_inferior_lindum = 2,
	att_reg_britannia_inferior_segontium = 3,
	att_reg_britannia_superior_camulodunon = 2,
	att_reg_britannia_superior_corinium = 3,
	att_reg_britannia_superior_londinium = 1,
	att_reg_caledonia_et_hibernia_eblana = 3,
	att_reg_caledonia_et_hibernia_eildon = 2,
	att_reg_caledonia_et_hibernia_tuesis = 1,
	att_reg_cappadocia_caesarea_eusebia = 1,
	att_reg_cappadocia_melitene = 3,
	att_reg_cappadocia_trapezus = 2,
	att_reg_carthaginensis_carthago_nova = 1,
	att_reg_carthaginensis_segobriga = 3,
	att_reg_carthaginensis_toletum = 2,
	att_reg_caucasia_gabala = 2,
	att_reg_caucasia_kotais = 3,
	att_reg_caucasia_mtskheta = 1,
	att_reg_cilicia_iconium = 3,
	att_reg_cilicia_myra = 2,
	att_reg_cilicia_tarsus = 1,
	att_reg_dacia_apulum = 1,
	att_reg_dacia_petrodava = 3,
	att_reg_dacia_romula = 2,
	att_reg_dalmatia_domavia = 3,
	att_reg_dalmatia_salona = 1,
	att_reg_dalmatia_siscia = 2,
	att_reg_dardania_scupi = 2,
	att_reg_dardania_serdica = 1,
	att_reg_dardania_viminacium = 3,
	att_reg_frisia_angulus = 3,
	att_reg_frisia_flevum = 2,
	att_reg_frisia_tulifurdum = 1,
	att_reg_gallaecia_asturica = 3,
	att_reg_gallaecia_bracara = 1,
	att_reg_gallaecia_brigantium = 2,
	att_reg_germania_aregelia = 2,
	att_reg_germania_lupfurdum = 3,
	att_reg_germania_uburzis = 1,
	att_reg_germano_sarmatia_duna = 1,
	att_reg_germano_sarmatia_oium = 1,
	att_reg_germano_sarmatia_palteskja = 1,
	att_reg_gothiscandza_ascaucalis = 2,
	att_reg_gothiscandza_gothiscandza = 1,
	att_reg_gothiscandza_rugion = 3,
	att_reg_hercynia_budorgis = 2,
	att_reg_hercynia_casurgis = 1,
	att_reg_hercynia_nitrahwa = 3,
	att_reg_hyperborea_kariskos = 1,
	att_reg_hyperborea_moramar = 3,
	att_reg_hyperborea_sylis = 2,
	att_reg_italia_fiorentia = 2,
	att_reg_italia_neapolis = 3,
	att_reg_italia_roma = 1,
	att_reg_khwarasan_abarshahr = 1,
	att_reg_khwarasan_harey = 3,
	att_reg_khwarasan_merv = 2,
	att_reg_libya_augila = 3,
	att_reg_libya_paraetonium = 2,
	att_reg_libya_ptolemais = 1,
	att_reg_liguria_genua = 3,
	att_reg_liguria_mediolanum = 1,
	att_reg_liguria_segusio = 2,
	att_reg_lugdunensis_lugdunum = 1,
	att_reg_lugdunensis_rotomagus = 2,
	att_reg_lugdunensis_turonum = 3,
	att_reg_lusitania_emerita_augusta = 2,
	att_reg_lusitania_olisipo = 1,
	att_reg_lusitania_pax_augusta = 3,
	att_reg_macedonia_corinthus = 2,
	att_reg_macedonia_dyrrhachium = 3,
	att_reg_macedonia_thessalonica = 1,
	att_reg_magna_graecia_rhegium = 3,
	att_reg_magna_graecia_syracusae = 2,
	att_reg_magna_graecia_tarentum = 1,
	att_reg_makran_harmosia = 3,
	att_reg_makran_phra = 2,
	att_reg_makran_pura = 1,
	att_reg_mauretania_caesarea = 1,
	att_reg_mauretania_tamousiga = 1,
	att_reg_mauretania_tingis = 2,
	att_reg_maxima_sequanorum_argentoratum = 3,
	att_reg_maxima_sequanorum_octodurus = 2,
	att_reg_maxima_sequanorum_vesontio = 1,
	att_reg_media_atropatene_ecbatana = 1,
	att_reg_media_atropatene_ganzaga = 2,
	att_reg_media_atropatene_rhaga = 3,
	att_reg_mediterraneus_occidentalis_ajax = 2,
	att_reg_mediterraneus_occidentalis_caralis = 1,
	att_reg_mediterraneus_occidentalis_palma = 3,
	att_reg_mediterraneus_orientalis_constantia = 2,
	att_reg_mediterraneus_orientalis_gortyna = 1,
	att_reg_mediterraneus_orientalis_rhodes = 3,
	att_reg_narbonensis_aquae_sextiae = 1,
	att_reg_narbonensis_narbo = 2,
	att_reg_narbonensis_vienna = 3,
	att_reg_osroene_amida = 3,
	att_reg_osroene_edessa = 1,
	att_reg_osroene_nisibis = 2,
	att_reg_palaestinea_aelia_capitolina = 3,
	att_reg_palaestinea_aila = 2,
	att_reg_palaestinea_nova_trajana_bostra = 1,
	att_reg_pannonia_savaria = 3,
	att_reg_pannonia_sirmium = 1,
	att_reg_pannonia_sopianae = 2,
	att_reg_persis_behdeshir = 3,
	att_reg_persis_siraf = 2,
	att_reg_persis_stakhr = 1,
	att_reg_phazania_cydamus = 2,
	att_reg_phazania_dimmidi = 3,
	att_reg_phazania_garama = 1,
	att_reg_raetia_et_noricum_augusta_vindelicorum = 1,
	att_reg_raetia_et_noricum_iuvavum = 2,
	att_reg_raetia_et_noricum_virunum = 3,
	att_reg_sarmatia_asiatica_anacopia = 1,
	att_reg_sarmatia_asiatica_samandar = 3,
	att_reg_sarmatia_asiatica_tanais = 2,
	att_reg_sarmatia_europaea_chersonessus = 1,
	att_reg_sarmatia_europaea_gelonus = 2,
	att_reg_sarmatia_europaea_olbia = 3,
	att_reg_scandza_alabu = 1,
	att_reg_scandza_hafn = 2,
	att_reg_scandza_hrefnesholt = 3,
	att_reg_scythia_bolghar = 2,
	att_reg_scythia_ra = 3,
	att_reg_scythia_sarai = 1,
	att_reg_spahan_issatis = 2,
	att_reg_spahan_spahan = 1,
	att_reg_spahan_susa = 3,
	att_reg_syria_antiochia = 1,
	att_reg_syria_emesa = 2,
	att_reg_syria_tyrus = 3,
	att_reg_tarraconensis_caesaraugusta = 2,
	att_reg_tarraconensis_pompaelo = 3,
	att_reg_tarraconensis_tarraco = 1,
	att_reg_terra_incognita = 1,
	att_reg_thracia_constantinopolis = 1,
	att_reg_thracia_marcianopolis = 2,
	att_reg_thracia_trimontium = 3,
	att_reg_transcarpathia_arheimar = 1,
	att_reg_transcarpathia_belz = 3,
	att_reg_transcarpathia_leopolis = 2,
	att_reg_transcaspia_dahistan = 3,
	att_reg_transcaspia_kath = 1,
	att_reg_transcaspia_siahkuh = 2,
	att_reg_tripolitana_leptis_magna = 1,
	att_reg_tripolitana_macomades = 3,
	att_reg_tripolitana_sabrata = 2,
	att_reg_venetia_aquileia = 2,
	att_reg_venetia_ravenna = 1,
	att_reg_venetia_verona = 3
};