----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------
--
-- 	MEDIEVAL KINGDOMS 1212 - COMMON LISTS
-- 	By: DETrooper
--
----------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------

REGIONS_TO_PROVINCES_LIST = {
	["mk_reg_aarhus"] = "mk_prov_alabu",
	["mk_reg_acre"] = "mk_prov_acre",
	["mk_reg_aden"] = "mk_prov_eudaemon",
	["mk_reg_agadir"] = "mk_prov_tamousiga",
	["mk_reg_ahvaz"] = "mk_prov_susa",
	["mk_reg_aix-en-provence"] = "mk_prov_aquae_sextiae",
	["mk_reg_ajaccio"] = "mk_prov_ajax",
	["mk_reg_aleppo"] = "mk_prov_aleppo",
	["mk_reg_alexandria"] = "mk_prov_alexandria",
	["mk_reg_algiers"] = "mk_prov_caesarea",
	["mk_reg_al-mahdiya"] = "mk_prov_hadrumentum",
	["mk_reg_al-rahba"] = "mk_prov_al-rahba",
	["mk_reg_al-raqqah"] = "mk_prov_edessa",
	["mk_reg_amol"] = "mk_prov_tabaristan",
	["mk_reg_ancona"] = "mk_prov_ancona",
	["mk_reg_ancyra"] = "mk_prov_ancyra",
	["mk_reg_antioch"] = "mk_prov_antiochia",
	["mk_reg_antwerp"] = "mk_prov_colonia_agrippina",
	["mk_reg_aqaba"] = "mk_prov_aila",
	["mk_reg_ardabil"] = "mk_prov_payttakaran",
	["mk_reg_arta"] = "mk_prov_epirus",
	["mk_reg_athens"] = "mk_prov_athens",
	["mk_reg_attaleia"] = "mk_prov_myra",
	["mk_reg_aydhab"] = "mk_prov_berenice",
	["mk_reg_badajoz"] = "mk_prov_emerita_augusta",
	["mk_reg_baghdad"] = "mk_prov_ctesiphon",
	["mk_reg_bahla"] = "mk_prov_omana",
	["mk_reg_baku"] = "mk_prov_gabala",
	["mk_reg_balkh"] = "mk_prov_balkh",
	["mk_reg_barca"] = "mk_prov_ptolemais",
	["mk_reg_barcelona"] = "mk_prov_tarraco",
	["mk_reg_basra"] = "mk_prov_meshan",
	["mk_reg_belgrade"] = "mk_prov_sirmium",
	["mk_reg_bergen"] = "mk_prov_bergen",
	["mk_reg_bern"] = "mk_prov_octodurus",
	["mk_reg_bilgorod"] = "mk_prov_olbia",
	["mk_reg_bilyar"] = "mk_prov_bolghar",
	["mk_reg_biskra"] = "mk_prov_dimmidi",
	["mk_reg_bologna"] = "mk_prov_ravenna",
	["mk_reg_bordeaux"] = "mk_prov_burdigala",
	["mk_reg_braga"] = "mk_prov_bracara",
	["mk_reg_brandenburg"] = "mk_prov_lupfurdum",
	["mk_reg_braunschweig"] = "mk_prov_tulifurdum",
	["mk_reg_bristol"] = "mk_prov_corinium",
	["mk_reg_bruges"] = "mk_prov_durocorterum",
	["mk_reg_bukhara"] = "mk_prov_bukhara",
	["mk_reg_burgos"] = "mk_prov_burgos",
	["mk_reg_bushehr"] = "mk_prov_siraf",
	["mk_reg_caernarvon"] = "mk_prov_segontium",
	["mk_reg_caffa"] = "mk_prov_chersonessus",
	["mk_reg_cagliari"] = "mk_prov_caralis",
	["mk_reg_cairo"] = "mk_prov_cairo",
	["mk_reg_candia"] = "mk_prov_gortyna",
	["mk_reg_cardiff"] = "mk_prov_cardiff",
	["mk_reg_chernigov"] = "mk_prov_kariskos",
	["mk_reg_colchester"] = "mk_prov_camulodunon",
	["mk_reg_constantinopolis"] = "mk_prov_constantinopolis",
	["mk_reg_cordoba"] = "mk_prov_corduba",
	["mk_reg_cork"] = "mk_prov_cork",
	["mk_reg_cyzicus"] = "mk_prov_cyzicus",
	["mk_reg_damascus"] = "mk_prov_nova_trajana_bostra",
	["mk_reg_damietta"] = "mk_prov_damietta",
	["mk_reg_daybal"] = "mk_prov_daybal",
	["mk_reg_derbent"] = "mk_prov_samandar",
	["mk_reg_dijon"] = "mk_prov_vesontio",
	["mk_reg_diyarbakir"] = "mk_prov_amida",
	["mk_reg_dongola"] = "mk_prov_pachoras",
	["mk_reg_dorylaion"] = "mk_prov_synnada",
	["mk_reg_dublin"] = "mk_prov_eblana",
	["mk_reg_dvin"] = "mk_prov_duin",
	["mk_reg_dyrrhachium"] = "mk_prov_dyrrhachium",
	["mk_reg_edinburgh"] = "mk_prov_eildon",
	["mk_reg_erbil"] = "mk_prov_arbela",
	["mk_reg_erfut"] = "mk_prov_erfut",
	["mk_reg_erzurum"] = "mk_prov_erzurum",
	["mk_reg_esztergom"] = "mk_prov_nitrahwa",
	["mk_reg_evora"] = "mk_prov_pax_augusta",
	["mk_reg_famagusta"] = "mk_prov_constantia",
	["mk_reg_fez"] = "mk_prov_fez",
	["mk_reg_frankfurt"] = "mk_prov_uburzis",
	["mk_reg_gardinas"] = "mk_prov_oium",
	["mk_reg_gdansk"] = "mk_prov_gothiscandza",
	["mk_reg_genoa"] = "mk_prov_genua",
	["mk_reg_ghazi"] = "mk_prov_ghazi",
	["mk_reg_farava"] = "mk_prov_dahistan",
	["mk_reg_granada"] = "mk_prov_granada",
	["mk_reg_graz"] = "mk_prov_virunum",
	["mk_reg_groningen"] = "mk_prov_flevum",
	["mk_reg_gyulafehervar"] = "mk_prov_apulum",
	["mk_reg_halych"] = "mk_prov_leopolis",
	["mk_reg_hamadan"] = "mk_prov_ecbatana",
	["mk_reg_saraijuq"] = "mk_prov_angulus",
	["mk_reg_heidelberg"] = "mk_prov_macomades",
	["mk_reg_herat"] = "mk_prov_harey",
	["mk_reg_homs"] = "mk_prov_emesa",
	["mk_reg_hormuz"] = "mk_prov_harmosia",
	["mk_reg_iconion"] = "mk_prov_iconium",
	["mk_reg_inverness"] = "mk_prov_tuesis",
	["mk_reg_isfahan"] = "mk_prov_spahan",
	["mk_reg_jerusalem"] = "mk_prov_aelia_capitolina",
	["mk_reg_kalmar"] = "mk_prov_kalmar",
	["mk_reg_kandahar"] = "mk_prov_kandahar",
	["mk_reg_kassa"] = "mk_prov_felvidek",
	["mk_reg_kayseri"] = "mk_prov_caesarea_eusebia",
	["mk_reg_kerak"] = "mk_prov_kerak",
	["mk_reg_kerman"] = "mk_prov_behdeshir",
	["mk_reg_kiev"] = "mk_prov_arheimar",
	["mk_reg_koln"] = "mk_prov_koln",
	["mk_reg_konigsberg"] = "mk_prov_prussia",
	["mk_reg_konstanz"] = "mk_prov_konstanz",
	["mk_reg_krakow"] = "mk_prov_belz",
	["mk_reg_kufah"] = "mk_prov_hira",
	["mk_reg_kursk"] = "mk_prov_sylis",
	["mk_reg_sukhumi"] = "mk_prov_kotais",
	["mk_reg_lalibela"] = "mk_prov_aksum",
	["mk_reg_leon"] = "mk_prov_asturica",
	["mk_reg_lisbon"] = "mk_prov_olisipo",
	["mk_reg_lodose"] = "mk_prov_hrefnesholt",
	["mk_reg_london"] = "mk_prov_londinium",
	["mk_reg_lubeck"] = "mk_prov_lubeck",
	["mk_reg_lyon"] = "mk_prov_lugdunum",
	["mk_reg_maghas"] = "mk_prov_anacopia",
	["mk_reg_malaga"] = "mk_prov_malaga",
	["mk_reg_malatya"] = "mk_prov_melitene",
	["mk_reg_maragheh"] = "mk_prov_maragheh",
	["mk_reg_marib"] = "mk_prov_zafar",
	["mk_reg_marrakech"] = "mk_prov_marrakech",
	["mk_reg_massawa"] = "mk_prov_adulis",
	["mk_reg_mecca"] = "mk_prov_yathrib",
	["mk_reg_mersa_matruh"] = "mk_prov_paraetonium",
	["mk_reg_merv"] = "mk_prov_merv",
	["mk_reg_milan"] = "mk_prov_mediolanum",
	["mk_reg_minsk"] = "mk_prov_minsk",
	["mk_reg_minya"] = "mk_prov_oxyrhynchus",
	["mk_reg_misrata"] = "mk_prov_sabrata",
	["mk_reg_montpellier"] = "mk_prov_narbo",
	["mk_reg_mosul"] = "mk_prov_nisibis",
	["mk_reg_munich"] = "mk_prov_augusta_vindelicorum",
	["mk_reg_murcia"] = "mk_prov_carthago_nova",
	["mk_reg_muscovy"] = "mk_prov_muscovy",
	["mk_reg_mystras"] = "mk_prov_corinthus",
	["mk_reg_nancy"] = "mk_prov_argentoratum",
	["mk_reg_nantes"] = "mk_prov_nantes",
	["mk_reg_naples"] = "mk_prov_neapolis",
	["mk_reg_nicaea"] = "mk_prov_nicomedia",
	["mk_reg_nis"] = "mk_prov_viminacium",
	["mk_reg_nishapur"] = "mk_prov_abarshahr",
	["mk_reg_coventry"] = "mk_prov_lindum",
	["mk_reg_novgorod"] = "mk_prov_novgorod",
	["mk_reg_nuremberg"] = "mk_prov_nuremburg",
	["mk_reg_olomouc"] = "mk_prov_olomouc",
	["mk_reg_orleans"] = "mk_prov_turonum",
	["mk_reg_oslo"] = "mk_prov_oslo",
	["mk_reg_pahrah"] = "mk_prov_pura",
	["mk_reg_palermo"] = "mk_prov_palermo",
	["mk_reg_palma"] = "mk_prov_palma",
	["mk_reg_pamplona"] = "mk_prov_pompaelo",
	["mk_reg_paris"] = "mk_prov_paris",
	["mk_reg_pecs"] = "mk_prov_sopianae",
	["mk_reg_pereyaslavl"] = "mk_prov_pereyaslavl",
	["mk_reg_philippopolis"] = "mk_prov_trimontium",
	["mk_reg_pisa"] = "mk_prov_fiorentia",
	["mk_reg_plock"] = "mk_prov_plock",
	["mk_reg_poitiers"] = "mk_prov_avaricum",
	["mk_reg_polotsk"] = "mk_prov_polotsk",
	["mk_reg_poznan"] = "mk_prov_ascaucalis",
	["mk_reg_prague"] = "mk_prov_casurgis",
	["mk_reg_pskov"] = "mk_prov_pskov",
	["mk_reg_qatif"] = "mk_prov_qatif",
	["mk_reg_qus"] = "mk_prov_qus",
	["mk_reg_qusantina"] = "mk_prov_constantina",
	["mk_reg_ras"] = "mk_prov_domavia",
	["mk_reg_ray"] = "mk_prov_rhaga",
	["mk_reg_reggio"] = "mk_prov_rhegium",
	["mk_reg_reims"] = "mk_prov_reims",
	["mk_reg_rhodes"] = "mk_prov_rhodes",
	["mk_reg_riga"] = "mk_prov_duna",
	["mk_reg_rome"] = "mk_prov_roma",
	["mk_reg_roskilde"] = "mk_prov_hafn",
	["mk_reg_rouen"] = "mk_prov_rotomagus",
	["mk_reg_ryazan"] = "mk_prov_moramar",
	["mk_reg_sale"] = "mk_prov_sale",
	["mk_reg_salzburg"] = "mk_prov_salzburg",
	["mk_reg_samarkand"] = "mk_prov_samarkand",
	["mk_reg_santiago"] = "mk_prov_brigantium",
	["mk_reg_saqsin"] = "mk_prov_sarai",
	["mk_reg_sarkel"] = "mk_prov_sarkel",
	["mk_reg_scopie"] = "mk_prov_scupi",
	["mk_reg_seville"] = "mk_prov_hispalis",
	["mk_reg_sharukan"] = "mk_prov_gelonus",
	["mk_reg_shiraz"] = "mk_prov_stakhr",
	["mk_reg_sinope"] = "mk_prov_amasea",
	["mk_reg_sis"] = "mk_prov_tarsus",
	["mk_reg_smolensk"] = "mk_prov_smolensk",
	["mk_reg_smyrna"] = "mk_prov_ephesus",
	["mk_reg_split"] = "mk_prov_salona",
	["mk_reg_sredets"] = "mk_prov_serdica",
	["mk_reg_stockholm"] = "mk_prov_stockholm",
	["mk_reg_stralsund"] = "mk_prov_rugion",
	["mk_reg_suceava"] = "mk_prov_petrodava",
	["mk_reg_burtas"] = "mk_prov_ra",
	["mk_reg_syracuse"] = "mk_prov_syracusae",
	["mk_reg_tabriz"] = "mk_prov_ganzaga",
	["mk_reg_tana"] = "mk_prov_tanais",
	["mk_reg_tangier"] = "mk_prov_tingis",
	["mk_reg_taranto"] = "mk_prov_tarentum",
	["mk_reg_targoviste"] = "mk_prov_romula",
	["mk_reg_tarnovo"] = "mk_prov_marcianopolis",
	["mk_reg_tbilisi"] = "mk_prov_mtskheta",
	["mk_reg_thessalonica"] = "mk_prov_thessalonica",
	["mk_reg_tlemcen"] = "mk_prov_tlemcen",
	["mk_reg_toledo"] = "mk_prov_toletum",
	["mk_reg_toulouse"] = "mk_prov_elusa",
	["mk_reg_trebizond"] = "mk_prov_trapezus",
	["mk_reg_trier"] = "mk_prov_augusta_treverorum",
	["mk_reg_tripoli_levant"] = "mk_prov_tyrus",
	["mk_reg_tripoli_libya"] = "mk_prov_leptis_magna",
	["mk_reg_tunis"] = "mk_prov_carthago",
	["mk_reg_turin"] = "mk_prov_segusio",
	["mk_reg_tver"] = "mk_prov_tver",
	["mk_reg_urgench"] = "mk_prov_kath",
	["mk_reg_valencia"] = "mk_prov_segobriga",
	["mk_reg_van"] = "mk_prov_tosp",
	["mk_reg_varad"] = "mk_prov_savaria",
	["mk_reg_varna"] = "mk_prov_varna",
	["mk_reg_venice"] = "mk_prov_aquileia",
	["mk_reg_verona"] = "mk_prov_verona",
	["mk_reg_vienna"] = "mk_prov_iuvavum",
	["mk_reg_vienne"] = "mk_prov_vienna",
	["mk_reg_vilnius"] = "mk_prov_palteskja",
	["mk_reg_visby"] = "mk_prov_gotland",
	["mk_reg_visoko"] = "mk_prov_visoko",
	["mk_reg_vladimir"] = "mk_prov_vladimir",
	["mk_reg_volodymyr"] = "mk_prov_volodymyr",
	["mk_reg_wittenberg"] = "mk_prov_aregelia",
	["mk_reg_wroclaw"] = "mk_prov_budorgis",
	["mk_reg_yaroslavl"] = "mk_prov_yaroslavl",
	["mk_reg_yazd"] = "mk_prov_issatis",
	["mk_reg_york"] = "mk_prov_eboracum",
	["mk_reg_zagreb"] = "mk_prov_siscia",
	["mk_reg_zaragoza"] = "mk_prov_caesaraugusta",
	["mk_reg_zaranj"] = "mk_prov_phra",
	["mk_reg_zeila"] = "mk_prov_zeila"
};

SEPARATIST_FACTION_REBELLION_UNITS = {
	["mk_fact_separatists_abbasid"] = {
		"mk_abb_t1_awam_rumat",
		"mk_abb_t1_ayyar",
		"mk_abb_t1_bedouin_lancers",
		"mk_abb_t1_dariyyah_ghulam_horse_archers",
		"mk_abb_t1_dismounted_ghulam",
		"mk_abb_t1_fursan_akrad",
		"mk_abb_t1_fursan_iqtaiyyah",
		"mk_abb_t1_futuwwa",
		"mk_abb_t1_futuwwa_jund",
		"mk_abb_t1_jund_crossbowmen",
		"mk_abb_t1_jund_rajilah",
		"mk_abb_t1_jund_rumat",
		"mk_abb_t1_mounted_crossbowmen",
		"mk_abb_t1_naffatun",
		"mk_abb_t1_turcoman_jarida",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_alania"] = {
		"mk_cuman_t1_heavy_HA",
		"mk_cuman_t1_heavy_lancers",
		"mk_cuman_t1_infantry",
		"mk_cuman_t1_light_HA",
		"mk_cuman_t1_light_archers",
		"mk_cuman_t1_light_lancers",
		"mk_cuman_t1_macemen",
		"mk_cuman_t1_medium_archers",
		"mk_cuman_t1_nogers",
		"mk_cuman_t1_skirmisher_cavalry",
		"mk_cuman_t1_skirmishers",
		"mk_cuman_t1_spearmen",
		"mk_cuman_t1_subject_cavalry",
		"mk_cuman_t1_tribal_HA",
		"mk_cuman_t1_uzdens",
		"mk_mon_t1_catapult",
	},
	["mk_fact_separatists_almohads"] = {
		"mk_alm_t1_abid_al_makhzan",
		"mk_alm_t1_abid_infantry",
		"mk_alm_t1_abid_skirmishers",
		"mk_alm_t1_arab_cavalry",
		"mk_alm_t1_berber_horsemen",
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_huffaz",
		"mk_alm_t1_hushud",
		"mk_alm_t1_hushud_rumat",
		"mk_alm_t1_jund_swordsmen",
		"mk_alm_t1_maghrebi_rumat",
		"mk_alm_t1_maghrebi_tribesmen",
		"mk_alm_t1_mounted_abid_al_makhzan",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_nobat_al_djandariya",
		"mk_alm_t1_slinger",
		"mk_mar_t1_humah_watanihi",
		"mk_mar_t1_zenata_skirmish_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_andalusian"] = {
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_ghuzz_horse_archers",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_slinger",
		"mk_gran_t1_andalusian_crossbowmen",
		"mk_gran_t1_andalusian_jund",
		"mk_gran_t1_andalusian_mounted_crossbowmen",
		"mk_gran_t1_asnaf_al_berber",
		"mk_gran_t1_granadine_knights",
		"mk_gran_t1_granadine_rais",
		"mk_gran_t1_granadine_spear_cavalry",
		"mk_gran_t1_heavy_andalusian_crossbowmen",
		"mk_gran_t1_hushud_rumat",
		"mk_gran_t1_jund_al_nasara",
		"mk_gran_t1_jundi_mutadawwan",
		"mk_gran_t1_maghrebi_tribesmen",
		"mk_gran_t1_mozarab_jund",
		"mk_gran_t1_muwalladun_cavalry",
		"mk_gran_t1_muwalladun_jund",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_antioch"] = {
		"mk_ant_t1_crossbowmen",
		"mk_ant_t1_knights",
		"mk_ant_t1_sergeants_mounted",
		"mk_ant_t1_spearmen",
		"mk_ant_t1_syriac_archers",
		"mk_eur_t1_catapult",
		"mk_mio_t1_hospitaller_knights",
		"mk_mio_t1_hospitaller_mounted_sergeants",
		"mk_mio_t1_hospitaller_sergeant_spearmen",
		"mk_mio_t1_templar_knights",
		"mk_mio_t1_templar_mounted_sergeants",
		"mk_mio_t1_templar_sergeant_spearmen",
	},
	["mk_fact_separatists_aragon"] = {
		"mk_ara_t1_almogavars",
		"mk_ara_t1_caballeros",
		"mk_ara_t1_caballeros_villanos",
		"mk_ara_t1_fidalgos",
		"mk_ara_t1_jinetes",
		"mk_ara_t1_militia_crossbowmen",
		"mk_ara_t1_militia_spearmen",
		"mk_ara_t1_mounted_crossbowmen",
		"mk_ara_t1_peones",
		"mk_ara_t1_peones_crossbowmen",
		"mk_ara_t1_peones_spearmen",
		"mk_ara_t1_pikemen",
		"mk_ara_t1_sergeant_crossbowmen",
		"mk_ara_t1_slingers",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_armenia"] = {
		"mk_arm_t1_archer_dziaworner",
		"mk_arm_t1_archer_serzhantner",
		"mk_arm_t1_aspatakner",
		"mk_arm_t1_aspetner",
		"mk_arm_t1_bardzraharker",
		"mk_arm_t1_bardzravandak_skirmishers",
		"mk_arm_t1_bourdjes_archers",
		"mk_arm_t1_bourdjes_militia",
		"mk_arm_t1_cilician_levies",
		"mk_arm_t1_dziaworner",
		"mk_arm_t1_foot_serzhantner",
		"mk_arm_t1_serzhantner",
		"mk_arm_t1_spear_serzhantner",
		"mk_arm_t1_turcopoles",
		"mk_byz_t1_catapult",
	},
	["mk_fact_separatists_austria"] = {
		"mk_aus_t1_armbrustschutzen_crossbow",
		"mk_aus_t1_bogner_archer",
		"mk_aus_t1_burgerwehr_spearmen",
		"mk_aus_t1_fussknecht_spearmen",
		"mk_aus_t1_fussknechte_halberdiers",
		"mk_aus_t1_konstafler",
		"mk_aus_t1_landsturm_crossbowmen",
		"mk_aus_t1_landsturm_spearmen",
		"mk_aus_t1_mounted_crossbowmen",
		"mk_aus_t1_mounted_sarianten",
		"mk_aus_t1_ritter",
		"mk_aus_t1_schutzen_crossbowmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_ayyubids"] = {
		"mk_ayy_t1_ahdath",
		"mk_ayy_t1_ahdath_archers",
		"mk_ayy_t1_ajnad_cavalry",
		"mk_ayy_t1_askari_cavalry",
		"mk_ayy_t1_askari_nobles",
		"mk_ayy_t1_beduin_camel_riders",
		"mk_ayy_t1_crossbowmen",
		"mk_ayy_t1_harafisha_infantry",
		"mk_ayy_t1_jaridah_cav",
		"mk_ayy_t1_jund_spearmen",
		"mk_ayy_t1_jund_swordsmen",
		"mk_ayy_t1_naffatun",
		"mk_ayy_t1_nubian_spearmen",
		"mk_ayy_t1_shujan",
		"mk_ayy_t1_sudanese_archers",
		"mk_ayy_t1_tawashi",
		"mk_ayy_t1_thaqlah_axemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_bohemia"] = {
		"mk_boh_t1_chod_frontiersmen",
		"mk_boh_t1_crossbowmen",
		"mk_boh_t1_king_bodyguard",
		"mk_boh_t1_knights",
		"mk_boh_t1_militia_archers",
		"mk_boh_t1_mounted_raiders",
		"mk_boh_t1_mounted_sergeants",
		"mk_boh_t1_pacholek_spearmen",
		"mk_boh_t1_peasant_archers",
		"mk_boh_t1_sergeant_spearmen",
		"mk_boh_t1_sergeants",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_bologna"] = {
		"mk_eur_t1_catapult",
		"mk_mil_t1_archer_militia",
		"mk_mil_t1_archers",
		"mk_mil_t1_berrovieri",
		"mk_mil_t1_crossbowmen",
		"mk_mil_t1_foot_berrovieri",
		"mk_mil_t1_knights",
		"mk_mil_t1_light_cav",
		"mk_mil_t1_militia_crossbowmen",
		"mk_mil_t1_militia_spearmen",
		"mk_mil_t1_militia_swordsmen",
		"mk_mil_t1_mounted_crossbowmen",
		"mk_mil_t1_mounted_serjeants",
		"mk_mil_t1_spearmen",
		"mk_mil_t1_swordsmen",
	},
	["mk_fact_separatists_brabant"] = {
		"mk_brab_t1_crossbowmen",
		"mk_brab_t1_dismounted_knights",
		"mk_brab_t1_goedendag_militia",
		"mk_brab_t1_guisarmiers",
		"mk_brab_t1_knights",
		"mk_brab_t1_levy_archer",
		"mk_brab_t1_militia_spearmen",
		"mk_brab_t1_militia_swordsmen",
		"mk_brab_t1_mounted_crossbowmen",
		"mk_brab_t1_mounted_sergeants",
		"mk_brab_t1_pikemen",
		"mk_brab_t1_sergeants",
		"mk_brab_t1_spearmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_britons"] = {
		"mk_wel_t1_dismounted_uchelwyr",
		"mk_wel_t1_hobilar",
		"mk_wel_t1_rhyfelwyr",
		"mk_wel_t1_saethwyr",
		"mk_wel_t1_schiltron_spearmen",
		"mk_wel_t1_spear_band",
		"mk_wel_t1_spearmen",
		"mk_wel_t1_teulu_saethwyr",
		"mk_wel_t1_uchelwyr",
		"mk_wel_t1_ysbeilwyr",
	},
	["mk_fact_separatists_bulgaria"] = {
		"mk_bulg_t1_archers",
		"mk_bulg_t1_axemen_dogs",
		"mk_bulg_t1_bolyars",
		"mk_bulg_t1_cavalry",
		"mk_bulg_t1_heavy_cavalry",
		"mk_bulg_t1_heavy_spearmen",
		"mk_bulg_t1_hooked_pikemen",
		"mk_bulg_t1_levy_spearmen",
		"mk_bulg_t1_militia_archers",
		"mk_bulg_t1_militia_spearmen",
		"mk_bulg_t1_slav_aux_javelinmen",
		"mk_bulg_t1_voivods",
		"mk_byz_t1_catapult",
	},
	["mk_fact_separatists_burgundy"] = {
		"mk_bur_t1_axe_sergeants",
		"mk_bur_t1_chevaliers",
		"mk_bur_t1_crossbowmen",
		"mk_bur_t1_dismounted_chevaliers",
		"mk_bur_t1_guisarmiers",
		"mk_bur_t1_levy_archers",
		"mk_bur_t1_levy_crossbowmen",
		"mk_bur_t1_levy_guisarmiers",
		"mk_bur_t1_mounted_crossbowmen",
		"mk_bur_t1_mounted_serjeants",
		"mk_bur_t1_scouts",
		"mk_bur_t1_sergeants",
		"mk_bur_t1_spear_militia",
		"mk_bur_t1_spearmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_castile"] = {
		"mk_cas_t1_almogavar_scouts",
		"mk_cas_t1_almogavars",
		"mk_cas_t1_caballeros",
		"mk_cas_t1_crossbow_militia",
		"mk_cas_t1_crossbowmen",
		"mk_cas_t1_hidalgos",
		"mk_cas_t1_jinetes",
		"mk_cas_t1_mounted_crossbowmen",
		"mk_cas_t1_peones",
		"mk_cas_t1_peones_crossbowmen",
		"mk_cas_t1_peones_spearmen",
		"mk_cas_t1_slingers",
		"mk_cas_t1_spear_militia",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_croatia"] = {
		"mk_croat_T1_archers",
		"mk_croat_T1_cavalry",
		"mk_croat_T1_communal_militia",
		"mk_croat_T1_communal_noble_infantry",
		"mk_croat_T1_crossbowmen",
		"mk_croat_T1_javelin_sailors",
		"mk_croat_T1_knight",
		"mk_croat_T1_militia_crossbowmen",
		"mk_croat_T1_spearmen",
		"mk_croat_T1_swordsmen",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_cumans"] = {
		"mk_cuman_t1_heavy_HA",
		"mk_cuman_t1_heavy_lancers",
		"mk_cuman_t1_infantry",
		"mk_cuman_t1_light_HA",
		"mk_cuman_t1_light_archers",
		"mk_cuman_t1_light_lancers",
		"mk_cuman_t1_macemen",
		"mk_cuman_t1_medium_archers",
		"mk_cuman_t1_nogers",
		"mk_cuman_t1_skirmisher_cavalry",
		"mk_cuman_t1_skirmishers",
		"mk_cuman_t1_spearmen",
		"mk_cuman_t1_subject_cavalry",
		"mk_cuman_t1_tribal_HA",
		"mk_cuman_t1_uzdens",
		"mk_mon_t1_catapult",
	},
	["mk_fact_separatists_denmark"] = {
		"mk_dan_t1_axe_bondir",
		"mk_dan_t1_bondir_spear",
		"mk_dan_t1_bow_bondir",
		"mk_dan_t1_crossbowmen",
		"mk_dan_t1_huskarls",
		"mk_dan_t1_huskarls_spear",
		"mk_dan_t1_knights",
		"mk_dan_t1_landevaern_infantry",
		"mk_dan_t1_landevaern_spearmen",
		"mk_dan_t1_longbowmen",
		"mk_dan_t1_scouts",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_epirus"] = {
		 "mk_byz_t1_catapult",
		 "mk_epirus_t1_epirus_epirote_guard",
		 "mk_epirus_t1_heavy_archers",
		 "mk_epirus_t1_kavallarioi",
		 "mk_epirus_t1_militia_spearmen",
		 "mk_epirus_t1_scoutatoi",
		 "mk_epirus_t1_scouts",
		 "mk_epirus_t1_skirmishers",
		 "mk_epirus_t1_swordsmen",
	},
	["mk_fact_separatists_flanders"] = {
		"mk_fla_t1_crossbowmen",
		"mk_fla_t1_falchion_swordsmen",
		"mk_fla_t1_goedendags",
		"mk_fla_t1_knights",
		"mk_fla_t1_maa",
		"mk_fla_t1_mounted_sergeants",
		"mk_fla_t1_pikemen",
		"mk_fla_t1_sergeants",
		"mk_fla_t1_spearmen",
		"mk_fla_t1_swordsmen",
	},
	["mk_fact_separatists_france"] = {
		"mk_eur_t1_catapult",
		"mk_fre_t1_arbaletriers",
		"mk_fre_t1_arbaletriers_mounted",
		"mk_fre_t1_archers",
		"mk_fre_t1_chevaliers_mounted",
		"mk_fre_t1_cliens",
		"mk_fre_t1_guisarmiers",
		"mk_fre_t1_levy_crossbowmen",
		"mk_fre_t1_levy_spearmen",
		"mk_fre_t1_mounted_sergeants",
		"mk_fre_t1_piquichins",
		"mk_fre_t1_ribauds",
		"mk_fre_t1_sergeant_axemen",
		"mk_fre_t1_sergeants",
	},
	["mk_fact_separatists_frankish"] = {
		"mk_eur_t1_catapult",
		"mk_lat_t1_bow_militia",
		"mk_lat_t1_chevaliers",
		"mk_lat_t1_crossbow_militia",
		"mk_lat_t1_crossbowmen",
		"mk_lat_t1_mounted_crossbowmen",
		"mk_lat_t1_mounted_sergeants",
		"mk_lat_t1_pikemen",
		"mk_lat_t1_sergeants",
		"mk_lat_t1_spear_militia",
	},
	["mk_fact_separatists_french"] = {
		"mk_eur_t1_catapult",
		"mk_fre_t1_arbaletriers",
		"mk_fre_t1_arbaletriers_mounted",
		"mk_fre_t1_archers",
		"mk_fre_t1_chevaliers_mounted",
		"mk_fre_t1_cliens",
		"mk_fre_t1_guisarmiers",
		"mk_fre_t1_levy_crossbowmen",
		"mk_fre_t1_levy_spearmen",
		"mk_fre_t1_mounted_sergeants",
		"mk_fre_t1_piquichins",
		"mk_fre_t1_ribauds",
		"mk_fre_t1_sergeant_axemen",
		"mk_fre_t1_sergeants",
	},
	["mk_fact_separatists_genoa"] = {
		"mk_eur_t1_catapult",
		"mk_gen_t1_archers",
		"mk_gen_t1_berrovieri",
		"mk_gen_t1_crossbowmen",
		"mk_gen_t1_foot_berrovieri",
		"mk_gen_t1_guelph_maa",
		"mk_gen_t1_guelph_mounted_maa",
		"mk_gen_t1_knights",
		"mk_gen_t1_light_cav",
		"mk_gen_t1_militia_archer",
		"mk_gen_t1_militia_crossbowmen",
		"mk_gen_t1_militia_spearmen",
		"mk_gen_t1_militia_swordmen",
		"mk_gen_t1_mounted_crossbowmen",
		"mk_gen_t1_spearmen",
		"mk_gen_t1_swordmen",
	},
	["mk_fact_separatists_georgia"] = {
		"mk_byz_t1_catapult",
		"mk_georg_t1_aznauri_lancers",
		"mk_georg_t1_aznauri_swordsmen",
		"mk_georg_t1_dismounted_monaspa_archers",
		"mk_georg_t1_kartlian_spearmen",
		"mk_georg_t1_khevsur_swordsmen",
		"mk_georg_t1_metsikhovne_archers",
		"mk_georg_t1_metsikhovne_spearmen",
		"mk_georg_t1_monaspa_lancers",
		"mk_georg_t1_msakhureuli_cavalry",
		"mk_georg_t1_shubosani_molashqre",
		"mk_georg_t1_svanian_crossbowmen",
		"mk_georg_t1_svanian_hunters",
		"mk_georg_t1_svanian_spearmen",
	},
	["mk_fact_separatists_german"] = {
		"mk_eur_t1_catapult",
		"mk_ger_t1_archers",
		"mk_ger_t1_axe_sergeants",
		"mk_ger_t1_emperor_bodyguard",
		"mk_ger_t1_knights",
		"mk_ger_t1_militia_crossbowmen",
		"mk_ger_t1_mounted_crossbowmen",
		"mk_ger_t1_mounted_sergeants",
		"mk_ger_t1_pikemen",
		"mk_ger_t1_sergeant_crossbowmen",
		"mk_ger_t1_sergeant_spearmen",
		"mk_ger_t1_sergeants",
		"mk_ger_t1_urban_militia_axe",
	},
	["mk_fact_separatists_ghurid"] = {
		"mk_ghu_t1_afghan_archers",
		"mk_ghu_t1_afghan_spearmen",
		"mk_ghu_t1_ghori_infantry",
		"mk_ghu_t1_ghori_maliks",
		"mk_ghu_t1_ghori_tribesmen",
		"mk_ghu_t1_ghulam_lancers",
		"mk_ghu_t1_ghulaman",
		"mk_ghu_t1_ghuzz_mercenaries",
		"mk_ghu_t1_indian_elephants",
		"mk_ghu_t1_khalaj_cavalry",
		"mk_ghu_t1_naphta_throwers",
		"mk_ghu_t1_nawak_infantry",
		"mk_ghu_t1_sawar-i_barahna_wa-jarida",
		"mk_ghu_t1_tajik_levy",
		"mk_ghu_t1_zupin_javelinmen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_goldenhorde"] = {
		"mk_mon_t1_catapult",
		"mk_mon_t1_fire_lance_infantry",
		"mk_mon_t1_golden_hashar_levy",
		"mk_mon_t1_golden_heavy_horse_archers",
		"mk_mon_t1_golden_heavy_lancers",
		"mk_mon_t1_golden_horse_archers",
		"mk_mon_t1_golden_kharash",
		"mk_mon_t1_golden_lancers",
		"mk_mon_t1_golden_rus_archers",
		"mk_mon_t1_golden_tserig_spearmen",
		"mk_mon_t1_golden_turk_heavy_horse_archers",
		"mk_mon_t1_ilkhan_turkic_archers",
	},
	["mk_fact_separatists_hafsids"] = {
		"mk_alm_t1_abid_al_makhzan",
		"mk_alm_t1_abid_infantry",
		"mk_alm_t1_abid_skirmishers",
		"mk_alm_t1_berber_horsemen",
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_hushud",
		"mk_alm_t1_hushud_rumat",
		"mk_alm_t1_jund_al_nasara",
		"mk_alm_t1_jund_swordsmen",
		"mk_alm_t1_maghrebi_rumat",
		"mk_alm_t1_maghrebi_tribesmen",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_slinger",
		"mk_haf_t1_ifriqyan_cavalry",
		"mk_haf_t1_irban",
		"mk_haf_t1_kabyle_tribal_horsemen",
		"mk_haf_t1_mashshain",
		"mk_mar_t1_mizwar_noble_horsemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_hre"] = {
		"mk_eur_t1_catapult",
		"mk_ger_t1_archers",
		"mk_ger_t1_axe_sergeants",
		"mk_ger_t1_emperor_bodyguard",
		"mk_ger_t1_knights",
		"mk_ger_t1_militia_crossbowmen",
		"mk_ger_t1_mounted_crossbowmen",
		"mk_ger_t1_mounted_sergeants",
		"mk_ger_t1_pikemen",
		"mk_ger_t1_sergeant_crossbowmen",
		"mk_ger_t1_sergeant_spearmen",
		"mk_ger_t1_sergeants",
		"mk_ger_t1_urban_militia_axe",
	},
	["mk_fact_separatists_hungary"] = {
		"mk_eur_t1_catapult",
		"mk_hun_t1_HA",
		"mk_hun_t1_crossbowmen",
		"mk_hun_t1_knight",
		"mk_hun_t1_light_lancer",
		"mk_hun_t1_militia_crossbowmen",
		"mk_hun_t1_militia_spear",
		"mk_hun_t1_royal_warriors",
		"mk_hun_t1_spearmen",
		"mk_hun_t1_sword",
		"mk_hun_t1_szekely_HA",
	},
	["mk_fact_separatists_iberian"] = {
		"mk_cas_t1_almogavar_scouts",
		"mk_cas_t1_almogavars",
		"mk_cas_t1_caballeros",
		"mk_cas_t1_crossbow_militia",
		"mk_cas_t1_crossbowmen",
		"mk_cas_t1_hidalgos",
		"mk_cas_t1_jinetes",
		"mk_cas_t1_mounted_crossbowmen",
		"mk_cas_t1_peones",
		"mk_cas_t1_peones_crossbowmen",
		"mk_cas_t1_peones_spearmen",
		"mk_cas_t1_slingers",
		"mk_cas_t1_spear_militia",
		"mk_eur_t1_catapult",
	},
	["mk_fact_separatists_ildegizids"] = {
		"mk_ata_t1_askari",
		"mk_ata_t1_ghazi_cavalry",
		"mk_ata_t1_tribesmen",
		"mk_aze_t1_azerbaijani_infantry",
		"mk_aze_t1_azerbaijani_savaran",
		"mk_aze_t1_highland_slingers",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_ilkhanate"] = {
		"mk_mon_t1_catapult",
		"mk_mon_t1_fire_lance_infantry",
		"mk_mon_t1_ilkhan_heavy_horse_archers",
		"mk_mon_t1_ilkhan_heavy_lancers",
		"mk_mon_t1_ilkhan_horse_archers",
		"mk_mon_t1_ilkhan_kharash",
		"mk_mon_t1_ilkhan_lancers",
		"mk_mon_t1_ilkhan_qaraghul",
		"mk_mon_t1_ilkhan_turkic_archers",
		"mk_mon_t1_tammas",
	},
	["mk_fact_separatists_iran"] = {
		"mk_ghu_t1_indian_elephants",
		"mk_khw_t1_askari",
		"mk_khw_t1_camel_cavalry",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_khwarazmian_cavalry",
		"mk_khw_t1_khwarazmian_lancers",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_savaran",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_ireland"] = {
		"mk_eur_t1_catapult",
		"mk_sco_t1_ettrick_archers",
		"mk_sco_t1_highlanders",
		"mk_sco_t1_hobilars",
		"mk_sco_t1_knights",
		"mk_sco_t1_longbow_militia",
		"mk_sco_t1_pikemen",
		"mk_sco_t1_sergeants",
	},
	["mk_fact_separatists_jerusalem"] = {
		"mk_eur_t1_catapult",
		"mk_jer_t1_maronite_skirmishers",
		"mk_jer_t1_maronite_spearmen",
		"mk_jer_t1_poulain_crossbowmen",
		"mk_jer_t1_poulain_knights",
		"mk_jer_t1_poulain_knights_dismounted",
		"mk_jer_t1_syriac_crossbowmen",
		"mk_jer_t1_turcopoles",
		"mk_mio_t1_hospitaller_knights",
		"mk_mio_t1_hospitaller_mounted_sergeants",
		"mk_mio_t1_hospitaller_sergeant_spearmen",
		"mk_mio_t1_templar_knights",
		"mk_mio_t1_templar_mounted_sergeants",
		"mk_mio_t1_templar_sergeant_spearmen",
	},
	["mk_fact_separatists_khwarazm"] = {
		"mk_ghu_t1_indian_elephants",
		"mk_khw_t1_askari",
		"mk_khw_t1_camel_cavalry",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_khwarazmian_cavalry",
		"mk_khw_t1_khwarazmian_lancers",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_savaran",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_kiev"] = {
		"mk_rus_t1_catapult",
		"mk_rus_t1_dismounted_druzina",
		"mk_rus_t1_druzina",
		"mk_rus_t1_guard_axemen",
		"mk_rus_t1_javelinmen",
		"mk_rus_t1_militia_archers",
		"mk_rus_t1_militia_heavy_spearmen",
		"mk_rus_t1_militia_infantry",
		"mk_rus_t1_militia_spearmen",
		"mk_rus_t1_senior_druzina",
		"mk_rus_t1_spearmen",
		"mk_rus_t1_swordsmen",
	},
	["mk_fact_separatists_latinempire"] = {
		"mk_eur_t1_catapult",
		"mk_lat_t1_bow_militia",
		"mk_lat_t1_chevaliers",
		"mk_lat_t1_crossbow_militia",
		"mk_lat_t1_crossbowmen",
		"mk_lat_t1_mounted_crossbowmen",
		"mk_lat_t1_mounted_sergeants",
		"mk_lat_t1_pikemen",
		"mk_lat_t1_sergeants",
		"mk_lat_t1_spear_militia",
	},
	["mk_fact_separatists_lesserpoland"] = {
		"mk_eur_t1_catapult",
		"mk_pol_t1_archers_lesser_poland",
		"mk_pol_t1_axemen_lesser_poland",
		"mk_pol_t1_knight_lesser_poland",
		"mk_pol_t1_militia_crossbowmen",
		"mk_pol_t1_militia_spearmen",
		"mk_pol_t1_mounted_crossbowmen",
		"mk_pol_t1_mounted_sergeants",
		"mk_pol_t1_sergeant_crossbowmen_lesser_poland",
		"mk_pol_t1_sergeant_spearmen",
		"mk_pol_t1_sergeants",
	},
	["mk_fact_separatists_lithuania"] = {
		"mk_lit_t1_axemen",
		"mk_lit_t1_boyars",
		"mk_lit_t1_ducal_axemen",
		"mk_lit_t1_ducal_spearmen",
		"mk_lit_t1_lithuanian_skirmishers",
		"mk_lit_t1_militia_crossbowmen",
		"mk_lit_t1_militia_spearmen",
		"mk_lit_t1_noble_cavalry",
		"mk_lit_t1_noble_swordsmen",
		"mk_lit_t1_ruthenian_archers",
		"mk_lit_t1_skirmisher_cavalry",
		"mk_rus_t1_catapult",
	},
	["mk_fact_separatists_lombards"] = {
		"mk_eur_t1_catapult",
		"mk_mil_t1_archer_militia",
		"mk_mil_t1_archers",
		"mk_mil_t1_berrovieri",
		"mk_mil_t1_crossbowmen",
		"mk_mil_t1_foot_berrovieri",
		"mk_mil_t1_knights",
		"mk_mil_t1_light_cav",
		"mk_mil_t1_militia_crossbowmen",
		"mk_mil_t1_militia_spearmen",
		"mk_mil_t1_militia_swordsmen",
		"mk_mil_t1_mounted_crossbowmen",
		"mk_mil_t1_mounted_serjeants",
		"mk_mil_t1_spearmen",
		"mk_mil_t1_swordsmen",
	},
	["mk_fact_separatists_lorraine"] = {
		"mk_eur_t1_catapult",
		"mk_lor_t1_axemen",
		"mk_lor_t1_chevaliers",
		"mk_lor_t1_coutiliers",
		"mk_lor_t1_crossbowmen",
		"mk_lor_t1_horsemen",
		"mk_lor_t1_jager_crossbowmen",
		"mk_lor_t1_pikes",
		"mk_lor_t1_scouts",
		"mk_lor_t1_spearmen",
		"mk_lor_t1_swordsmen",
		"mk_lor_t1_urban_militia",
	},
	["mk_fact_separatists_makuria"] = {
		"mk_mak_t1_alodian_horsemen",
		"mk_mak_t1_arab_horsemen",
		"mk_mak_t1_arab_infantry",
		"mk_mak_t1_beja_bowmen",
		"mk_mak_t1_beja_camelry",
		"mk_mak_t1_beja_tribesmen",
		"mk_mak_t1_bukna_warband",
		"mk_mak_t1_frontier_guardsmen",
		"mk_mak_t1_nubian_archers",
		"mk_mak_t1_nubian_knights",
		"mk_mak_t1_nubian_light_cavalry",
		"mk_mak_t1_nubian_quilted_infantry",
		"mk_mak_t1_nubian_slingers",
		"mk_mak_t1_nubian_spearmen",
		"mk_mak_t1_sudanese_sheikhs",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_marinids"] = {
		"mk_alm_t1_abid_infantry",
		"mk_alm_t1_abid_skirmishers",
		"mk_alm_t1_arab_cavalry",
		"mk_alm_t1_ghuzat",
		"mk_alm_t1_ghuzz_horse_archers",
		"mk_alm_t1_hushud",
		"mk_alm_t1_hushud_rumat",
		"mk_alm_t1_jund_al_nasara",
		"mk_alm_t1_jund_swordsmen",
		"mk_alm_t1_maghrebi_rumat",
		"mk_alm_t1_mutatawiah",
		"mk_alm_t1_saqaliba_jund",
		"mk_alm_t1_slinger",
		"mk_mar_t1_beni_merin_lancers",
		"mk_mar_t1_humah_watanihi",
		"mk_mar_t1_mizwar_noble_horsemen",
		"mk_mar_t1_zanata_skirmishers",
		"mk_mar_t1_zenata_skirmish_cavalry",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_mecca"] = {
		"mk_ayy_t1_ahdath",
		"mk_ayy_t1_ahdath_archers",
		"mk_ayy_t1_ajnad_cavalry",
		"mk_ayy_t1_askari_cavalry",
		"mk_ayy_t1_askari_nobles",
		"mk_ayy_t1_beduin_camel_riders",
		"mk_ayy_t1_crossbowmen",
		"mk_ayy_t1_harafisha_infantry",
		"mk_ayy_t1_jaridah_cav",
		"mk_ayy_t1_jund_spearmen",
		"mk_ayy_t1_jund_swordsmen",
		"mk_ayy_t1_naffatun",
		"mk_ayy_t1_nubian_spearmen",
		"mk_ayy_t1_shujan",
		"mk_ayy_t1_sudanese_archers",
		"mk_ayy_t1_tawashi",
		"mk_ayy_t1_thaqlah_axemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_milan"] = {
		"mk_eur_t1_catapult",
		"mk_mil_t1_archer_militia",
		"mk_mil_t1_archers",
		"mk_mil_t1_berrovieri",
		"mk_mil_t1_crossbowmen",
		"mk_mil_t1_foot_berrovieri",
		"mk_mil_t1_knights",
		"mk_mil_t1_light_cav",
		"mk_mil_t1_militia_crossbowmen",
		"mk_mil_t1_militia_spearmen",
		"mk_mil_t1_militia_swordsmen",
		"mk_mil_t1_mounted_crossbowmen",
		"mk_mil_t1_mounted_serjeants",
		"mk_mil_t1_spearmen",
		"mk_mil_t1_swordsmen",
	},
	["mk_fact_separatists_navarre"] = {
		"mk_eur_t1_catapult",
		"mk_nav_t1_caballeros",
		"mk_nav_t1_caballeros_spearmen",
		"mk_nav_t1_dismounted_hidalgos",
		"mk_nav_t1_hidalgos",
		"mk_nav_t1_militia_archers",
		"mk_nav_t1_militia_crossbowmen",
		"mk_nav_t1_militia_spearmen",
		"mk_nav_t1_peones",
		"mk_nav_t1_peones_spearmen",
		"mk_nav_t1_piquieros",
		"mk_nav_t1_slingers",
		"mk_nav_t1_vasque_skirmisher_cavalry",
		"mk_nav_t1_vasque_skirmishers",
	},
	["mk_fact_separatists_nicaea"] = {
		"mk_byz_t1_cataphractoi",
		"mk_byz_t1_catapult",
		"mk_byz_t1_gasmouloi",
		"mk_byz_t1_kavallarioi",
		"mk_byz_t1_kontaratoi",
		"mk_byz_t1_latinikon",
		"mk_byz_t1_militia_spearmen",
		"mk_byz_t1_mourtatoi",
		"mk_byz_t1_peltastoi",
		"mk_byz_t1_pronoiaroi",
		"mk_byz_t1_scoutatoi",
		"mk_byz_t1_scoutatoi_swordsmen",
		"mk_byz_t1_turcoman_HA",
	},
	["mk_fact_separatists_norway"] = {
		"mk_eur_t1_catapult",
		"mk_nor_t1_atgeir_bondir",
		"mk_nor_t1_bondir",
		"mk_nor_t1_bow_bondir",
		"mk_nor_t1_candle_men",
		"mk_nor_t1_crossbow_hirdmen",
		"mk_nor_t1_guest",
		"mk_nor_t1_hirdmen",
		"mk_nor_t1_knekts",
		"mk_nor_t1_orkney",
		"mk_nor_t1_riddere",
		"mk_nor_t1_spear_bondir",
		"mk_nor_t1_tablemen",
	},
	["mk_fact_separatists_oman"] = {
		"mk_ayy_t1_ahdath",
		"mk_ayy_t1_ahdath_archers",
		"mk_ayy_t1_ajnad_cavalry",
		"mk_ayy_t1_askari_cavalry",
		"mk_ayy_t1_askari_nobles",
		"mk_ayy_t1_beduin_camel_riders",
		"mk_ayy_t1_crossbowmen",
		"mk_ayy_t1_harafisha_infantry",
		"mk_ayy_t1_jaridah_cav",
		"mk_ayy_t1_jund_spearmen",
		"mk_ayy_t1_jund_swordsmen",
		"mk_ayy_t1_naffatun",
		"mk_ayy_t1_nubian_spearmen",
		"mk_ayy_t1_shujan",
		"mk_ayy_t1_sudanese_archers",
		"mk_ayy_t1_tawashi",
		"mk_ayy_t1_thaqlah_axemen",
		"mk_mus_t1_catapult",
	},
	["mk_fact_separatists_papacy"] = {
		"mk_eur_t1_catapult",
		"mk_pap_t1_archer_militia",
		"mk_pap_t1_archers",
		"mk_pap_t1_berrovieri",
		"mk_pap_t1_crossbow_militia",
		"mk_pap_t1_crossbowmen",
		"mk_pap_t1_foot_berrovieri",
		"mk_pap_t1_foot_latin_milites",
		"mk_pap_t1_latin_milites",
		"mk_pap_t1_mounted_crossbowmen",
		"mk_pap_t1_mounted_serjeants",
		"mk_pap_t1_papal_sergeants",
		"mk_pap_t1_spear_militia",
		"mk_pap_t1_spearmen",
		"mk_pap_t1_sword_militia",
		"mk_pap_t1_swordsmen",
	},
	["mk_fact_separatists_pisa"] = {
		"mk_eur_t1_catapult",
		"mk_pis_t1_archers",
		"mk_pis_t1_berrovieri",
		"mk_pis_t1_foot_berrovieri",
		"mk_pis_t1_ghibelline_crossbowmen",
		"mk_pis_t1_ghibelline_spearmen",
		"mk_pis_t1_knights",
		"mk_pis_t1_light_cav",
		"mk_pis_t1_militia_archer",
		"mk_pis_t1_militia_crossbowmen",
		"mk_pis_t1_militia_spearmen",
		"mk_pis_t1_militia_swordsmen",
		"mk_pis_t1_mounted_crossbowmen",
		"mk_pis_t1_swordsmen",
	},
	["mk_fact_separatists_portugal"] = {
		"mk_eur_t1_catapult",
		"mk_por_t1_besteiros",
		"mk_por_t1_cavaleiros",
		"mk_por_t1_cavaleiros_apeados",
		"mk_por_t1_cavaleiros_vilaos",
		"mk_por_t1_fundeiros",
		"mk_por_t1_milicia_concelhia",
		"mk_por_t1_peoes_de_besta",
		"mk_por_t1_peoes_de_dardo",
		"mk_por_t1_peoes_de_lanca",
	},
	["mk_fact_separatists_prussian"] = {
		"mk_lit_t1_axemen",
		"mk_lit_t1_boyars",
		"mk_lit_t1_ducal_axemen",
		"mk_lit_t1_ducal_spearmen",
		"mk_lit_t1_lithuanian_skirmishers",
		"mk_lit_t1_militia_crossbowmen",
		"mk_lit_t1_militia_spearmen",
		"mk_lit_t1_noble_cavalry",
		"mk_lit_t1_noble_swordsmen",
		"mk_lit_t1_ruthenian_archers",
		"mk_lit_t1_skirmisher_cavalry",
		"mk_rus_t1_catapult",
	},
	["mk_fact_separatists_rus"] = {
		"mk_rus_t1_catapult",
		"mk_rus_t1_dismounted_druzina",
		"mk_rus_t1_druzina",
		"mk_rus_t1_guard_axemen",
		"mk_rus_t1_javelinmen",
		"mk_rus_t1_militia_archers",
		"mk_rus_t1_militia_heavy_spearmen",
		"mk_rus_t1_militia_infantry",
		"mk_rus_t1_militia_spearmen",
		"mk_rus_t1_senior_druzina",
		"mk_rus_t1_spearmen",
		"mk_rus_t1_swordsmen",
		"mk_rus_t2_boyar_sons",
	},
	["mk_fact_separatists_schwyz"] = {
		"mk_eur_t1_catapult",
		"mk_swi_t1_archer_militia",
		"mk_swi_t1_archer_sergeants",
		"mk_swi_t1_crossbow_militia",
		"mk_swi_t1_crossbowmen",
		"mk_swi_t1_kyburg_axemen",
		"mk_swi_t1_kyburg_knights_mounted",
		"mk_swi_t1_kyburg_notables_mounted",
		"mk_swi_t1_landsturm_halberdiers",
		"mk_swi_t1_mounted_crossbows",
		"mk_swi_t1_zaehringer_schiltron",
		"mk_swi_t1_zaehringer_swordsmen",
	},
	["mk_fact_separatists_scotland"] = {
		"mk_sco_t1_ettrick_archers",
		"mk_sco_t1_highlanders",
		"mk_sco_t1_hobilars",
		"mk_sco_t1_knights",
		"mk_sco_t1_longbow_militia",
		"mk_sco_t1_pikemen",
		"mk_sco_t1_sergeants",
	},
	["mk_fact_separatists_seljuks"] = {
		"mk_mus_t1_catapult",
		"mk_rum_t1_askeri_nobles",
		"mk_rum_t1_futuwwa",
		"mk_rum_t1_ghazi_horse_archers",
		"mk_rum_t1_ghazi_lancers",
		"mk_rum_t1_ghazi_warriors",
		"mk_rum_t1_ghulam_foot_guard",
		"mk_rum_t1_jira_khaars",
		"mk_rum_t1_junior_ghulams",
		"mk_rum_t1_koyluleri",
		"mk_rum_t1_muqti_cavalry",
		"mk_rum_t1_naffatun",
		"mk_rum_t1_senior_ghulams",
		"mk_rum_t1_turcoman_tribal_cavalry",
		"mk_rum_t1_uc_suvarileri",
		"mk_rum_t1_uc_turkleri",
	},
	["mk_fact_separatists_serbia"] = {
		"mk_eur_t1_catapult",
		"mk_serb_t1_archers",
		"mk_serb_t1_frontiersmen",
		"mk_serb_t1_militia_spearmen",
		"mk_serb_t1_peasant_bowmen",
		"mk_serb_t1_pronija_lancer",
		"mk_serb_t1_vlastelicici",
		"mk_serb_t1_vojnici_axemen",
		"mk_serb_t1_vojnici_spearmen",
	},
	["mk_fact_separatists_sicily"] = {
		"mk_eur_t1_catapult",
		"mk_sic_t1_crossbowmen",
		"mk_sic_t1_ghibelline_spearmen",
		"mk_sic_t1_guelph_maa",
		"mk_sic_t1_guelph_mounted_maa",
		"mk_sic_t1_italian_jav_militia",
		"mk_sic_t1_knights",
		"mk_sic_t1_maa",
		"mk_sic_t1_militia_crossbowmen",
		"mk_sic_t1_militia_spearmen",
		"mk_sic_t1_militia_swordsmen",
		"mk_sic_t1_muslim_archers",
	},
	["mk_fact_separatists_sweden"] = {
		"mk_eur_t1_catapult",
		"mk_swd_t1_atgeir_bondir",
		"mk_swd_t1_bondir",
		"mk_swd_t1_crossbowmen",
		"mk_swd_t1_haelsing_hunters",
		"mk_swd_t1_hirdmen",
		"mk_swd_t1_jarl_bodyguard",
		"mk_swd_t1_mounted_fralse",
		"mk_swd_t1_sergeants",
		"mk_swd_t1_spear_bondir",
		"mk_swd_t1_svenns",
	},
	["mk_fact_separatists_tatars"] = {
		"mk_mon_t1_catapult",
		"mk_mon_t1_fire_lance_infantry",
		"mk_mon_t1_golden_hashar_levy",
		"mk_mon_t1_golden_heavy_horse_archers",
		"mk_mon_t1_golden_heavy_lancers",
		"mk_mon_t1_golden_horse_archers",
		"mk_mon_t1_golden_kharash",
		"mk_mon_t1_golden_lancers",
		"mk_mon_t1_golden_rus_archers",
		"mk_mon_t1_golden_tserig_spearmen",
		"mk_mon_t1_golden_turk_heavy_horse_archers",
		"mk_mon_t1_ilkhan_turkic_archers",
	},
	["mk_fact_separatists_teutonic"] = {
		"mk_eur_t1_catapult",
		"mk_teu_t1_levy_crossbowmen",
		"mk_teu_t1_levy_spearmen",
		"mk_teu_t1_livonian_crossbowmen",
		"mk_teu_t1_mounted_crossbowmen",
		"mk_teu_t1_mounted_sergeants",
		"mk_teu_t1_pogesanian_raiders",
		"mk_teu_t1_prussian_archers",
		"mk_teu_t1_ritterbruder",
		"mk_teu_t1_samlander_swordsmen",
		"mk_teu_t1_sergeant_brother",
		"mk_teu_t1_sergeant_brother_axemen",
		"mk_teu_t1_sergeant_spearmen",
		"mk_teu_t1_sudovian_skirmisher_cavalry",
		"mk_teu_t1_swordbrethren",
		"mk_teu_t1_swordbrother_knight",
	},
	["mk_fact_separatists_toulouse"] = {
		"mk_eur_t1_catapult",
		"mk_tou_t1_archers",
		"mk_tou_t1_chevaliers",
		"mk_tou_t1_cliens",
		"mk_tou_t1_communal_guisarmiers",
		"mk_tou_t1_crossbowmen",
		"mk_tou_t1_dismounted_chevaliers",
		"mk_tou_t1_levy_crossbowmen",
		"mk_tou_t1_mounted_crossbowmen",
		"mk_tou_t1_mounted_sergeants",
		"mk_tou_t1_ribauds",
		"mk_tou_t1_sergeant_axemen",
		"mk_tou_t1_sergeants",
		"mk_tou_t1_spear_levy",
		"mk_tou_t1_spearmen",
		"mk_tou_t1_voulge_militia",
	},
	["mk_fact_separatists_trebizond"] = {
		"mk_byz_t1_catapult",
		"mk_trbznd_t1_guard_archers",
		"mk_trbznd_t1_kavallarioi",
		"mk_trbznd_t1_militia",
		"mk_trbznd_t1_peltastoi",
		"mk_trbznd_t1_pronoia_lancers",
		"mk_trbznd_t1_scoutatoi",
		"mk_trbznd_t1_scoutatoi_swordsmen",
		"mk_trbznd_t1_toxotai",
		"mk_trbznd_t1_trapezitae_mounted_javcav",
		"mk_trbznd_t1_trebizond_archers",
	},
	["mk_fact_separatists_trier"] = {
		"mk_eur_t1_catapult",
		"mk_tri_t1_elector_bowmen",
		"mk_tri_t1_elector_knights",
		"mk_tri_t1_elector_spearmen",
		"mk_tri_t1_elector_swordsmen",
		"mk_tri_t1_trier_city_knights",
		"mk_tri_t1_trier_crossbowmen",
		"mk_tri_t1_trier_spearmen",
		"mk_tri_t1_trier_swordsmen",
	},
	["mk_fact_separatists_turks"] = {
		"mk_mus_t1_catapult",
		"mk_rum_t1_askeri_nobles",
		"mk_rum_t1_futuwwa",
		"mk_rum_t1_ghazi_horse_archers",
		"mk_rum_t1_ghazi_lancers",
		"mk_rum_t1_ghazi_warriors",
		"mk_rum_t1_ghulam_foot_guard",
		"mk_rum_t1_jira_khaars",
		"mk_rum_t1_junior_ghulams",
		"mk_rum_t1_koyluleri",
		"mk_rum_t1_muqti_cavalry",
		"mk_rum_t1_naffatun",
		"mk_rum_t1_senior_ghulams",
		"mk_rum_t1_turcoman_tribal_cavalry",
		"mk_rum_t1_uc_suvarileri",
		"mk_rum_t1_uc_turkleri",
	},
	["mk_fact_separatists_venice"] = {
		"mk_eur_t1_catapult",
		"mk_ven_t1_archers",
		"mk_ven_t1_crossbowmen",
		"mk_ven_t1_foot_zaffones",
		"mk_ven_t1_knight",
		"mk_ven_t1_militia_archer",
		"mk_ven_t1_militia_crossbowmen",
		"mk_ven_t1_militia_spearmen",
		"mk_ven_t1_militia_swordsmen",
		"mk_ven_t1_mounted_crossbow",
		"mk_ven_t1_mounted_zaffones",
		"mk_ven_t1_pikemen",
		"mk_ven_t1_scout",
		"mk_ven_t1_spearmen",
		"mk_ven_t1_swordsmen",
	},
	["mk_fact_separatists_volga"] = {
		"mk_mon_t1_catapult",
		"mk_volga_t1_chirmesh_HA",
		"mk_volga_t1_chirmesh_archers",
		"mk_volga_t1_chirmesh_lancers",
		"mk_volga_t1_chirmesh_spearmen",
		"mk_volga_t1_elite_archers",
		"mk_volga_t1_elite_cav",
		"mk_volga_t1_knights",
		"mk_volga_t1_light_HA",
		"mk_volga_t1_skirmisher_cavalry",
		"mk_volga_t1_tribal_archers",
		"mk_volga_t1_tribal_infantry",
		"mk_volga_t1_tribal_noble_archers",
		"mk_volga_t1_tribal_skirmishers",
		"mk_volga_t1_tribal_spearmen",
	},
	["mk_fact_separatists_wallachia"] = {
		"mk_byz_t1_catapult",
		"mk_vlach_t1_boieri",
		"mk_vlach_t1_boieri_archers",
		"mk_vlach_t1_calarasi_horse_archers",
		"mk_vlach_t1_curteni_cavalry",
		"mk_vlach_t1_maciuca_macemen",
		"mk_vlach_t1_militia_archers",
		"mk_vlach_t1_militia_spearmen",
		"mk_vlach_t1_mosneni",
		"mk_vlach_t1_mosneni_archers",
		"mk_vlach_t1_peasants",
		"mk_vlach_t1_plaiesi_javelinmen",
	},
	["mk_fact_separatists_wendish"] = {
		"mk_eur_t1_catapult",
		"mk_pol_t1_archers_lesser_poland",
		"mk_pol_t1_axemen_lesser_poland",
		"mk_pol_t1_knight_lesser_poland",
		"mk_pol_t1_militia_crossbowmen",
		"mk_pol_t1_militia_spearmen",
		"mk_pol_t1_mounted_crossbowmen",
		"mk_pol_t1_mounted_sergeants",
		"mk_pol_t1_sergeant_crossbowmen_lesser_poland",
		"mk_pol_t1_sergeant_spearmen",
		"mk_pol_t1_sergeants",
	},
	["mk_fact_separatists_zagwe"] = {
		"mk_mus_t1_catapult",
		"mk_zag_t1_aqaytat",
		"mk_zag_t1_bow_sarawit",
		"mk_zag_t1_hadar_frontiersmen",
		"mk_zag_t1_heroic_horsemen",
		"mk_zag_t1_highland_angada",
		"mk_zag_t1_horse_sarawit",
		"mk_zag_t1_spear_sarawit",
	},
	["mk_fact_separatists_zengid"] = {
		"mk_ata_t1_askari",
		"mk_ata_t1_ghazi_cavalry",
		"mk_khw_t1_charkh_infantry",
		"mk_khw_t1_ghazi",
		"mk_khw_t1_ghulaman",
		"mk_khw_t1_javanmardan",
		"mk_khw_t1_junior_ghulaman",
		"mk_khw_t1_muqti",
		"mk_khw_t1_muttawiah",
		"mk_khw_t1_naffatun",
		"mk_khw_t1_piyadegan",
		"mk_khw_t1_rayat",
		"mk_khw_t1_turcoman_cavalry",
		"mk_mus_t1_catapult",
		"mk_zen_t1_arab_jarida",
		"mk_zen_t1_jazira_infantry",
		"mk_zen_t1_jazira_spearmen",
		"mk_zen_t1_tawashi_cavalry",
	},
};

DIPLOMACY_OPTIONS = {
	"trade agreement",
	"hard military access",
	"cancel hard military access",
	"military alliance",
	"regions",
	"technology",
	"state gift",
	"payments",
	"vassal",
	"peace",
	"war",
	"join war",
	"break trade",
	"break alliance",
	"hostages",
	"marriage",
	"non aggression pact",
	"soft military access",
	"cancel soft military access",
	"defensive alliance",
	"client state",
	--"form confederation",
	"break non aggression pact",
	"break soft military access",
	"break defensive alliance",
	"break vassal",
	"break client state",
	"state gift unilateral"
};

MAX_TECHS = {
	{"mk_barb_civil_imperial_autocracy", "mk_barb_military_massed_infantry_formations"},
	{"mk_east_civil_discovery_of_coffee", "mk_east_military_joint_operations"},
	{"mk_noma_civil_chingissid_legacy", "mk_noma_military_nonlinear_combat_tactics"},
	{"mk_orth_civil_imperial_restoration", "mk_orth_military_military_renaissance"},
	{"mk_west_civil_new_world_expeditions", "mk_west_military_combined_arms_tactics"}
}
