-- Some factions aren't in here due to kingdom missions, already being empires, being rebels, special cases (like the papacy), etc.
DYNAMIC_FACTION_NAMES_FACTIONS = {
	"mk_fact_achaea",
	"mk_fact_alania",
	"mk_fact_antioch",
	"mk_fact_aragon",
	"mk_fact_armenia",
	"mk_fact_austria",
	"mk_fact_bavaria",
	"mk_fact_bohemia",
	"mk_fact_bologna",
	"mk_fact_brabant",
	"mk_fact_brandenburg",
	"mk_fact_bulgaria",
	"mk_fact_burgundy",
	"mk_fact_castile",
	"mk_fact_chernigov",
	"mk_fact_croatia",
	"mk_fact_cumans",
	"mk_fact_dauphine",
	"mk_fact_denmark",
	"mk_fact_england",
	"mk_fact_flanders",
	"mk_fact_france",
	"mk_fact_friesland",
	"mk_fact_genoa",
	"mk_fact_georgia",
	"mk_fact_ghurids",
	"mk_fact_goldenhorde",
	"mk_fact_greaterpoland",
	"mk_fact_hafsids",
	"mk_fact_halych",
	"mk_fact_hazaraspids",
	"mk_fact_hungary",
	"mk_fact_ildegizids",
	"mk_fact_ilkhanate",
	"mk_fact_ireland",
	"mk_fact_jerusalem",
	"mk_fact_kiev",
	"mk_fact_lithuania",
	"mk_fact_lorraine",
	"mk_fact_makuria",
	"mk_fact_marinids",
	"mk_fact_mecca",
	"mk_fact_milan",
	"mk_fact_navarre",
	"mk_fact_norway",
	"mk_fact_oman",
	"mk_fact_pisa",
	"mk_fact_pomerania",
	"mk_fact_portugal",
	"mk_fact_provence",
	"mk_fact_salghurids",
	"mk_fact_savoy",
	"mk_fact_saxony",
	"mk_fact_schwyz",
	"mk_fact_scotland",
	"mk_fact_seljuks",
	"mk_fact_shirvan",
	"mk_fact_sicily",
	"mk_fact_silesia",
	"mk_fact_sweden",
	"mk_fact_teutonicorder",
	"mk_fact_thessalonica",
	"mk_fact_toulouse",
	"mk_fact_trier",
	"mk_fact_venice",
	"mk_fact_verona",
	"mk_fact_vladimir",
	"mk_fact_volga",
	"mk_fact_wales",
	"mk_fact_wallachia",
	"mk_fact_yotvingians",
	"mk_fact_zagwe",
	"mk_fact_zengids",
};

-- Factions not in this array or the next are level 1 by default.
FACTIONS_DFN_EMPIRES = {
	"mk_fact_abbasids",
	"mk_fact_almohads",
	"mk_fact_ayyubids",
	"mk_fact_epirus",
	"mk_fact_goldenhorde",
	"mk_fact_hre",
	"mk_fact_ilkhanate",
	"mk_fact_khwarazm",
	"mk_fact_latinempire",
	"mk_fact_nicaea",
	"mk_fact_trebizond"
};

FACTIONS_DFN_KINGDOMS = {
	"mk_fact_aragon",
	"mk_fact_armenia",
	"mk_fact_bohemia",
	"mk_fact_bulgaria",
	"mk_fact_castile",
	"mk_fact_chernigov",
	"mk_fact_croatia",
	"mk_fact_cumans",
	"mk_fact_denmark",
	"mk_fact_england",
	"mk_fact_france",
	"mk_fact_friesland",
	"mk_fact_genoa",
	"mk_fact_georgia",
	"mk_fact_ghurids",
	"mk_fact_hafsids",
	"mk_fact_hungary",
	"mk_fact_ildegizids",
	"mk_fact_ireland",
	"mk_fact_jerusalem",
	"mk_fact_kiev",
	"mk_fact_makuria",
	"mk_fact_marinids",
	"mk_fact_mecca",
	"mk_fact_navarre",
	"mk_fact_norway",
	"mk_fact_oman",
	"mk_fact_pisa",
	"mk_fact_portugal",
	"mk_fact_scotland",
	"mk_fact_seljuks",
	"mk_fact_shirvan",
	"mk_fact_sicily",
	"mk_fact_sweden",
	"mk_fact_teutonicorder",
	"mk_fact_thessalonica",
	"mk_fact_venice",
	"mk_fact_vladimir",
	"mk_fact_volga",
	"mk_fact_zagwe"
};

-- Level 1 is handed by normal faction names.
DFN_NAMES_LOCALISATION = {
	["mk_fact_abbasids_lvl3"] = "Abbasid Caliphate",
	["mk_fact_achaea_lvl1"] = "Principality of Achaea",
	["mk_fact_achaea_lvl2"] = "Kingdom of Achaea",
	["mk_fact_achaea_lvl3"] = "Achaean Empire",
	["mk_fact_alania_lvl1"] = "Kingdom of Alania",
	["mk_fact_alania_lvl2"] = "Kingdom of Alania",
	["mk_fact_alania_lvl3"] = "Empire of Alania",
	["mk_fact_almohads_lvl3"] = "Almohad Caliphate",
	["mk_fact_antioch_lvl1"] = "Principality of Antioch",
	["mk_fact_antioch_lvl2"] = "Kingdom of Antioch",
	["mk_fact_antioch_lvl3"] = "Empire of Antioch",
	["mk_fact_aragon_lvl1"] = "Crown of Aragon",
	["mk_fact_aragon_lvl2"] = "Crown of Aragon",
	["mk_fact_aragon_lvl3"] = "Aragonese Empire",
	["mk_fact_aragon_lvl4"] = "Kingdom of Spain",
	["mk_fact_aragon_lvl5"] = "Spanish Empire",
	["mk_fact_armenia_lvl1"] = "Kingdom of Cilicia",
	["mk_fact_armenia_lvl2"] = "Kingdom of Cilicia",
	["mk_fact_armenia_lvl3"] = "Empire of Cilicia",
	["mk_fact_armenia_lvl4"] = "Kingdom of Armenia",
	["mk_fact_armenia_lvl5"] = "Armenian Empire",
	["mk_fact_austria_lvl1"] = "Duchy of Austria",
	["mk_fact_austria_lvl2"] = "Kingdom of Austria",
	["mk_fact_austria_lvl3"] = "Austrian Empire",
	["mk_fact_ayyubids_lvl1"] = "Ayyubid Sultanate",
	["mk_fact_ayyubids_lvl2"] = "Ayyubid Sultanate",
	["mk_fact_ayyubids_lvl3"] = "Ayyubid Empire",
	["mk_fact_bavaria_lvl1"] = "Duchy of Bavaria",
	["mk_fact_bavaria_lvl2"] = "Kingdom of Bavaria",
	["mk_fact_bavaria_lvl3"] = "Bavarian Empire",
	["mk_fact_bohemia_lvl1"] = "Kingdom of Bohemia",
	["mk_fact_bohemia_lvl2"] = "Kingdom of Bohemia",
	["mk_fact_bohemia_lvl3"] = "Bohemian Empire",
	["mk_fact_bologna_lvl1"] = "Commune of Bologna",
	["mk_fact_bologna_lvl2"] = "Republic of Bologna",
	["mk_fact_bologna_lvl3"] = "Empire of Bologna",
	["mk_fact_bologna_lvl4"] = "Kingdom of Italy",
	["mk_fact_bologna_lvl5"] = "Italian Empire",
	["mk_fact_brabant_lvl1"] = "Duchy of Brabant",
	["mk_fact_brabant_lvl2"] = "Kingdom of Brabant",
	["mk_fact_brabant_lvl3"] = "Empire of Brabant",
	["mk_fact_brandenburg_lvl1"] = "Margraviate of Brandenburg",
	["mk_fact_brandenburg_lvl2"] = "Kingdom of Brandenburg",
	["mk_fact_brandenburg_lvl3"] = "Empire of Brandenburg",
	["mk_fact_bulgaria_lvl1"] = "Tsardom of Bulgaria",
	["mk_fact_bulgaria_lvl2"] = "Tsardom of Bulgaria",
	["mk_fact_bulgaria_lvl3"] = "Bulgarian Empire",
	["mk_fact_burgundy_lvl1"] = "Duchy of Burgundy",
	["mk_fact_burgundy_lvl2"] = "Kingdom of Burgundy",
	["mk_fact_burgundy_lvl3"] = "Burgundian Empire",
	["mk_fact_castile_lvl1"] = "Kingdom of Castile",
	["mk_fact_castile_lvl2"] = "Kingdom of Castile",
	["mk_fact_castile_lvl3"] = "Castilian Empire",
	["mk_fact_castile_lvl4"] = "Kingdom of Spain",
	["mk_fact_castile_lvl5"] = "Spanish Empire",
	["mk_fact_chernigov_lvl1"] = "Grand Knyazate of Chernigov",
	["mk_fact_chernigov_lvl2"] = "Grand Knyazate of Chernigov",
	["mk_fact_chernigov_lvl3"] = "Empire of Chernigov",
	["mk_fact_croatia_lvl1"] = "Kingdom of Croatia",
	["mk_fact_croatia_lvl2"] = "Kingdom of Croatia",
	["mk_fact_croatia_lvl3"] = "Empire of Croatia",
	["mk_fact_cumans_lvl1"] = "Cuman-Kipchak Confederacy",
	["mk_fact_cumans_lvl2"] = "Cuman-Kipchak Confederacy",
	["mk_fact_cumans_lvl3"] = "Cuman-Kipchak Empire",
	["mk_fact_dauphine_lvl1"] = "Dauphiné of Viennois",
	["mk_fact_dauphine_lvl2"] = "Kingdom of Dauphiné",
	["mk_fact_dauphine_lvl3"] = "Empire of Dauphiné",
	["mk_fact_denmark_lvl1"] = "Kingdom of Denmark",
	["mk_fact_denmark_lvl2"] = "Kingdom of Denmark",
	["mk_fact_denmark_lvl3"] = "Danish Empire",
	["mk_fact_england_lvl1"] = "Kingdom of England",
	["mk_fact_england_lvl2"] = "Kingdom of England",
	["mk_fact_england_lvl3"] = "British Empire",
	["mk_fact_epirus_lvl3"] = "Empire of Epirus",
	["mk_fact_epirus_lvl4"] = "Byzantine Empire",
	["mk_fact_epirus_lvl5"] = "Roman Empire",
	["mk_fact_flanders_lvl1"] = "County of Flanders",
	["mk_fact_flanders_lvl2"] = "Kingdom of Flanders",
	["mk_fact_flanders_lvl3"] = "Empire of Flanders",
	["mk_fact_france_lvl1"] = "Kingdom of France",
	["mk_fact_france_lvl2"] = "Kingdom of France",
	["mk_fact_france_lvl3"] = "French Empire",
	["mk_fact_friesland_lvl1"] = "Upstalsboom League",
	["mk_fact_friesland_lvl2"] = "Upstalsboom League",
	["mk_fact_friesland_lvl3"] = "Empire of the Netherlands",
	["mk_fact_genoa_lvl1"] = "Republic of Genoa",
	["mk_fact_genoa_lvl2"] = "Republic of Genoa",
	["mk_fact_genoa_lvl3"] = "Genoese Empire",
	["mk_fact_genoa_lvl4"] = "Kingdom of Italy",
	["mk_fact_genoa_lvl5"] = "Italian Empire",
	["mk_fact_georgia_lvl1"] = "Kingdom of Georgia",
	["mk_fact_georgia_lvl2"] = "Kingdom of Georgia",
	["mk_fact_georgia_lvl3"] = "Empire of Georgia",
	["mk_fact_ghurids_lvl1"] = "Ghurid Sultanate",
	["mk_fact_ghurids_lvl2"] = "Ghurid Sultanate",
	["mk_fact_ghurids_lvl3"] = "Ghurid Empire",
	["mk_fact_goldenhorde_lvl3"] = "Ulus of Jochi",
	["mk_fact_goldenhorde_lvl4"] = "Golden Horde",
	["mk_fact_greaterpoland_lvl1"] = "Duchy of Greater Poland",
	["mk_fact_greaterpoland_lvl2"] = "Kingdom of Poland",
	["mk_fact_greaterpoland_lvl3"] = "Polish Empire",
	["mk_fact_hafsids_lvl1"] = "Hafsid Sultanate",
	["mk_fact_hafsids_lvl2"] = "Hafsid Sultanate",
	["mk_fact_hafsids_lvl3"] = "Hafsid Empire",
	["mk_fact_halych_lvl1"] = "Grand Knyazate of Halych-Volhynia",
	["mk_fact_halych_lvl2"] = "Grand Knyazate of Halych-Volhynia",
	["mk_fact_halych_lvl3"] = "Empire of Halych-Volhynia",
	["mk_fact_hazaraspids_lvl1"] = "Hazaraspid Atabegate",
	["mk_fact_hazaraspids_lvl2"] = "Hazaraspid Shahdom",
	["mk_fact_hazaraspids_lvl3"] = "Hazaraspid Empire",
	["mk_fact_hre_lvl3"] = "Holy Roman Empire",
	["mk_fact_hungary_lvl1"] = "Kingdom of Hungary",
	["mk_fact_hungary_lvl2"] = "Kingdom of Hungary",
	["mk_fact_hungary_lvl3"] = "Hungarian Empire",
	["mk_fact_ildegizids_lvl1"] = "Ildegizid Atabegate",
	["mk_fact_ildegizids_lvl2"] = "Ildegizid Shahdom",
	["mk_fact_ildegizids_lvl3"] = "Ildegizid Empire",
	["mk_fact_ilkhanate_lvl3"] = "Ulus of Tolui",
	["mk_fact_ilkhanate_lvl4"] = "Ilkhanate",
	["mk_fact_ireland_lvl1"] = "Kingdom of Connacht",
	["mk_fact_ireland_lvl2"] = "Kingdom of Connacht",
	["mk_fact_ireland_lvl3"] = "Irish Empire",
	["mk_fact_jerusalem_lvl1"] = "Kingdom of Jerusalem & Cyprus",
	["mk_fact_jerusalem_lvl2"] = "Kingdom of Jerusalem & Cyprus",
	["mk_fact_jerusalem_lvl3"] = "Empire of the Outremer",
	["mk_fact_kiev_lvl1"] = "Grand Knyazate of Kiev",
	["mk_fact_kiev_lvl2"] = "Grand Knyazate of Kiev",
	["mk_fact_kiev_lvl3"] = "Empire of Kiev",
	["mk_fact_khwarazm_lvl3"] = "Khwarazmian Empire",
	["mk_fact_latinempire_lvl3"] = "Latin Empire",
	["mk_fact_lesserpoland_lvl2"] = "Kingdom of Poland",
	["mk_fact_lesserpoland_lvl3"] = "Polish Empire",
	["mk_fact_lithuania_lvl1"] = "Grand Duchy of Lithuania",
	["mk_fact_lithuania_lvl2"] = "Kingdom of Lithuania",
	["mk_fact_lithuania_lvl3"] = "Lithuanian Empire",
	["mk_fact_lorraine_lvl1"] = "Duchy of Lorraine",
	["mk_fact_lorraine_lvl2"] = "Kingdom of Lorraine",
	["mk_fact_lorraine_lvl3"] = "Empire of Lorraine",
	["mk_fact_makuria_lvl1"] = "Kingdom of Makuria",
	["mk_fact_makuria_lvl2"] = "Kingdom of Makuria",
	["mk_fact_makuria_lvl3"] = "Empire of Makuria",
	["mk_fact_marinids_lvl1"] = "Marinid Sultanate",
	["mk_fact_marinids_lvl2"] = "Marinid Sultanate",
	["mk_fact_marinids_lvl3"] = "Marinid Empire",
	["mk_fact_mecca_lvl1"] = "Sharifate of Mecca",
	["mk_fact_mecca_lvl2"] = "Sharifate of Mecca",
	["mk_fact_mecca_lvl3"] = "Sharifate of Mecca",
	["mk_fact_milan_lvl1"] = "Commune of Milan",
	["mk_fact_milan_lvl2"] = "Kingdom of Milan",
	["mk_fact_milan_lvl3"] = "Empire of Milan",
	["mk_fact_milan_lvl4"] = "Kingdom of Italy",
	["mk_fact_milan_lvl5"] = "Italian Empire",
	["mk_fact_navarre_lvl1"] = "Kingdom of Navarre",
	["mk_fact_navarre_lvl2"] = "Kingdom of Navarre",
	["mk_fact_navarre_lvl3"] = "Empire of Navarre",
	["mk_fact_navarre_lvl4"] = "Kingdom of Spain",
	["mk_fact_navarre_lvl5"] = "Spanish Empire",
	["mk_fact_nicaea_lvl3"] = "Empire of Nicaea",
	["mk_fact_nicaea_lvl4"] = "Byzantine Empire",
	["mk_fact_nicaea_lvl5"] = "Roman Empire",
	["mk_fact_norway_lvl1"] = "Kingdom of Norway",
	["mk_fact_norway_lvl2"] = "Kingdom of Norway",
	["mk_fact_norway_lvl3"] = "Norwegian Empire",
	["mk_fact_oman_lvl1"] = "Malikate of Oman",
	["mk_fact_oman_lvl2"] = "Malikate of Oman",
	["mk_fact_oman_lvl3"] = "Empire of Oman",
	["mk_fact_pisa_lvl1"] = "Republic of Pisa",
	["mk_fact_pisa_lvl2"] = "Republic of Pisa",
	["mk_fact_pisa_lvl3"] = "Empire of Pisa",
	["mk_fact_pisa_lvl4"] = "Kingdom of Italy",
	["mk_fact_pisa_lvl5"] = "Italian Empire",
	["mk_fact_pomerania_lvl1"] = "Duchy of Pomerania",
	["mk_fact_pomerania_lvl2"] = "Kingdom of Pomerania",
	["mk_fact_pomerania_lvl3"] = "Pomeranian Empire",
	["mk_fact_portugal_lvl2"] = "Kingdom of Portugal",
	["mk_fact_portugal_lvl3"] = "Portuguese Empire",
	["mk_fact_provence_lvl1"] = "County of Provence",
	["mk_fact_provence_lvl2"] = "Kingdom of Provence",
	["mk_fact_provence_lvl3"] = "Empire of Provence",
	["mk_fact_salghurids_lvl1"] = "Salghurid Atabegate",
	["mk_fact_salghurids_lvl2"] = "Salghurid Sultanate",
	["mk_fact_salghurids_lvl3"] = "Salghurid Empire",
	["mk_fact_savoy_lvl1"] = "County of Savoy",
	["mk_fact_savoy_lvl2"] = "Kingdom of Savoy",
	["mk_fact_savoy_lvl3"] = "Empire of Savoy",
	["mk_fact_savoy_lvl4"] = "Kingdom of Italy",
	["mk_fact_savoy_lvl5"] = "Italian Empire",
	["mk_fact_saxony_lvl1"] = "Duchy of Saxony",
	["mk_fact_saxony_lvl2"] = "Kingdom of Saxony",
	["mk_fact_saxony_lvl3"] = "Empire of Saxony",
	["mk_fact_schwyz_lvl1"] = "Canton of Schwyz",
	["mk_fact_schwyz_lvl2"] = "Swiss Confederacy",
	["mk_fact_schwyz_lvl3"] = "Swiss Empire",
	["mk_fact_scotland_lvl1"] = "Kingdom of Scotland",
	["mk_fact_scotland_lvl2"] = "Kingdom of Scotland",
	["mk_fact_scotland_lvl3"] = "Empire of Scotland",
	["mk_fact_seljuks_lvl1"] = "Seljuk Sultanate of Rûm",
	["mk_fact_seljuks_lvl2"] = "Seljuk Sultanate of Rûm",
	["mk_fact_seljuks_lvl3"] = "Seljuk Empire",
	["mk_fact_serbia_lvl2"] = "Kingdom of Serbia",
	["mk_fact_serbia_lvl3"] = "Serbian Empire",
	["mk_fact_shirvan_lvl1"] = "Shirvan Shahdom",
	["mk_fact_shirvan_lvl2"] = "Shirvan Shahdom",
	["mk_fact_shirvan_lvl3"] = "Shirvan Empire",
	["mk_fact_sicily_lvl1"] = "Kingdom of Sicily",
	["mk_fact_sicily_lvl2"] = "Kingdom of Sicily",
	["mk_fact_sicily_lvl3"] = "Empire of Sicily",
	["mk_fact_sicily_lvl4"] = "Kingdom of Italy",
	["mk_fact_sicily_lvl5"] = "Italian Empire",
	["mk_fact_silesia_lvl1"] = "Duchy of Silesia",
	["mk_fact_silesia_lvl2"] = "Kingdom of Silesia",
	["mk_fact_silesia_lvl3"] = "Empire of Silesia",
	["mk_fact_sweden_lvl1"] = "Kingdom of Sweden",
	["mk_fact_sweden_lvl2"] = "Kingdom of Sweden",
	["mk_fact_sweden_lvl3"] = "Swedish Empire",
	["mk_fact_teutonicorder_lvl1"] = "Teutonic Order",
	["mk_fact_teutonicorder_lvl2"] = "Teutonic Order",
	["mk_fact_teutonicorder_lvl3"] = "Teutonic Empire",
	["mk_fact_thessalonica_lvl1"] = "Kingdom of Thessalonica",
	["mk_fact_thessalonica_lvl2"] = "Kingdom of Thessalonica",
	["mk_fact_thessalonica_lvl3"] = "Empire of Thessalonica",
	["mk_fact_toulouse_lvl1"] = "County of Toulouse",
	["mk_fact_toulouse_lvl2"] = "Kingdom of Toulouse",
	["mk_fact_toulouse_lvl3"] = "Empire of Toulouse",
	["mk_fact_trebizond_lvl3"] = "Empire of Trebizond",
	["mk_fact_trebizond_lvl4"] = "Byzantine Empire",
	["mk_fact_trebizond_lvl5"] = "Roman Empire",
	["mk_fact_trier_lvl1"] = "Electorate of Trier",
	["mk_fact_trier_lvl2"] = "Kingdom of Trier",
	["mk_fact_trier_lvl3"] = "Empire of Trier",
	["mk_fact_venice_lvl1"] = "Republic of Venice",
	["mk_fact_venice_lvl2"] = "Republic of Venice",
	["mk_fact_venice_lvl3"] = "Venetian Empire",
	["mk_fact_venice_lvl4"] = "Kingdom of Italy",
	["mk_fact_venice_lvl5"] = "Italian Empire",
	["mk_fact_verona_lvl1"] = "Commune of Verona",
	["mk_fact_verona_lvl2"] = "Kingdom of Verona",
	["mk_fact_verona_lvl3"] = "Empire of Verona",
	["mk_fact_verona_lvl4"] = "Kingdom of Italy",
	["mk_fact_verona_lvl5"] = "Italian Empire",
	["mk_fact_vladimir_lvl1"] = "Grand Knyazate of Vladimir",
	["mk_fact_vladimir_lvl2"] = "Grand Knyazate of Vladimir",
	["mk_fact_vladimir_lvl3"] = "Empire of Vladimir",
	["mk_fact_volga_lvl1"] = "Khanate of Volga Bulgaria",
	["mk_fact_volga_lvl2"] = "Khanate of Volga Bulgaria",
	["mk_fact_volga_lvl3"] = "Empire of Volga Bulgaria",
	["mk_fact_wales_lvl1"] = "Principality of Wales",
	["mk_fact_wales_lvl2"] = "Kingdom of Wales",
	["mk_fact_wales_lvl3"] = "Empire of Wales",
	["mk_fact_wallachia_lvl1"] = "Voivodeship of Wallachia",
	["mk_fact_wallachia_lvl2"] = "Kingdom of Wallachia",
	["mk_fact_wallachia_lvl3"] = "Empire of Wallachia",
	["mk_fact_yotvingians_lvl1"] = "Yotvingians",
	["mk_fact_yotvingians_lvl2"] = "Kingdom of Yotvingia",
	["mk_fact_yotvingians_lvl3"] = "Empire of Yotvingia",
	["mk_fact_zagwe_lvl1"] = "Zagwe Kingdom",
	["mk_fact_zagwe_lvl2"] = "Zagwe Kingdom",
	["mk_fact_zagwe_lvl3"] = "Zagwe Empire",
	["mk_fact_zengids_lvl1"] = "Zengid Atabegate",
	["mk_fact_zengids_lvl2"] = "Zengid Shahdom",
	["mk_fact_zengids_lvl3"] = "Zengid Empire"
};

ANNEX_VASSALS_SIZES = {
	"25",
	"20",
	"15",
	"10",
	"9",
	"8",
	"7",
	"6",
	"5",
	"4",
	"3",
	"2",
	"1"
};

ANNEX_VASSALS_PERCENTAGES = {
	"75%",
	"70%",
	"65%",
	"60%",
	"55%",
	"50%",
	"45%",
	"40%",
	"35%",
	"30%",
	"25%",
	"20%",
	"15%"
};

REGIONS_LIBERATION_FACTIONS = {
	["att_reg_aegyptus_alexandria"] = "mk_fact_ayyubids",
	["att_reg_aegyptus_berenice"] = "mk_fact_ayyubids",
	["att_reg_aegyptus_oxyrhynchus"] = "mk_fact_ayyubids",
	["att_reg_aethiopia_adulis"] = "mk_fact_makuria",
	["att_reg_aethiopia_aksum"] = "mk_fact_zagwe",
	["att_reg_aethiopia_pachoras"] = "mk_fact_makuria",
	["att_reg_africa_carthago"] = "mk_fact_hafsids",
	["att_reg_africa_constantina"] = "mk_fact_hafsids",
	["att_reg_africa_hadrumentum"] = "mk_fact_hafsids",
	["att_reg_aquitania_avaricum"] = "mk_fact_france",
	["att_reg_aquitania_burdigala"] = "mk_fact_england",
	["att_reg_aquitania_elusa"] = "mk_fact_toulouse",
	["att_reg_arabia_felix_eudaemon"] = "mk_fact_ayyubids",
	["att_reg_arabia_felix_omana"] = "mk_fact_oman",
	["att_reg_arabia_felix_zafar"] = "mk_fact_mecca",
	["att_reg_arabia_magna_dumatha"] = "mk_fact_mecca",
	["att_reg_arabia_magna_hira"] = "mk_fact_abbasids",
	["att_reg_arabia_magna_yathrib"] = "mk_fact_mecca",
	["att_reg_armenia_duin"] = "mk_fact_georgia",
	["att_reg_armenia_payttakaran"] = "mk_fact_ildegizids",
	["att_reg_armenia_tosp"] = "mk_fact_georgia",
	["att_reg_asia_cyzicus"] = "mk_fact_nicaea",
	["att_reg_asia_ephesus"] = "mk_fact_nicaea",
	["att_reg_asia_synnada"] = "mk_fact_nicaea",
	["att_reg_asorstan_arbela"] = "mk_fact_abbasids",
	["att_reg_asorstan_ctesiphon"] = "mk_fact_abbasids",
	["att_reg_asorstan_meshan"] = "mk_fact_abbasids",
	["att_reg_baetica_corduba"] = "mk_fact_almohads",
	["att_reg_baetica_hispalis"] = "mk_fact_almohads",
	["att_reg_baetica_malaca"] = "mk_fact_almohads",
	["att_reg_belgica_augusta_treverorum"] = "mk_fact_trier",
	["att_reg_belgica_colonia_agrippina"] = "mk_fact_brabant",
	["att_reg_belgica_durocorterum"] = "mk_fact_flanders",
	["att_reg_bithynia_amasea"] = "mk_fact_trebizond",
	["att_reg_bithynia_ancyra"] = "mk_fact_seljuks",
	["att_reg_bithynia_nicomedia"] = "mk_fact_nicaea",
	["att_reg_britannia_inferior_eboracum"] = "mk_fact_england",
	["att_reg_britannia_inferior_lindum"] = "mk_fact_england",
	["att_reg_britannia_inferior_segontium"] = "mk_fact_wales",
	["att_reg_britannia_superior_camulodunon"] = "mk_fact_england",
	["att_reg_britannia_superior_corinium"] = "mk_fact_england",
	["att_reg_britannia_superior_londinium"] = "mk_fact_england",
	["att_reg_caledonia_et_hibernia_eblana"] = "mk_fact_ireland",
	["att_reg_caledonia_et_hibernia_eildon"] = "mk_fact_scotland",
	["att_reg_caledonia_et_hibernia_tuesis"] = "mk_fact_scotland",
	["att_reg_cappadocia_caesarea_eusebia"] = "mk_fact_seljuks",
	["att_reg_cappadocia_melitene"] = "mk_fact_seljuks",
	["att_reg_cappadocia_trapezus"] = "mk_fact_trebizond",
	["att_reg_carthaginensis_carthago_nova"] = "mk_fact_almohads",
	["att_reg_carthaginensis_segobriga"] = "mk_fact_almohads",
	["att_reg_carthaginensis_toletum"] = "mk_fact_castile",
	["att_reg_caucasia_gabala"] = "mk_fact_shirvan",
	["att_reg_caucasia_kotais"] = "mk_fact_georgia",
	["att_reg_caucasia_mtskheta"] = "mk_fact_georgia",
	["att_reg_cilicia_iconium"] = "mk_fact_seljuks",
	["att_reg_cilicia_myra"] = "mk_fact_seljuks",
	["att_reg_cilicia_tarsus"] = "mk_fact_armenia",
	["att_reg_dacia_apulum"] = "mk_fact_hungary",
	["att_reg_dacia_petrodava"] = "mk_fact_wallachia",
	["att_reg_dacia_romula"] = "mk_fact_wallachia",
	["att_reg_dalmatia_domavia"] = "mk_fact_serbia",
	["att_reg_dalmatia_salona"] = "mk_fact_croatia",
	["att_reg_dalmatia_siscia"] = "mk_fact_croatia",
	["att_reg_dardania_scupi"] = "mk_fact_bulgaria",
	["att_reg_dardania_serdica"] = "mk_fact_bulgaria",
	["att_reg_dardania_viminacium"] = "mk_fact_serbia",
	["att_reg_frisia_angulus"] = "mk_fact_denmark",
	["att_reg_frisia_flevum"] = "mk_fact_friesland",
	["att_reg_frisia_tulifurdum"] = "mk_fact_hre",
	["att_reg_gallaecia_asturica"] = "mk_fact_castile",
	["att_reg_gallaecia_bracara"] = "mk_fact_portugal",
	["att_reg_gallaecia_brigantium"] = "mk_fact_castile",
	["att_reg_germania_aregelia"] = "mk_fact_saxony",
	["att_reg_germania_lupfurdum"] = "mk_fact_brandenburg",
	["att_reg_germania_uburzis"] = "mk_fact_hre",
	["att_reg_germano_sarmatia_duna"] = "mk_fact_yotvingians",
	["att_reg_germano_sarmatia_oium"] = "mk_fact_yotvingians",
	["att_reg_germano_sarmatia_palteskja"] = "mk_fact_lithuania",
	["att_reg_gothiscandza_ascaucalis"] = "mk_fact_greaterpoland",
	["att_reg_gothiscandza_gothiscandza"] = "mk_fact_pomerania",
	["att_reg_gothiscandza_rugion"] = "mk_fact_denmark",
	["att_reg_hercynia_budorgis"] = "mk_fact_silesia",
	["att_reg_hercynia_casurgis"] = "mk_fact_bohemia",
	["att_reg_hercynia_nitrahwa"] = "mk_fact_hungary",
	["att_reg_hyperborea_kariskos"] = "mk_fact_chernigov",
	["att_reg_hyperborea_moramar"] = "mk_fact_vladimir",
	["att_reg_hyperborea_sylis"] = "mk_fact_cumans",
	["att_reg_italia_fiorentia"] = "mk_fact_pisa",
	["att_reg_italia_neapolis"] = "mk_fact_sicily",
	["att_reg_italia_roma"] = "mk_fact_papacy",
	["att_reg_khwarasan_abarshahr"] = "mk_fact_khwarazm",
	["att_reg_khwarasan_harey"] = "mk_fact_khwarazm",
	["att_reg_khwarasan_merv"] = "mk_fact_khwarazm",
	["att_reg_libya_augila"] = "mk_fact_ayyubids",
	["att_reg_libya_paraetonium"] = "mk_fact_ayyubids",
	["att_reg_libya_ptolemais"] = "mk_fact_ayyubids",
	["att_reg_liguria_genua"] = "mk_fact_genoa",
	["att_reg_liguria_mediolanum"] = "mk_fact_milan",
	["att_reg_liguria_segusio"] = "mk_fact_savoy",
	["att_reg_lugdunensis_lugdunum"] = "mk_fact_france",
	["att_reg_lugdunensis_rotomagus"] = "mk_fact_france",
	["att_reg_lugdunensis_turonum"] = "mk_fact_france",
	["att_reg_lusitania_emerita_augusta"] = "mk_fact_almohads",
	["att_reg_lusitania_olisipo"] = "mk_fact_portugal",
	["att_reg_lusitania_pax_augusta"] = "mk_fact_portugal",
	["att_reg_macedonia_corinthus"] = "mk_fact_nicaea",
	["att_reg_macedonia_dyrrhachium"] = "mk_fact_epirus",
	["att_reg_macedonia_thessalonica"] = "mk_fact_nicaea",
	["att_reg_magna_graecia_rhegium"] = "mk_fact_sicily",
	["att_reg_magna_graecia_syracusae"] = "mk_fact_sicily",
	["att_reg_magna_graecia_tarentum"] = "mk_fact_sicily",
	["att_reg_makran_harmosia"] = "mk_fact_salghurids",
	["att_reg_makran_phra"] = "mk_fact_ghurids",
	["att_reg_makran_pura"] = "mk_fact_ghurids",
	["att_reg_mauretania_caesarea"] = "mk_fact_marinids",
	["att_reg_mauretania_tamousiga"] = "mk_fact_marinids",
	["att_reg_mauretania_tingis"] = "mk_fact_marinids",
	["att_reg_maxima_sequanorum_argentoratum"] = "mk_fact_lorraine",
	["att_reg_maxima_sequanorum_octodurus"] = "mk_fact_schwyz",
	["att_reg_maxima_sequanorum_vesontio"] = "mk_fact_burgundy",
	["att_reg_media_atropatene_ecbatana"] = "mk_fact_khwarazm",
	["att_reg_media_atropatene_ganzaga"] = "mk_fact_ildegizids",
	["att_reg_media_atropatene_rhaga"] = "mk_fact_khwarazm",
	["att_reg_narbonensis_aquae_sextiae"] = "mk_fact_provence",
	["att_reg_narbonensis_narbo"] = "mk_fact_toulouse",
	["att_reg_narbonensis_vienna"] = "mk_fact_dauphine",
	["att_reg_osroene_amida"] = "mk_fact_zengids",
	["att_reg_osroene_edessa"] = "mk_fact_ayyubids",
	["att_reg_osroene_nisibis"] = "mk_fact_zengids",
	["att_reg_palaestinea_aelia_capitolina"] = "mk_fact_ayyubids",
	["att_reg_palaestinea_aila"] = "mk_fact_ayyubids",
	["att_reg_palaestinea_nova_trajana_bostra"] = "mk_fact_ayyubids",
	["att_reg_pannonia_savaria"] = "mk_fact_hungary",
	["att_reg_pannonia_sirmium"] = "mk_fact_serbia",
	["att_reg_pannonia_sopianae"] = "mk_fact_hungary",
	["att_reg_persis_behdeshir"] = "mk_fact_khwarazm",
	["att_reg_persis_siraf"] = "mk_fact_salghurids",
	["att_reg_persis_stakhr"] = "mk_fact_salghurids",
	["att_reg_phazania_cydamus"] = "mk_fact_hafsids",
	["att_reg_phazania_dimmidi"] = "mk_fact_hafsids",
	["att_reg_phazania_garama"] = "mk_fact_hafsids",
	["att_reg_raetia_et_noricum_augusta_vindelicorum"] = "mk_fact_bavaria",
	["att_reg_raetia_et_noricum_iuvavum"] = "mk_fact_austria",
	["att_reg_raetia_et_noricum_virunum"] = "mk_fact_austria",
	["att_reg_sarmatia_asiatica_anacopia"] = "mk_fact_alania",
	["att_reg_sarmatia_asiatica_samandar"] = "mk_fact_cumans",
	["att_reg_sarmatia_asiatica_tanais"] = "mk_fact_cumans",
	["att_reg_sarmatia_europaea_chersonessus"] = "mk_fact_trebizond",
	["att_reg_sarmatia_europaea_gelonus"] = "mk_fact_cumans",
	["att_reg_sarmatia_europaea_olbia"] = "mk_fact_cumans",
	["att_reg_scandza_alabu"] = "mk_fact_denmark",
	["att_reg_scandza_hafn"] = "mk_fact_denmark",
	["att_reg_scandza_hrefnesholt"] = "mk_fact_sweden",
	["att_reg_scythia_bolghar"] = "mk_fact_volga",
	["att_reg_scythia_ra"] = "mk_fact_volga",
	["att_reg_scythia_sarai"] = "mk_fact_cumans",
	["att_reg_spahan_issatis"] = "mk_fact_khwarazm",
	["att_reg_spahan_spahan"] = "mk_fact_khwarazm",
	["att_reg_spahan_susa"] = "mk_fact_hazaraspids",
	["att_reg_syria_antiochia"] = "mk_fact_ayyubids",
	["att_reg_syria_emesa"] = "mk_fact_ayyubids",
	["att_reg_syria_tyrus"] = "mk_fact_ayyubids",
	["att_reg_tarraconensis_caesaraugusta"] = "mk_fact_aragon",
	["att_reg_tarraconensis_pompaelo"] = "mk_fact_navarre",
	["att_reg_tarraconensis_tarraco"] = "mk_fact_aragon",
	["att_reg_thracia_constantinopolis"] = "mk_fact_nicaea",
	["att_reg_thracia_marcianopolis"] = "mk_fact_bulgaria",
	["att_reg_thracia_trimontium"] = "mk_fact_bulgaria",
	["att_reg_transcarpathia_arheimar"] = "mk_fact_kiev",
	["att_reg_transcarpathia_belz"] = "mk_fact_lesserpoland",
	["att_reg_transcarpathia_leopolis"] = "mk_fact_halych",
	["att_reg_transcaspia_dahistan"] = "mk_fact_khwarazm",
	["att_reg_transcaspia_kath"] = "mk_fact_khwarazm",
	["att_reg_transcaspia_siahkuh"] = "mk_fact_cumans",
	["att_reg_tripolitana_leptis_magna"] = "mk_fact_hafsids",
	["att_reg_tripolitana_macomades"] = "mk_fact_hafsids",
	["att_reg_tripolitana_sabrata"] = "mk_fact_hafsids",
	["att_reg_venetia_aquileia"] = "mk_fact_venice",
	["att_reg_venetia_ravenna"] = "mk_fact_bologna",
	["att_reg_venetia_verona"] = "mk_fact_verona",
	["att_reg_mediterraneus_occidentalis_ajax"] = "mk_fact_genoa",
	["att_reg_mediterraneus_occidentalis_caralis"] = "mk_fact_pisa",
	["att_reg_mediterraneus_orientalis_gortyna"] = "mk_fact_venice",
	["att_reg_mediterraneus_orientalis_constantia"] = "mk_fact_nicaea",
	["att_reg_mediterraneus_orientalis_rhodes"] = "mk_fact_nicaea",
	["att_reg_mediterraneus_occidentalis_palma"] = "mk_fact_aragon"
};

-- Regions that will always be infected by year.

REGIONS_1346 = {
	"att_reg_armenia_payttakaran",
	"att_reg_sarmatia_asiatica_anacopia",
	"att_reg_sarmatia_asiatica_samandar",
	"att_reg_sarmatia_asiatica_tanais"
};

REGIONS_1347 = {
	"att_reg_aegyptus_alexandria",
	"att_reg_armenia_duin",
	"att_reg_armenia_tosp",
	"att_reg_asia_cyzicus",
	"att_reg_asia_ephesus",
	"att_reg_bithynia_nicomedia",
	"att_reg_caucasia_gabala",
	"att_reg_caucasia_kotais",
	"att_reg_caucasia_mtskheta",
	"att_reg_cilicia_myra",
	"att_reg_dalmatia_salona",
	"att_reg_hyperborea_sylis",
	"att_reg_liguria_genua",
	"att_reg_macedonia_corinthus",
	"att_reg_magna_graecia_syracusae",
	"att_reg_mediterraneus_occidentalis_ajax",
	"att_reg_mediterraneus_occidentalis_caralis",
	"att_reg_mediterraneus_orientalis_constantia",
	"att_reg_mediterraneus_orientalis_gortyna",
	"att_reg_mediterraneus_orientalis_rhodes",
	"att_reg_narbonensis_aquae_sextiae",
	"att_reg_sarmatia_europaea_chersonessus",
	"att_reg_sarmatia_europaea_gelonus",
	"att_reg_sarmatia_europaea_olbia",
	"att_reg_thracia_constantinopolis",
	"att_reg_venetia_aquileia"
};

REGIONS_1348 = {
	"att_reg_aegyptus_berenice",
	"att_reg_africa_carthago",
	"att_reg_africa_constantina",
	"att_reg_africa_hadrumentum",
	"att_reg_aquitania_avaricum",
	"att_reg_aquitania_burdigala",
	"att_reg_aquitania_elusa",
	"att_reg_asia_synnada",
	"att_reg_belgica_durocorterum",
	"att_reg_bithynia_amasea",
	"att_reg_britannia_superior_camulodunon",
	"att_reg_britannia_superior_corinium",
	"att_reg_britannia_superior_londinium",
	"att_reg_cappadocia_melitene",
	"att_reg_cappadocia_trapezus",
	"att_reg_carthaginensis_segobriga",
	"att_reg_cilicia_iconium",
	"att_reg_cilicia_tarsus",
	"att_reg_dalmatia_domavia",
	"att_reg_dalmatia_siscia",
	"att_reg_dardania_scupi",
	"att_reg_dardania_serdica",
	"att_reg_gallaecia_asturica",
	"att_reg_gallaecia_bracara",
	"att_reg_gallaecia_brigantium",
	"att_reg_hyperborea_kariskos",
	"att_reg_hyperborea_moramar",
	"att_reg_hyperborea_sylis",
	"att_reg_italia_fiorentia",
	"att_reg_italia_neapolis",
	"att_reg_italia_roma",
	"att_reg_libya_augila",
	"att_reg_libya_paraetonium",
	"att_reg_libya_ptolemais",
	"att_reg_liguria_mediolanum",
	"att_reg_liguria_segusio",
	"att_reg_lugdunensis_rotomagus",
	"att_reg_lusitania_olisipo",
	"att_reg_macedonia_dyrrhachium",
	"att_reg_macedonia_thessalonica",
	"att_reg_magna_graecia_rhegium",
	"att_reg_magna_graecia_tarentum",
	"att_reg_mauretania_caesarea",
	"att_reg_maxima_sequanorum_octodurus",
	"att_reg_mediterraneus_occidentalis_palma",
	"att_reg_narbonensis_narbo",
	"att_reg_narbonensis_vienna",
	"att_reg_osroene_amida",
	"att_reg_osroene_edessa",
	"att_reg_palaestinea_aelia_capitolina",
	"att_reg_palaestinea_aila",
	"att_reg_palaestinea_nova_trajana_bostra",
	"att_reg_raetia_et_noricum_virunum",
	"att_reg_syria_antiochia",
	"att_reg_syria_emesa",
	"att_reg_syria_tyrus",
	"att_reg_tarraconensis_caesaraugusta",
	"att_reg_tarraconensis_tarraco",
	"att_reg_thracia_marcianopolis",
	"att_reg_thracia_trimontium",
	"att_reg_transcarpathia_arheimar",
	"att_reg_tripolitana_leptis_magna",
	"att_reg_tripolitana_macomades",
	"att_reg_tripolitana_sabrata",
	"att_reg_venetia_ravenna",
	"att_reg_venetia_verona"
};

REGIONS_1349 = {
	"att_reg_aegyptus_oxyrhynchus",
	"att_reg_asorstan_arbela",
	"att_reg_asorstan_ctesiphon",
	"att_reg_asorstan_meshan",
	"att_reg_baetica_corduba",
	"att_reg_baetica_hispalis",
	"att_reg_baetica_malaca",
	"att_reg_belgica_augusta_treverorum",
	"att_reg_belgica_colonia_agrippina",
	"att_reg_bithynia_ancyra",
	"att_reg_britannia_inferior_eboracum",
	"att_reg_britannia_inferior_lindum",
	"att_reg_britannia_inferior_segontium",
	"att_reg_caledonia_et_hibernia_eblana",
	"att_reg_cappadocia_caesarea_eusebia",
	"att_reg_carthaginensis_carthago_nova",
	"att_reg_carthaginensis_toletum",
	"att_reg_dardania_viminacium",
	"att_reg_lugdunensis_lugdunum",
	"att_reg_lugdunensis_turonum",
	"att_reg_lusitania_emerita_augusta",
	"att_reg_lusitania_pax_augusta",
	"att_reg_mauretania_tamousiga",
	"att_reg_mauretania_tingis",
	"att_reg_maxima_sequanorum_argentoratum",
	"att_reg_maxima_sequanorum_vesontio",
	"att_reg_osroene_nisibis",
	"att_reg_pannonia_savaria",
	"att_reg_pannonia_sirmium",
	"att_reg_pannonia_sopianae",
	"att_reg_raetia_et_noricum_augusta_vindelicorum",
	"att_reg_raetia_et_noricum_iuvavum",
	"att_reg_scandza_hrefnesholt"
};

REGIONS_1350 = {
	"att_reg_caledonia_et_hibernia_eildon",
	"att_reg_caledonia_et_hibernia_tuesis",
	"att_reg_dacia_apulum",
	"att_reg_frisia_angulus",
	"att_reg_frisia_flevum",
	"att_reg_frisia_tulifurdum",
	"att_reg_germania_aregelia",
	"att_reg_germania_uburzis",
	"att_reg_germano_sarmatia_duna",
	"att_reg_gothiscandza_ascaucalis",
	"att_reg_gothiscandza_gothiscandza",
	"att_reg_gothiscandza_rugion",
	"att_reg_hercynia_casurgis",
	"att_reg_scandza_alabu",
	"att_reg_scandza_hafn"
};

REGIONS_1351 = {
	"att_reg_germania_lupfurdum",
	"att_reg_hercynia_nitrahwa",
	"att_reg_hercynia_budorgis",
	"att_reg_germano_sarmatia_oium",
	"att_reg_transcarpathia_belz",
	"att_reg_transcarpathia_leopolis"
};

REGIONS_1352 = {
	"att_reg_transcarpathia_arheimar",
	"att_reg_germano_sarmatia_palteskja",
	"att_reg_hyperborea_kariskos"
};